"use strict";
/* Generated by tools/build-qbank.js — do not edit by hand. */
(function () {
  var data = {
 "slug": "awards-honours",
 "name": "Awards & Honours",
 "icon": "medal",
 "group": "General Knowledge",
 "exams": [
  "ssc-cgl",
  "ssc-chsl",
  "railways"
 ],
 "blurb": "Civilian, gallantry, literary and international awards.",
 "count": 201,
 "questions": [
  {
   "id": "awards-honours-00001",
   "q": "Which is the highest civilian award of India?",
   "o": [
    "Padma Vibhushan",
    "Bharat Ratna",
    "Padma Bhushan",
    "Padma Shri"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "The Bharat Ratna is the highest civilian award of India."
  },
  {
   "id": "awards-honours-00002",
   "q": "Who was the first recipient of the Bharat Ratna?",
   "o": [
    "Jawaharlal Nehru",
    "C. Rajagopalachari",
    "S. Radhakrishnan",
    "C. V. Raman"
   ],
   "a": 1,
   "t": "Curated",
   "l": 3,
   "s": "curated",
   "e": "C. Rajagopalachari was among the first recipients in 1954."
  },
  {
   "id": "awards-honours-00003",
   "q": "Which is the highest gallantry award of India?",
   "o": [
    "Ashoka Chakra",
    "Param Vir Chakra",
    "Maha Vir Chakra",
    "Vir Chakra"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "The Param Vir Chakra is the highest wartime gallantry award."
  },
  {
   "id": "awards-honours-00004",
   "q": "Who was the first woman to receive the Bharat Ratna?",
   "o": [
    "Indira Gandhi",
    "Mother Teresa",
    "Sarojini Naidu",
    "Aruna Asaf Ali"
   ],
   "a": 0,
   "t": "Curated",
   "l": 3,
   "s": "curated",
   "e": "Indira Gandhi received the Bharat Ratna in 1971."
  },
  {
   "id": "awards-honours-00005",
   "q": "The Jnanpith Award is given for excellence in:",
   "o": [
    "Cinema",
    "Literature",
    "Science",
    "Sports"
   ],
   "a": 1,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "The Jnanpith Award honours writers in Indian languages."
  },
  {
   "id": "awards-honours-00006",
   "q": "The Dada Saheb Phalke Award is associated with:",
   "o": [
    "Music",
    "Cinema",
    "Painting",
    "Theatre"
   ],
   "a": 1,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "It is the highest award in Indian cinema."
  },
  {
   "id": "awards-honours-00007",
   "q": "Which award is the highest sporting honour of India?",
   "o": [
    "Arjuna Award",
    "Dronacharya Award",
    "Major Dhyan Chand Khel Ratna",
    "Dhyan Chand Award"
   ],
   "a": 2,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "The Khel Ratna is India's highest sporting honour."
  },
  {
   "id": "awards-honours-00008",
   "q": "The Dronacharya Award is given to:",
   "o": [
    "Players",
    "Coaches",
    "Umpires",
    "Sports journalists"
   ],
   "a": 1,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "The Dronacharya Award recognises outstanding coaches."
  },
  {
   "id": "awards-honours-00009",
   "q": "In which year was the Nobel Prize first awarded?",
   "o": [
    "1895",
    "1901",
    "1913",
    "1920"
   ],
   "a": 1,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "The first Nobel Prizes were awarded in 1901."
  },
  {
   "id": "awards-honours-00010",
   "q": "Who was the first Indian to win a Nobel Prize?",
   "o": [
    "C. V. Raman",
    "Rabindranath Tagore",
    "Mother Teresa",
    "Amartya Sen"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Rabindranath Tagore won the Nobel Prize in Literature in 1913."
  },
  {
   "id": "awards-honours-00011",
   "q": "C. V. Raman won the Nobel Prize in which field?",
   "o": [
    "Physics",
    "Chemistry",
    "Medicine",
    "Literature"
   ],
   "a": 0,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "C. V. Raman won the Nobel Prize in Physics in 1930."
  },
  {
   "id": "awards-honours-00012",
   "q": "Amartya Sen won the Nobel Prize in which field?",
   "o": [
    "Economics",
    "Physics",
    "Peace",
    "Literature"
   ],
   "a": 0,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "Amartya Sen won the Nobel Memorial Prize in Economic Sciences in 1998."
  },
  {
   "id": "awards-honours-00013",
   "q": "The Ramon Magsaysay Award is often called the:",
   "o": [
    "Asian Nobel Prize",
    "European Nobel Prize",
    "Indian Nobel Prize",
    "World Peace Prize"
   ],
   "a": 0,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "It is popularly known as Asia's Nobel Prize."
  },
  {
   "id": "awards-honours-00014",
   "q": "Which award is given for bravery by children in India?",
   "o": [
    "National Bravery Award",
    "Ashoka Chakra",
    "Kirti Chakra",
    "Shaurya Chakra"
   ],
   "a": 0,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "The National Bravery Award honours brave children."
  },
  {
   "id": "awards-honours-00015",
   "q": "The Pulitzer Prize is associated with:",
   "o": [
    "Journalism",
    "Medicine",
    "Physics",
    "Music only"
   ],
   "a": 0,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "The Pulitzer Prize mainly recognises journalism and letters."
  },
  {
   "id": "awards-honours-00016",
   "q": "Which award is given to Indian scientists for research in science and technology?",
   "o": [
    "Shanti Swarup Bhatnagar Prize",
    "Dada Saheb Phalke Award",
    "Jnanpith Award",
    "Vyas Samman"
   ],
   "a": 0,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "The Shanti Swarup Bhatnagar Prize is a prestigious Indian science award."
  },
  {
   "id": "awards-honours-00017",
   "q": "The Gandhi Peace Prize is awarded by the Government of India for:",
   "o": [
    "Social and economic development",
    "Cinema",
    "Sports",
    "Literature"
   ],
   "a": 0,
   "t": "Curated",
   "l": 3,
   "s": "curated",
   "e": "It recognises contributions to social, economic and political transformation."
  },
  {
   "id": "awards-honours-00018",
   "q": "Which is the highest award for valour in peacetime in India?",
   "o": [
    "Param Vir Chakra",
    "Ashoka Chakra",
    "Maha Vir Chakra",
    "Sena Medal"
   ],
   "a": 1,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "The Ashoka Chakra is awarded for peacetime gallantry."
  },
  {
   "id": "awards-honours-00019",
   "q": "The Oscar award is associated with which field?",
   "o": [
    "Cinema",
    "Music",
    "Literature",
    "Science"
   ],
   "a": 0,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "The Academy Awards, known as Oscars, honour cinema."
  },
  {
   "id": "awards-honours-00020",
   "q": "Which award is given for lifetime achievement in Indian sports?",
   "o": [
    "Dhyan Chand Award",
    "Arjuna Award",
    "Khel Ratna",
    "Dronacharya Award"
   ],
   "a": 0,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "The Dhyan Chand Award honours lifetime contribution to sports."
  },
  {
   "id": "awards-honours-00021",
   "q": "Who was the first Indian woman to win the Miss World title?",
   "o": [
    "Aishwarya Rai",
    "Reita Faria",
    "Sushmita Sen",
    "Priyanka Chopra"
   ],
   "a": 1,
   "t": "Curated",
   "l": 3,
   "s": "curated",
   "e": "Reita Faria won the Miss World title in 1966."
  },
  {
   "id": "awards-honours-00022",
   "q": "Right Livelihood Award is associated with which of the following?",
   "o": [
    "Highest military decoration of India",
    "Alternative Nobel Prize",
    "Third highest civilian award of India",
    "Outstanding performance in Indian sports"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Right Livelihood Award — Alternative Nobel Prize."
  },
  {
   "id": "awards-honours-00023",
   "q": "Arjuna Award is associated with which of the following?",
   "o": [
    "Asian award for public service",
    "International award for Physics, Chemistry, Medicine, Literature, Peace and Economics",
    "Highest military decoration of India",
    "Outstanding performance in Indian sports"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Arjuna Award — Outstanding performance in Indian sports."
  },
  {
   "id": "awards-honours-00024",
   "q": "Indira Gandhi Prize is associated with which of the following?",
   "o": [
    "American award for films",
    "American award for music",
    "Asian award for public service",
    "Indian award for peace, disarmament and development"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Indira Gandhi Prize — Indian award for peace, disarmament and development."
  },
  {
   "id": "awards-honours-00025",
   "q": "Pulitzer Prize is associated with which of the following?",
   "o": [
    "Indian award in agricultural science",
    "American award for journalism and letters",
    "Indian literary award",
    "Indian award in science and technology"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Pulitzer Prize — American award for journalism and letters."
  },
  {
   "id": "awards-honours-00026",
   "q": "National Film Award is associated with which of the following?",
   "o": [
    "Awards for Indian cinema",
    "UNESCO award for popularisation of science",
    "Asian award for public service",
    "Performing arts award of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "National Film Award — Awards for Indian cinema."
  },
  {
   "id": "awards-honours-00027",
   "q": "Sangeet Natak Akademi Award is associated with which of the following?",
   "o": [
    "Coaching excellence in Indian sports",
    "Performing arts award of India",
    "British award for fiction",
    "Alternative Nobel Prize"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Sangeet Natak Akademi Award — Performing arts award of India."
  },
  {
   "id": "awards-honours-00028",
   "q": "Kirti Chakra is associated with which of the following?",
   "o": [
    "Asian award for public service",
    "Third highest civilian award of India",
    "Second highest peacetime gallantry award of India",
    "Second highest civilian award of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Kirti Chakra — Second highest peacetime gallantry award of India."
  },
  {
   "id": "awards-honours-00029",
   "q": "Jnanpith Award is associated with which of the following?",
   "o": [
    "Highest literary award of India",
    "Performing arts award of India",
    "Highest civilian award of India",
    "American award for journalism and letters"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Jnanpith Award — Highest literary award of India."
  },
  {
   "id": "awards-honours-00030",
   "q": "National Bravery Award is associated with which of the following?",
   "o": [
    "Coaching excellence in Indian sports",
    "Award for brave children in India",
    "Second highest peacetime gallantry award of India",
    "Highest military decoration of India"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "National Bravery Award — Award for brave children in India."
  },
  {
   "id": "awards-honours-00031",
   "q": "Shanti Swarup Bhatnagar Prize is associated with which of the following?",
   "o": [
    "Indian award in science and technology",
    "American award for music",
    "Highest civilian award of India",
    "Third highest peacetime gallantry award of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Shanti Swarup Bhatnagar Prize — Indian award in science and technology."
  },
  {
   "id": "awards-honours-00032",
   "q": "Ashoka Chakra is associated with which of the following?",
   "o": [
    "Indian literary award",
    "Second highest military decoration of India",
    "Second highest peacetime gallantry award of India",
    "Highest peacetime gallantry award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Ashoka Chakra — Highest peacetime gallantry award of India."
  },
  {
   "id": "awards-honours-00033",
   "q": "Vyas Samman is associated with which of the following?",
   "o": [
    "Second highest civilian award of India",
    "Award for progress in spiritual matters",
    "Indian literary award",
    "Highest peacetime gallantry award of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Vyas Samman — Indian literary award."
  },
  {
   "id": "awards-honours-00034",
   "q": "Ramon Magsaysay Award is associated with which of the following?",
   "o": [
    "Third highest military decoration of India",
    "Lifetime achievement in Indian sports",
    "Asian award for public service",
    "Indian award in science and technology"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Ramon Magsaysay Award — Asian award for public service."
  },
  {
   "id": "awards-honours-00035",
   "q": "Maha Vir Chakra is associated with which of the following?",
   "o": [
    "Second highest military decoration of India",
    "Second highest civilian award of India",
    "Indian literary award",
    "American award for films"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Maha Vir Chakra — Second highest military decoration of India."
  },
  {
   "id": "awards-honours-00036",
   "q": "Padma Bhushan is associated with which of the following?",
   "o": [
    "Second highest civilian award of India",
    "American award for music",
    "Second highest peacetime gallantry award of India",
    "Third highest civilian award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Padma Bhushan — Third highest civilian award of India."
  },
  {
   "id": "awards-honours-00037",
   "q": "Saraswati Samman is associated with which of the following?",
   "o": [
    "Awards for Indian cinema",
    "British award for fiction",
    "Second highest military decoration of India",
    "Indian literary award"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Saraswati Samman — Indian literary award."
  },
  {
   "id": "awards-honours-00038",
   "q": "Academy Award (Oscar) is associated with which of the following?",
   "o": [
    "American award for films",
    "Second highest civilian award of India",
    "Award for brave children in India",
    "Indian award for social work and peace"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Academy Award (Oscar) — American award for films."
  },
  {
   "id": "awards-honours-00039",
   "q": "Infosys Prize is associated with which of the following?",
   "o": [
    "Alternative Nobel Prize",
    "Indian award for social work and peace",
    "Highest sporting honour of India",
    "Indian award for research"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Infosys Prize — Indian award for research."
  },
  {
   "id": "awards-honours-00040",
   "q": "Shaurya Chakra is associated with which of the following?",
   "o": [
    "Lifetime achievement in Indian sports",
    "Alternative Nobel Prize",
    "Third highest peacetime gallantry award of India",
    "Literary award for Indian languages"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Shaurya Chakra — Third highest peacetime gallantry award of India."
  },
  {
   "id": "awards-honours-00041",
   "q": "Param Vir Chakra is associated with which of the following?",
   "o": [
    "American award for music",
    "British award for fiction",
    "Indian award in science and technology",
    "Highest military decoration of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Param Vir Chakra — Highest military decoration of India."
  },
  {
   "id": "awards-honours-00042",
   "q": "Booker Prize is associated with which of the following?",
   "o": [
    "British award for fiction",
    "Performing arts award of India",
    "Indian award in science and technology",
    "Highest award in Indian cinema"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Booker Prize — British award for fiction."
  },
  {
   "id": "awards-honours-00043",
   "q": "Padma Vibhushan is associated with which of the following?",
   "o": [
    "Alternative Nobel Prize",
    "Second highest civilian award of India",
    "Highest civilian award of India",
    "Highest literary award of India"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Padma Vibhushan — Second highest civilian award of India."
  },
  {
   "id": "awards-honours-00044",
   "q": "Nobel Prize is associated with which of the following?",
   "o": [
    "Indian award for social work and peace",
    "Highest military decoration of India",
    "Indian literary award",
    "International award for Physics, Chemistry, Medicine, Literature, Peace and Economics"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Nobel Prize — International award for Physics, Chemistry, Medicine, Literature, Peace and Economics."
  },
  {
   "id": "awards-honours-00045",
   "q": "Gandhi Peace Prize is associated with which of the following?",
   "o": [
    "British award for fiction",
    "Indian award for social work and peace",
    "Second highest peacetime gallantry award of India",
    "Awards for Indian cinema"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Gandhi Peace Prize — Indian award for social work and peace."
  },
  {
   "id": "awards-honours-00046",
   "q": "Kalinga Prize is associated with which of the following?",
   "o": [
    "Highest peacetime gallantry award of India",
    "Indian literary award",
    "Indian award for peace, disarmament and development",
    "UNESCO award for popularisation of science"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Kalinga Prize — UNESCO award for popularisation of science."
  },
  {
   "id": "awards-honours-00047",
   "q": "Vir Chakra is associated with which of the following?",
   "o": [
    "Highest award in Indian cinema",
    "American award for music",
    "Third highest military decoration of India",
    "Alternative Nobel Prize"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Vir Chakra — Third highest military decoration of India."
  },
  {
   "id": "awards-honours-00048",
   "q": "Borlaug Award is associated with which of the following?",
   "o": [
    "Award for progress in spiritual matters",
    "Lifetime achievement in Indian sports",
    "Indian award in agricultural science",
    "British award for fiction"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Borlaug Award — Indian award in agricultural science."
  },
  {
   "id": "awards-honours-00049",
   "q": "Bharat Ratna is associated with which of the following?",
   "o": [
    "UNESCO award for popularisation of science",
    "Highest civilian award of India",
    "Coaching excellence in Indian sports",
    "Asian award for public service"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Bharat Ratna — Highest civilian award of India."
  },
  {
   "id": "awards-honours-00050",
   "q": "Templeton Prize is associated with which of the following?",
   "o": [
    "UNESCO award for popularisation of science",
    "Award for progress in spiritual matters",
    "Outstanding performance in Indian sports",
    "Lifetime achievement in Indian sports"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Templeton Prize — Award for progress in spiritual matters."
  },
  {
   "id": "awards-honours-00051",
   "q": "Padma Shri is associated with which of the following?",
   "o": [
    "Indian literary award",
    "Fourth highest civilian award of India",
    "American award for films",
    "American award for journalism and letters"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Padma Shri — Fourth highest civilian award of India."
  },
  {
   "id": "awards-honours-00052",
   "q": "Dronacharya Award is associated with which of the following?",
   "o": [
    "Indian award for peace, disarmament and development",
    "Highest peacetime gallantry award of India",
    "Coaching excellence in Indian sports",
    "Highest civilian award of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Dronacharya Award — Coaching excellence in Indian sports."
  },
  {
   "id": "awards-honours-00053",
   "q": "Grammy Award is associated with which of the following?",
   "o": [
    "American award for music",
    "Lifetime achievement in Indian sports",
    "Third highest military decoration of India",
    "UNESCO award for popularisation of science"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Grammy Award — American award for music."
  },
  {
   "id": "awards-honours-00054",
   "q": "Major Dhyan Chand Khel Ratna Award is associated with which of the following?",
   "o": [
    "Highest sporting honour of India",
    "Highest award in Indian cinema",
    "Indian award for research",
    "Third highest civilian award of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Major Dhyan Chand Khel Ratna Award — Highest sporting honour of India."
  },
  {
   "id": "awards-honours-00055",
   "q": "Dada Saheb Phalke Award is associated with which of the following?",
   "o": [
    "American award for films",
    "Third highest civilian award of India",
    "Third highest military decoration of India",
    "Highest award in Indian cinema"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Dada Saheb Phalke Award — Highest award in Indian cinema."
  },
  {
   "id": "awards-honours-00056",
   "q": "Dhyan Chand Award is associated with which of the following?",
   "o": [
    "Second highest peacetime gallantry award of India",
    "Asian award for public service",
    "Lifetime achievement in Indian sports",
    "Indian award for social work and peace"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Dhyan Chand Award — Lifetime achievement in Indian sports."
  },
  {
   "id": "awards-honours-00057",
   "q": "Sahitya Akademi Award is associated with which of the following?",
   "o": [
    "Literary award for Indian languages",
    "Highest literary award of India",
    "Performing arts award of India",
    "Second highest civilian award of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 2,
   "s": "generated",
   "e": "Sahitya Akademi Award — Literary award for Indian languages."
  },
  {
   "id": "awards-honours-00058",
   "q": "Which award is described as: Indian literary award?",
   "o": [
    "Vir Chakra",
    "Ashoka Chakra",
    "Right Livelihood Award",
    "Vyas Samman"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Indian literary award describes Vyas Samman."
  },
  {
   "id": "awards-honours-00059",
   "q": "Which award is described as: UNESCO award for popularisation of science?",
   "o": [
    "Booker Prize",
    "Shanti Swarup Bhatnagar Prize",
    "Dronacharya Award",
    "Kalinga Prize"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "UNESCO award for popularisation of science describes Kalinga Prize."
  },
  {
   "id": "awards-honours-00060",
   "q": "Which award is described as: American award for films?",
   "o": [
    "Sahitya Akademi Award",
    "Vir Chakra",
    "Academy Award (Oscar)",
    "Saraswati Samman"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "American award for films describes Academy Award (Oscar)."
  },
  {
   "id": "awards-honours-00061",
   "q": "Which award is described as: Asian award for public service?",
   "o": [
    "Param Vir Chakra",
    "Ramon Magsaysay Award",
    "Borlaug Award",
    "Kalinga Prize"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Asian award for public service describes Ramon Magsaysay Award."
  },
  {
   "id": "awards-honours-00062",
   "q": "Which award is described as: Performing arts award of India?",
   "o": [
    "Sangeet Natak Akademi Award",
    "Dada Saheb Phalke Award",
    "Major Dhyan Chand Khel Ratna Award",
    "Arjuna Award"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Performing arts award of India describes Sangeet Natak Akademi Award."
  },
  {
   "id": "awards-honours-00063",
   "q": "Which award is described as: Indian award in agricultural science?",
   "o": [
    "Booker Prize",
    "Padma Vibhushan",
    "Padma Bhushan",
    "Borlaug Award"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Indian award in agricultural science describes Borlaug Award."
  },
  {
   "id": "awards-honours-00064",
   "q": "Which award is described as: Award for brave children in India?",
   "o": [
    "Sangeet Natak Akademi Award",
    "National Bravery Award",
    "Grammy Award",
    "Gandhi Peace Prize"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Award for brave children in India describes National Bravery Award."
  },
  {
   "id": "awards-honours-00065",
   "q": "Which award is described as: Coaching excellence in Indian sports?",
   "o": [
    "Padma Vibhushan",
    "Sahitya Akademi Award",
    "Dronacharya Award",
    "Saraswati Samman"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Coaching excellence in Indian sports describes Dronacharya Award."
  },
  {
   "id": "awards-honours-00066",
   "q": "Which award is described as: Outstanding performance in Indian sports?",
   "o": [
    "Infosys Prize",
    "Padma Bhushan",
    "Padma Shri",
    "Arjuna Award"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Outstanding performance in Indian sports describes Arjuna Award."
  },
  {
   "id": "awards-honours-00067",
   "q": "Which award is described as: Highest civilian award of India?",
   "o": [
    "Borlaug Award",
    "Major Dhyan Chand Khel Ratna Award",
    "Padma Bhushan",
    "Bharat Ratna"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Highest civilian award of India describes Bharat Ratna."
  },
  {
   "id": "awards-honours-00068",
   "q": "Which award is described as: Second highest military decoration of India?",
   "o": [
    "Grammy Award",
    "Pulitzer Prize",
    "Maha Vir Chakra",
    "Kalinga Prize"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Second highest military decoration of India describes Maha Vir Chakra."
  },
  {
   "id": "awards-honours-00069",
   "q": "Which award is described as: Awards for Indian cinema?",
   "o": [
    "National Film Award",
    "Shaurya Chakra",
    "Major Dhyan Chand Khel Ratna Award",
    "Shanti Swarup Bhatnagar Prize"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Awards for Indian cinema describes National Film Award."
  },
  {
   "id": "awards-honours-00070",
   "q": "Which award is described as: British award for fiction?",
   "o": [
    "Booker Prize",
    "Padma Vibhushan",
    "Ramon Magsaysay Award",
    "Maha Vir Chakra"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "British award for fiction describes Booker Prize."
  },
  {
   "id": "awards-honours-00071",
   "q": "Which award is described as: Second highest peacetime gallantry award of India?",
   "o": [
    "Kirti Chakra",
    "Ashoka Chakra",
    "Bharat Ratna",
    "Maha Vir Chakra"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Second highest peacetime gallantry award of India describes Kirti Chakra."
  },
  {
   "id": "awards-honours-00072",
   "q": "Which award is described as: Indian literary award?",
   "o": [
    "Major Dhyan Chand Khel Ratna Award",
    "Infosys Prize",
    "Saraswati Samman",
    "Dronacharya Award"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Indian literary award describes Saraswati Samman."
  },
  {
   "id": "awards-honours-00073",
   "q": "Which award is described as: Indian award in science and technology?",
   "o": [
    "Shaurya Chakra",
    "Jnanpith Award",
    "Academy Award (Oscar)",
    "Shanti Swarup Bhatnagar Prize"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Indian award in science and technology describes Shanti Swarup Bhatnagar Prize."
  },
  {
   "id": "awards-honours-00074",
   "q": "Which award is described as: Highest sporting honour of India?",
   "o": [
    "Right Livelihood Award",
    "Param Vir Chakra",
    "Major Dhyan Chand Khel Ratna Award",
    "Ashoka Chakra"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Highest sporting honour of India describes Major Dhyan Chand Khel Ratna Award."
  },
  {
   "id": "awards-honours-00075",
   "q": "Which award is described as: American award for journalism and letters?",
   "o": [
    "Pulitzer Prize",
    "Booker Prize",
    "Padma Shri",
    "Infosys Prize"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "American award for journalism and letters describes Pulitzer Prize."
  },
  {
   "id": "awards-honours-00076",
   "q": "Which award is described as: Highest literary award of India?",
   "o": [
    "Templeton Prize",
    "Infosys Prize",
    "Jnanpith Award",
    "Pulitzer Prize"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Highest literary award of India describes Jnanpith Award."
  },
  {
   "id": "awards-honours-00077",
   "q": "Which award is described as: Alternative Nobel Prize?",
   "o": [
    "Right Livelihood Award",
    "Padma Bhushan",
    "Booker Prize",
    "Sangeet Natak Akademi Award"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Alternative Nobel Prize describes Right Livelihood Award."
  },
  {
   "id": "awards-honours-00078",
   "q": "Which award is described as: Indian award for research?",
   "o": [
    "Kalinga Prize",
    "Infosys Prize",
    "Pulitzer Prize",
    "Shanti Swarup Bhatnagar Prize"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Indian award for research describes Infosys Prize."
  },
  {
   "id": "awards-honours-00079",
   "q": "Which award is described as: Third highest civilian award of India?",
   "o": [
    "Padma Bhushan",
    "Kalinga Prize",
    "Borlaug Award",
    "Maha Vir Chakra"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Third highest civilian award of India describes Padma Bhushan."
  },
  {
   "id": "awards-honours-00080",
   "q": "Which award is described as: Highest peacetime gallantry award of India?",
   "o": [
    "Saraswati Samman",
    "Ashoka Chakra",
    "Nobel Prize",
    "Shanti Swarup Bhatnagar Prize"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Highest peacetime gallantry award of India describes Ashoka Chakra."
  },
  {
   "id": "awards-honours-00081",
   "q": "Which award is described as: Highest military decoration of India?",
   "o": [
    "Param Vir Chakra",
    "Gandhi Peace Prize",
    "Jnanpith Award",
    "Pulitzer Prize"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Highest military decoration of India describes Param Vir Chakra."
  },
  {
   "id": "awards-honours-00082",
   "q": "Which award is described as: Second highest civilian award of India?",
   "o": [
    "Vir Chakra",
    "National Bravery Award",
    "Padma Vibhushan",
    "Infosys Prize"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Second highest civilian award of India describes Padma Vibhushan."
  },
  {
   "id": "awards-honours-00083",
   "q": "Which award is described as: Third highest military decoration of India?",
   "o": [
    "Maha Vir Chakra",
    "Vir Chakra",
    "Infosys Prize",
    "Vyas Samman"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Third highest military decoration of India describes Vir Chakra."
  },
  {
   "id": "awards-honours-00084",
   "q": "Which award is described as: Award for progress in spiritual matters?",
   "o": [
    "Infosys Prize",
    "Templeton Prize",
    "Arjuna Award",
    "Bharat Ratna"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Award for progress in spiritual matters describes Templeton Prize."
  },
  {
   "id": "awards-honours-00085",
   "q": "Which award is described as: Fourth highest civilian award of India?",
   "o": [
    "National Bravery Award",
    "Padma Shri",
    "Jnanpith Award",
    "Booker Prize"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Fourth highest civilian award of India describes Padma Shri."
  },
  {
   "id": "awards-honours-00086",
   "q": "Which award is described as: Literary award for Indian languages?",
   "o": [
    "Templeton Prize",
    "Booker Prize",
    "Sahitya Akademi Award",
    "Kirti Chakra"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Literary award for Indian languages describes Sahitya Akademi Award."
  },
  {
   "id": "awards-honours-00087",
   "q": "Which award is described as: Third highest peacetime gallantry award of India?",
   "o": [
    "Right Livelihood Award",
    "Shaurya Chakra",
    "Maha Vir Chakra",
    "Major Dhyan Chand Khel Ratna Award"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Third highest peacetime gallantry award of India describes Shaurya Chakra."
  },
  {
   "id": "awards-honours-00088",
   "q": "Which award is described as: American award for music?",
   "o": [
    "Dada Saheb Phalke Award",
    "Grammy Award",
    "Right Livelihood Award",
    "Major Dhyan Chand Khel Ratna Award"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "American award for music describes Grammy Award."
  },
  {
   "id": "awards-honours-00089",
   "q": "Which award is described as: Indian award for peace, disarmament and development?",
   "o": [
    "Kirti Chakra",
    "Infosys Prize",
    "Dhyan Chand Award",
    "Indira Gandhi Prize"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Indian award for peace, disarmament and development describes Indira Gandhi Prize."
  },
  {
   "id": "awards-honours-00090",
   "q": "Which award is described as: Indian award for social work and peace?",
   "o": [
    "Sangeet Natak Akademi Award",
    "Gandhi Peace Prize",
    "Indira Gandhi Prize",
    "Dada Saheb Phalke Award"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Indian award for social work and peace describes Gandhi Peace Prize."
  },
  {
   "id": "awards-honours-00091",
   "q": "Which award is described as: Lifetime achievement in Indian sports?",
   "o": [
    "Maha Vir Chakra",
    "Pulitzer Prize",
    "Dhyan Chand Award",
    "Right Livelihood Award"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Lifetime achievement in Indian sports describes Dhyan Chand Award."
  },
  {
   "id": "awards-honours-00092",
   "q": "Which award is described as: International award for Physics, Chemistry, Medicine, Literature, Peace and Economics?",
   "o": [
    "National Bravery Award",
    "Ashoka Chakra",
    "Infosys Prize",
    "Nobel Prize"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "International award for Physics, Chemistry, Medicine, Literature, Peace and Economics describes Nobel Prize."
  },
  {
   "id": "awards-honours-00093",
   "q": "Which award is described as: Highest award in Indian cinema?",
   "o": [
    "Kirti Chakra",
    "Padma Bhushan",
    "Dada Saheb Phalke Award",
    "Arjuna Award"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Highest award in Indian cinema describes Dada Saheb Phalke Award."
  },
  {
   "id": "awards-honours-00094",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Param Vir Chakra - Highest military decoration of India",
    "Param Vir Chakra - American award for journalism and letters",
    "Param Vir Chakra - Highest award in Indian cinema",
    "Param Vir Chakra - Lifetime achievement in Indian sports"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Param Vir Chakra - Highest military decoration of India is correctly matched."
  },
  {
   "id": "awards-honours-00095",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Param Vir Chakra - Awards for Indian cinema",
    "Param Vir Chakra - Highest award in Indian cinema",
    "Param Vir Chakra - Indian literary award",
    "Param Vir Chakra - Highest military decoration of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Param Vir Chakra - Highest military decoration of India is correctly matched."
  },
  {
   "id": "awards-honours-00096",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Borlaug Award - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics",
    "Borlaug Award - Third highest civilian award of India",
    "Borlaug Award - Indian award in agricultural science",
    "Borlaug Award - Award for progress in spiritual matters"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Borlaug Award - Indian award in agricultural science is correctly matched."
  },
  {
   "id": "awards-honours-00097",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Borlaug Award - Coaching excellence in Indian sports",
    "Borlaug Award - Awards for Indian cinema",
    "Borlaug Award - Indian award in agricultural science",
    "Borlaug Award - Highest peacetime gallantry award of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Borlaug Award - Indian award in agricultural science is correctly matched."
  },
  {
   "id": "awards-honours-00098",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Vyas Samman - Indian literary award",
    "Vyas Samman - Second highest military decoration of India",
    "Vyas Samman - Third highest peacetime gallantry award of India",
    "Vyas Samman - Indian award for research"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Vyas Samman - Indian literary award is correctly matched."
  },
  {
   "id": "awards-honours-00099",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Vyas Samman - Second highest peacetime gallantry award of India",
    "Vyas Samman - Highest sporting honour of India",
    "Vyas Samman - Awards for Indian cinema",
    "Vyas Samman - Indian literary award"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Vyas Samman - Indian literary award is correctly matched."
  },
  {
   "id": "awards-honours-00100",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Templeton Prize - Awards for Indian cinema",
    "Templeton Prize - American award for journalism and letters",
    "Templeton Prize - Indian literary award",
    "Templeton Prize - Award for progress in spiritual matters"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Templeton Prize - Award for progress in spiritual matters is correctly matched."
  },
  {
   "id": "awards-honours-00101",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Templeton Prize - Third highest civilian award of India",
    "Templeton Prize - Indian literary award",
    "Templeton Prize - Third highest military decoration of India",
    "Templeton Prize - Award for progress in spiritual matters"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Templeton Prize - Award for progress in spiritual matters is correctly matched."
  },
  {
   "id": "awards-honours-00102",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Academy Award (Oscar) - Indian award for social work and peace",
    "Academy Award (Oscar) - Alternative Nobel Prize",
    "Academy Award (Oscar) - American award for films",
    "Academy Award (Oscar) - Second highest peacetime gallantry award of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Academy Award (Oscar) - American award for films is correctly matched."
  },
  {
   "id": "awards-honours-00103",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Academy Award (Oscar) - UNESCO award for popularisation of science",
    "Academy Award (Oscar) - Awards for Indian cinema",
    "Academy Award (Oscar) - American award for films",
    "Academy Award (Oscar) - Indian award for research"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Academy Award (Oscar) - American award for films is correctly matched."
  },
  {
   "id": "awards-honours-00104",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Nobel Prize - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics",
    "Nobel Prize - Indian literary award",
    "Nobel Prize - Indian award for research",
    "Nobel Prize - Indian award in agricultural science"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Nobel Prize - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics is correctly matched."
  },
  {
   "id": "awards-honours-00105",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Nobel Prize - Indian award in agricultural science",
    "Nobel Prize - Third highest military decoration of India",
    "Nobel Prize - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics",
    "Nobel Prize - Second highest military decoration of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Nobel Prize - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics is correctly matched."
  },
  {
   "id": "awards-honours-00106",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Booker Prize - British award for fiction",
    "Booker Prize - Award for brave children in India",
    "Booker Prize - Highest literary award of India",
    "Booker Prize - Indian award for peace, disarmament and development"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Booker Prize - British award for fiction is correctly matched."
  },
  {
   "id": "awards-honours-00107",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Booker Prize - British award for fiction",
    "Booker Prize - Second highest civilian award of India",
    "Booker Prize - Coaching excellence in Indian sports",
    "Booker Prize - Performing arts award of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Booker Prize - British award for fiction is correctly matched."
  },
  {
   "id": "awards-honours-00108",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Jnanpith Award - Second highest civilian award of India",
    "Jnanpith Award - Indian literary award",
    "Jnanpith Award - American award for journalism and letters",
    "Jnanpith Award - Highest literary award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Jnanpith Award - Highest literary award of India is correctly matched."
  },
  {
   "id": "awards-honours-00109",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Jnanpith Award - Award for progress in spiritual matters",
    "Jnanpith Award - Indian award in science and technology",
    "Jnanpith Award - Highest literary award of India",
    "Jnanpith Award - Outstanding performance in Indian sports"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Jnanpith Award - Highest literary award of India is correctly matched."
  },
  {
   "id": "awards-honours-00110",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Vir Chakra - Highest civilian award of India",
    "Vir Chakra - Third highest military decoration of India",
    "Vir Chakra - Literary award for Indian languages",
    "Vir Chakra - American award for films"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Vir Chakra - Third highest military decoration of India is correctly matched."
  },
  {
   "id": "awards-honours-00111",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Vir Chakra - Awards for Indian cinema",
    "Vir Chakra - Indian award in agricultural science",
    "Vir Chakra - Lifetime achievement in Indian sports",
    "Vir Chakra - Third highest military decoration of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Vir Chakra - Third highest military decoration of India is correctly matched."
  },
  {
   "id": "awards-honours-00112",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Dhyan Chand Award - Third highest peacetime gallantry award of India",
    "Dhyan Chand Award - Asian award for public service",
    "Dhyan Chand Award - Highest award in Indian cinema",
    "Dhyan Chand Award - Lifetime achievement in Indian sports"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Dhyan Chand Award - Lifetime achievement in Indian sports is correctly matched."
  },
  {
   "id": "awards-honours-00113",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Dhyan Chand Award - Third highest civilian award of India",
    "Dhyan Chand Award - Lifetime achievement in Indian sports",
    "Dhyan Chand Award - American award for music",
    "Dhyan Chand Award - Awards for Indian cinema"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Dhyan Chand Award - Lifetime achievement in Indian sports is correctly matched."
  },
  {
   "id": "awards-honours-00114",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Padma Shri - Second highest military decoration of India",
    "Padma Shri - Awards for Indian cinema",
    "Padma Shri - Indian award for research",
    "Padma Shri - Fourth highest civilian award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Padma Shri - Fourth highest civilian award of India is correctly matched."
  },
  {
   "id": "awards-honours-00115",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Padma Shri - Second highest military decoration of India",
    "Padma Shri - Awards for Indian cinema",
    "Padma Shri - Indian literary award",
    "Padma Shri - Fourth highest civilian award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Padma Shri - Fourth highest civilian award of India is correctly matched."
  },
  {
   "id": "awards-honours-00116",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Indira Gandhi Prize - Highest military decoration of India",
    "Indira Gandhi Prize - Lifetime achievement in Indian sports",
    "Indira Gandhi Prize - Indian award for peace, disarmament and development",
    "Indira Gandhi Prize - American award for journalism and letters"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Indira Gandhi Prize - Indian award for peace, disarmament and development is correctly matched."
  },
  {
   "id": "awards-honours-00117",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Indira Gandhi Prize - Highest military decoration of India",
    "Indira Gandhi Prize - Third highest peacetime gallantry award of India",
    "Indira Gandhi Prize - Indian award for peace, disarmament and development",
    "Indira Gandhi Prize - Lifetime achievement in Indian sports"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Indira Gandhi Prize - Indian award for peace, disarmament and development is correctly matched."
  },
  {
   "id": "awards-honours-00118",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Kalinga Prize - Indian award in agricultural science",
    "Kalinga Prize - American award for music",
    "Kalinga Prize - Literary award for Indian languages",
    "Kalinga Prize - UNESCO award for popularisation of science"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Kalinga Prize - UNESCO award for popularisation of science is correctly matched."
  },
  {
   "id": "awards-honours-00119",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Kalinga Prize - Third highest military decoration of India",
    "Kalinga Prize - British award for fiction",
    "Kalinga Prize - UNESCO award for popularisation of science",
    "Kalinga Prize - Highest civilian award of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Kalinga Prize - UNESCO award for popularisation of science is correctly matched."
  },
  {
   "id": "awards-honours-00120",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Kirti Chakra - Second highest peacetime gallantry award of India",
    "Kirti Chakra - Performing arts award of India",
    "Kirti Chakra - Indian literary award",
    "Kirti Chakra - Second highest civilian award of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Kirti Chakra - Second highest peacetime gallantry award of India is correctly matched."
  },
  {
   "id": "awards-honours-00121",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Kirti Chakra - Award for brave children in India",
    "Kirti Chakra - Highest military decoration of India",
    "Kirti Chakra - Asian award for public service",
    "Kirti Chakra - Second highest peacetime gallantry award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Kirti Chakra - Second highest peacetime gallantry award of India is correctly matched."
  },
  {
   "id": "awards-honours-00122",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Right Livelihood Award - Alternative Nobel Prize",
    "Right Livelihood Award - American award for music",
    "Right Livelihood Award - Fourth highest civilian award of India",
    "Right Livelihood Award - Asian award for public service"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Right Livelihood Award - Alternative Nobel Prize is correctly matched."
  },
  {
   "id": "awards-honours-00123",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Right Livelihood Award - Highest literary award of India",
    "Right Livelihood Award - Alternative Nobel Prize",
    "Right Livelihood Award - Third highest peacetime gallantry award of India",
    "Right Livelihood Award - Indian award in science and technology"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Right Livelihood Award - Alternative Nobel Prize is correctly matched."
  },
  {
   "id": "awards-honours-00124",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Ramon Magsaysay Award - Asian award for public service",
    "Ramon Magsaysay Award - Awards for Indian cinema",
    "Ramon Magsaysay Award - Award for progress in spiritual matters",
    "Ramon Magsaysay Award - Indian award for social work and peace"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Ramon Magsaysay Award - Asian award for public service is correctly matched."
  },
  {
   "id": "awards-honours-00125",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Ramon Magsaysay Award - Indian award for social work and peace",
    "Ramon Magsaysay Award - Asian award for public service",
    "Ramon Magsaysay Award - Highest peacetime gallantry award of India",
    "Ramon Magsaysay Award - Highest sporting honour of India"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Ramon Magsaysay Award - Asian award for public service is correctly matched."
  },
  {
   "id": "awards-honours-00126",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Shanti Swarup Bhatnagar Prize - Indian literary award",
    "Shanti Swarup Bhatnagar Prize - Alternative Nobel Prize",
    "Shanti Swarup Bhatnagar Prize - Indian award in science and technology",
    "Shanti Swarup Bhatnagar Prize - Highest military decoration of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Shanti Swarup Bhatnagar Prize - Indian award in science and technology is correctly matched."
  },
  {
   "id": "awards-honours-00127",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Shanti Swarup Bhatnagar Prize - Third highest peacetime gallantry award of India",
    "Shanti Swarup Bhatnagar Prize - Outstanding performance in Indian sports",
    "Shanti Swarup Bhatnagar Prize - Indian award in science and technology",
    "Shanti Swarup Bhatnagar Prize - Indian award in agricultural science"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Shanti Swarup Bhatnagar Prize - Indian award in science and technology is correctly matched."
  },
  {
   "id": "awards-honours-00128",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Grammy Award - Award for progress in spiritual matters",
    "Grammy Award - American award for music",
    "Grammy Award - Awards for Indian cinema",
    "Grammy Award - Award for brave children in India"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Grammy Award - American award for music is correctly matched."
  },
  {
   "id": "awards-honours-00129",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Grammy Award - Third highest military decoration of India",
    "Grammy Award - Third highest civilian award of India",
    "Grammy Award - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics",
    "Grammy Award - American award for music"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Grammy Award - American award for music is correctly matched."
  },
  {
   "id": "awards-honours-00130",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Major Dhyan Chand Khel Ratna Award - Indian award in science and technology",
    "Major Dhyan Chand Khel Ratna Award - British award for fiction",
    "Major Dhyan Chand Khel Ratna Award - Highest sporting honour of India",
    "Major Dhyan Chand Khel Ratna Award - Outstanding performance in Indian sports"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Major Dhyan Chand Khel Ratna Award - Highest sporting honour of India is correctly matched."
  },
  {
   "id": "awards-honours-00131",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Major Dhyan Chand Khel Ratna Award - Highest sporting honour of India",
    "Major Dhyan Chand Khel Ratna Award - UNESCO award for popularisation of science",
    "Major Dhyan Chand Khel Ratna Award - Outstanding performance in Indian sports",
    "Major Dhyan Chand Khel Ratna Award - Awards for Indian cinema"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Major Dhyan Chand Khel Ratna Award - Highest sporting honour of India is correctly matched."
  },
  {
   "id": "awards-honours-00132",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Bharat Ratna - Indian award for research",
    "Bharat Ratna - Highest civilian award of India",
    "Bharat Ratna - Second highest peacetime gallantry award of India",
    "Bharat Ratna - Outstanding performance in Indian sports"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Bharat Ratna - Highest civilian award of India is correctly matched."
  },
  {
   "id": "awards-honours-00133",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Bharat Ratna - Outstanding performance in Indian sports",
    "Bharat Ratna - Highest civilian award of India",
    "Bharat Ratna - Indian award for social work and peace",
    "Bharat Ratna - Coaching excellence in Indian sports"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Bharat Ratna - Highest civilian award of India is correctly matched."
  },
  {
   "id": "awards-honours-00134",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Shaurya Chakra - Performing arts award of India",
    "Shaurya Chakra - American award for films",
    "Shaurya Chakra - Indian award for social work and peace",
    "Shaurya Chakra - Third highest peacetime gallantry award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Shaurya Chakra - Third highest peacetime gallantry award of India is correctly matched."
  },
  {
   "id": "awards-honours-00135",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Shaurya Chakra - Highest peacetime gallantry award of India",
    "Shaurya Chakra - Second highest peacetime gallantry award of India",
    "Shaurya Chakra - Lifetime achievement in Indian sports",
    "Shaurya Chakra - Third highest peacetime gallantry award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Shaurya Chakra - Third highest peacetime gallantry award of India is correctly matched."
  },
  {
   "id": "awards-honours-00136",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Ashoka Chakra - Award for brave children in India",
    "Ashoka Chakra - Highest sporting honour of India",
    "Ashoka Chakra - Fourth highest civilian award of India",
    "Ashoka Chakra - Highest peacetime gallantry award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Ashoka Chakra - Highest peacetime gallantry award of India is correctly matched."
  },
  {
   "id": "awards-honours-00137",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Ashoka Chakra - American award for films",
    "Ashoka Chakra - Highest peacetime gallantry award of India",
    "Ashoka Chakra - Third highest peacetime gallantry award of India",
    "Ashoka Chakra - Outstanding performance in Indian sports"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Ashoka Chakra - Highest peacetime gallantry award of India is correctly matched."
  },
  {
   "id": "awards-honours-00138",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Sangeet Natak Akademi Award - Awards for Indian cinema",
    "Sangeet Natak Akademi Award - Performing arts award of India",
    "Sangeet Natak Akademi Award - Indian award in agricultural science",
    "Sangeet Natak Akademi Award - Coaching excellence in Indian sports"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Sangeet Natak Akademi Award - Performing arts award of India is correctly matched."
  },
  {
   "id": "awards-honours-00139",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Sangeet Natak Akademi Award - Highest sporting honour of India",
    "Sangeet Natak Akademi Award - Highest military decoration of India",
    "Sangeet Natak Akademi Award - Performing arts award of India",
    "Sangeet Natak Akademi Award - Indian award for social work and peace"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Sangeet Natak Akademi Award - Performing arts award of India is correctly matched."
  },
  {
   "id": "awards-honours-00140",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Saraswati Samman - British award for fiction",
    "Saraswati Samman - Indian award for social work and peace",
    "Saraswati Samman - Second highest military decoration of India",
    "Saraswati Samman - Indian literary award"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Saraswati Samman - Indian literary award is correctly matched."
  },
  {
   "id": "awards-honours-00141",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Saraswati Samman - Indian literary award",
    "Saraswati Samman - Indian award in science and technology",
    "Saraswati Samman - Coaching excellence in Indian sports",
    "Saraswati Samman - Asian award for public service"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Saraswati Samman - Indian literary award is correctly matched."
  },
  {
   "id": "awards-honours-00142",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "National Bravery Award - Award for brave children in India",
    "National Bravery Award - Highest award in Indian cinema",
    "National Bravery Award - Highest civilian award of India",
    "National Bravery Award - Indian award for peace, disarmament and development"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only National Bravery Award - Award for brave children in India is correctly matched."
  },
  {
   "id": "awards-honours-00143",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "National Bravery Award - Third highest military decoration of India",
    "National Bravery Award - Award for brave children in India",
    "National Bravery Award - American award for journalism and letters",
    "National Bravery Award - Indian award in agricultural science"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only National Bravery Award - Award for brave children in India is correctly matched."
  },
  {
   "id": "awards-honours-00144",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Gandhi Peace Prize - British award for fiction",
    "Gandhi Peace Prize - Indian award for social work and peace",
    "Gandhi Peace Prize - Indian literary award",
    "Gandhi Peace Prize - American award for music"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Gandhi Peace Prize - Indian award for social work and peace is correctly matched."
  },
  {
   "id": "awards-honours-00145",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Gandhi Peace Prize - Award for progress in spiritual matters",
    "Gandhi Peace Prize - Coaching excellence in Indian sports",
    "Gandhi Peace Prize - Indian award for social work and peace",
    "Gandhi Peace Prize - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Gandhi Peace Prize - Indian award for social work and peace is correctly matched."
  },
  {
   "id": "awards-honours-00146",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Padma Vibhushan - Alternative Nobel Prize",
    "Padma Vibhushan - Second highest civilian award of India",
    "Padma Vibhushan - American award for journalism and letters",
    "Padma Vibhushan - Third highest military decoration of India"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Padma Vibhushan - Second highest civilian award of India is correctly matched."
  },
  {
   "id": "awards-honours-00147",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Padma Vibhushan - Highest literary award of India",
    "Padma Vibhushan - Indian literary award",
    "Padma Vibhushan - Alternative Nobel Prize",
    "Padma Vibhushan - Second highest civilian award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Padma Vibhushan - Second highest civilian award of India is correctly matched."
  },
  {
   "id": "awards-honours-00148",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Infosys Prize - Lifetime achievement in Indian sports",
    "Infosys Prize - Award for brave children in India",
    "Infosys Prize - Indian award for social work and peace",
    "Infosys Prize - Indian award for research"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Infosys Prize - Indian award for research is correctly matched."
  },
  {
   "id": "awards-honours-00149",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Infosys Prize - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics",
    "Infosys Prize - Indian literary award",
    "Infosys Prize - Indian award for research",
    "Infosys Prize - Asian award for public service"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Infosys Prize - Indian award for research is correctly matched."
  },
  {
   "id": "awards-honours-00150",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Arjuna Award - American award for journalism and letters",
    "Arjuna Award - Third highest civilian award of India",
    "Arjuna Award - Outstanding performance in Indian sports",
    "Arjuna Award - American award for music"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Arjuna Award - Outstanding performance in Indian sports is correctly matched."
  },
  {
   "id": "awards-honours-00151",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Arjuna Award - Outstanding performance in Indian sports",
    "Arjuna Award - Award for brave children in India",
    "Arjuna Award - Indian award for social work and peace",
    "Arjuna Award - Lifetime achievement in Indian sports"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Arjuna Award - Outstanding performance in Indian sports is correctly matched."
  },
  {
   "id": "awards-honours-00152",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Maha Vir Chakra - Coaching excellence in Indian sports",
    "Maha Vir Chakra - Indian award in science and technology",
    "Maha Vir Chakra - Highest military decoration of India",
    "Maha Vir Chakra - Second highest military decoration of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Maha Vir Chakra - Second highest military decoration of India is correctly matched."
  },
  {
   "id": "awards-honours-00153",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Maha Vir Chakra - Second highest military decoration of India",
    "Maha Vir Chakra - Third highest military decoration of India",
    "Maha Vir Chakra - Asian award for public service",
    "Maha Vir Chakra - Highest military decoration of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Maha Vir Chakra - Second highest military decoration of India is correctly matched."
  },
  {
   "id": "awards-honours-00154",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Sahitya Akademi Award - American award for music",
    "Sahitya Akademi Award - Outstanding performance in Indian sports",
    "Sahitya Akademi Award - Literary award for Indian languages",
    "Sahitya Akademi Award - American award for films"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Sahitya Akademi Award - Literary award for Indian languages is correctly matched."
  },
  {
   "id": "awards-honours-00155",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Sahitya Akademi Award - Literary award for Indian languages",
    "Sahitya Akademi Award - Second highest civilian award of India",
    "Sahitya Akademi Award - British award for fiction",
    "Sahitya Akademi Award - Lifetime achievement in Indian sports"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Sahitya Akademi Award - Literary award for Indian languages is correctly matched."
  },
  {
   "id": "awards-honours-00156",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Padma Bhushan - Coaching excellence in Indian sports",
    "Padma Bhushan - Third highest civilian award of India",
    "Padma Bhushan - Indian award for research",
    "Padma Bhushan - Lifetime achievement in Indian sports"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Padma Bhushan - Third highest civilian award of India is correctly matched."
  },
  {
   "id": "awards-honours-00157",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Padma Bhushan - Awards for Indian cinema",
    "Padma Bhushan - UNESCO award for popularisation of science",
    "Padma Bhushan - Highest military decoration of India",
    "Padma Bhushan - Third highest civilian award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Padma Bhushan - Third highest civilian award of India is correctly matched."
  },
  {
   "id": "awards-honours-00158",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Pulitzer Prize - American award for journalism and letters",
    "Pulitzer Prize - Alternative Nobel Prize",
    "Pulitzer Prize - Indian award in science and technology",
    "Pulitzer Prize - Highest award in Indian cinema"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Pulitzer Prize - American award for journalism and letters is correctly matched."
  },
  {
   "id": "awards-honours-00159",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Pulitzer Prize - American award for journalism and letters",
    "Pulitzer Prize - Indian literary award",
    "Pulitzer Prize - Third highest civilian award of India",
    "Pulitzer Prize - Highest peacetime gallantry award of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Pulitzer Prize - American award for journalism and letters is correctly matched."
  },
  {
   "id": "awards-honours-00160",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Dada Saheb Phalke Award - Highest award in Indian cinema",
    "Dada Saheb Phalke Award - Highest sporting honour of India",
    "Dada Saheb Phalke Award - Alternative Nobel Prize",
    "Dada Saheb Phalke Award - Award for brave children in India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Dada Saheb Phalke Award - Highest award in Indian cinema is correctly matched."
  },
  {
   "id": "awards-honours-00161",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Dada Saheb Phalke Award - Award for brave children in India",
    "Dada Saheb Phalke Award - Performing arts award of India",
    "Dada Saheb Phalke Award - Highest peacetime gallantry award of India",
    "Dada Saheb Phalke Award - Highest award in Indian cinema"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Dada Saheb Phalke Award - Highest award in Indian cinema is correctly matched."
  },
  {
   "id": "awards-honours-00162",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Dronacharya Award - Second highest civilian award of India",
    "Dronacharya Award - American award for journalism and letters",
    "Dronacharya Award - American award for music",
    "Dronacharya Award - Coaching excellence in Indian sports"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Dronacharya Award - Coaching excellence in Indian sports is correctly matched."
  },
  {
   "id": "awards-honours-00163",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "Dronacharya Award - Indian award for social work and peace",
    "Dronacharya Award - American award for journalism and letters",
    "Dronacharya Award - Coaching excellence in Indian sports",
    "Dronacharya Award - British award for fiction"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only Dronacharya Award - Coaching excellence in Indian sports is correctly matched."
  },
  {
   "id": "awards-honours-00164",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "National Film Award - American award for music",
    "National Film Award - Second highest peacetime gallantry award of India",
    "National Film Award - Awards for Indian cinema",
    "National Film Award - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only National Film Award - Awards for Indian cinema is correctly matched."
  },
  {
   "id": "awards-honours-00165",
   "q": "Which of the following pairs of award and field is correctly matched?",
   "o": [
    "National Film Award - Highest peacetime gallantry award of India",
    "National Film Award - Third highest civilian award of India",
    "National Film Award - Second highest peacetime gallantry award of India",
    "National Film Award - Awards for Indian cinema"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "Only National Film Award - Awards for Indian cinema is correctly matched."
  },
  {
   "id": "awards-honours-00166",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Ramon Magsaysay Award - Asian award for public service",
    "Maha Vir Chakra - Performing arts award of India",
    "Sangeet Natak Akademi Award - Performing arts award of India",
    "Sahitya Akademi Award - Literary award for Indian languages"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Maha Vir Chakra - Performing arts award of India is not correctly matched."
  },
  {
   "id": "awards-honours-00167",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Bharat Ratna - Highest civilian award of India",
    "Vyas Samman - Indian literary award",
    "Borlaug Award - Third highest civilian award of India",
    "Booker Prize - British award for fiction"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Borlaug Award - Third highest civilian award of India is not correctly matched."
  },
  {
   "id": "awards-honours-00168",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Dada Saheb Phalke Award - Second highest civilian award of India",
    "Gandhi Peace Prize - Indian award for social work and peace",
    "Kalinga Prize - UNESCO award for popularisation of science",
    "Grammy Award - American award for music"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Dada Saheb Phalke Award - Second highest civilian award of India is not correctly matched."
  },
  {
   "id": "awards-honours-00169",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Dronacharya Award - Indian literary award",
    "Bharat Ratna - Highest civilian award of India",
    "Padma Shri - Fourth highest civilian award of India",
    "Booker Prize - British award for fiction"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Dronacharya Award - Indian literary award is not correctly matched."
  },
  {
   "id": "awards-honours-00170",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Sahitya Akademi Award - Literary award for Indian languages",
    "Kirti Chakra - Second highest peacetime gallantry award of India",
    "Sangeet Natak Akademi Award - Indian literary award",
    "Infosys Prize - Indian award for research"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Sangeet Natak Akademi Award - Indian literary award is not correctly matched."
  },
  {
   "id": "awards-honours-00171",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Padma Bhushan - Third highest civilian award of India",
    "Jnanpith Award - Indian literary award",
    "National Bravery Award - Award for brave children in India",
    "Gandhi Peace Prize - Indian award for social work and peace"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Jnanpith Award - Indian literary award is not correctly matched."
  },
  {
   "id": "awards-honours-00172",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Bharat Ratna - Highest civilian award of India",
    "Gandhi Peace Prize - Lifetime achievement in Indian sports",
    "Padma Shri - Fourth highest civilian award of India",
    "Shaurya Chakra - Third highest peacetime gallantry award of India"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Gandhi Peace Prize - Lifetime achievement in Indian sports is not correctly matched."
  },
  {
   "id": "awards-honours-00173",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Shaurya Chakra - Indian literary award",
    "Academy Award (Oscar) - American award for films",
    "Templeton Prize - Award for progress in spiritual matters",
    "Padma Vibhushan - Second highest civilian award of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Shaurya Chakra - Indian literary award is not correctly matched."
  },
  {
   "id": "awards-honours-00174",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Booker Prize - Indian award for research",
    "Sangeet Natak Akademi Award - Performing arts award of India",
    "Padma Shri - Fourth highest civilian award of India",
    "Vir Chakra - Third highest military decoration of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Booker Prize - Indian award for research is not correctly matched."
  },
  {
   "id": "awards-honours-00175",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Maha Vir Chakra - Second highest military decoration of India",
    "Sangeet Natak Akademi Award - Performing arts award of India",
    "Shaurya Chakra - Third highest peacetime gallantry award of India",
    "Param Vir Chakra - American award for films"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Param Vir Chakra - American award for films is not correctly matched."
  },
  {
   "id": "awards-honours-00176",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Kirti Chakra - Second highest peacetime gallantry award of India",
    "Vir Chakra - Indian literary award",
    "National Film Award - Awards for Indian cinema",
    "National Bravery Award - Award for brave children in India"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Vir Chakra - Indian literary award is not correctly matched."
  },
  {
   "id": "awards-honours-00177",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Vyas Samman - Indian literary award",
    "Templeton Prize - Award for progress in spiritual matters",
    "Nobel Prize - Highest award in Indian cinema",
    "Dhyan Chand Award - Lifetime achievement in Indian sports"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Nobel Prize - Highest award in Indian cinema is not correctly matched."
  },
  {
   "id": "awards-honours-00178",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Sangeet Natak Akademi Award - Performing arts award of India",
    "Indira Gandhi Prize - Alternative Nobel Prize",
    "Maha Vir Chakra - Second highest military decoration of India",
    "Shanti Swarup Bhatnagar Prize - Indian award in science and technology"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Indira Gandhi Prize - Alternative Nobel Prize is not correctly matched."
  },
  {
   "id": "awards-honours-00179",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Sangeet Natak Akademi Award - Performing arts award of India",
    "Padma Vibhushan - Highest award in Indian cinema",
    "Nobel Prize - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics",
    "Padma Bhushan - Third highest civilian award of India"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Padma Vibhushan - Highest award in Indian cinema is not correctly matched."
  },
  {
   "id": "awards-honours-00180",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Param Vir Chakra - Highest military decoration of India",
    "Ramon Magsaysay Award - Second highest military decoration of India",
    "Padma Bhushan - Third highest civilian award of India",
    "Shanti Swarup Bhatnagar Prize - Indian award in science and technology"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Ramon Magsaysay Award - Second highest military decoration of India is not correctly matched."
  },
  {
   "id": "awards-honours-00181",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Sahitya Akademi Award - Literary award for Indian languages",
    "Booker Prize - British award for fiction",
    "Pulitzer Prize - American award for journalism and letters",
    "Templeton Prize - Alternative Nobel Prize"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Templeton Prize - Alternative Nobel Prize is not correctly matched."
  },
  {
   "id": "awards-honours-00182",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Jnanpith Award - Highest literary award of India",
    "Shaurya Chakra - Third highest peacetime gallantry award of India",
    "Pulitzer Prize - Second highest peacetime gallantry award of India",
    "Arjuna Award - Outstanding performance in Indian sports"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Pulitzer Prize - Second highest peacetime gallantry award of India is not correctly matched."
  },
  {
   "id": "awards-honours-00183",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Vir Chakra - Third highest military decoration of India",
    "Padma Shri - Fourth highest civilian award of India",
    "Bharat Ratna - Awards for Indian cinema",
    "Dronacharya Award - Coaching excellence in Indian sports"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Bharat Ratna - Awards for Indian cinema is not correctly matched."
  },
  {
   "id": "awards-honours-00184",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Infosys Prize - Indian award for research",
    "Sangeet Natak Akademi Award - Performing arts award of India",
    "Kirti Chakra - American award for journalism and letters",
    "Maha Vir Chakra - Second highest military decoration of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Kirti Chakra - American award for journalism and letters is not correctly matched."
  },
  {
   "id": "awards-honours-00185",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Padma Vibhushan - Second highest civilian award of India",
    "Grammy Award - Performing arts award of India",
    "Nobel Prize - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics",
    "Kalinga Prize - UNESCO award for popularisation of science"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Grammy Award - Performing arts award of India is not correctly matched."
  },
  {
   "id": "awards-honours-00186",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Saraswati Samman - Indian literary award",
    "Kalinga Prize - UNESCO award for popularisation of science",
    "National Film Award - Awards for Indian cinema",
    "Vyas Samman - Second highest peacetime gallantry award of India"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Vyas Samman - Second highest peacetime gallantry award of India is not correctly matched."
  },
  {
   "id": "awards-honours-00187",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Borlaug Award - Indian award in agricultural science",
    "Gandhi Peace Prize - Indian award for social work and peace",
    "Infosys Prize - Indian award for research",
    "Major Dhyan Chand Khel Ratna Award - Literary award for Indian languages"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Major Dhyan Chand Khel Ratna Award - Literary award for Indian languages is not correctly matched."
  },
  {
   "id": "awards-honours-00188",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Borlaug Award - Indian award in agricultural science",
    "Infosys Prize - American award for music",
    "Vyas Samman - Indian literary award",
    "Kalinga Prize - UNESCO award for popularisation of science"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Infosys Prize - American award for music is not correctly matched."
  },
  {
   "id": "awards-honours-00189",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Grammy Award - American award for music",
    "Gandhi Peace Prize - Indian award for social work and peace",
    "Shanti Swarup Bhatnagar Prize - Third highest peacetime gallantry award of India",
    "Padma Shri - Fourth highest civilian award of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Shanti Swarup Bhatnagar Prize - Third highest peacetime gallantry award of India is not correctly matched."
  },
  {
   "id": "awards-honours-00190",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Nobel Prize - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics",
    "Right Livelihood Award - Indian award for peace, disarmament and development",
    "Sangeet Natak Akademi Award - Performing arts award of India",
    "Major Dhyan Chand Khel Ratna Award - Highest sporting honour of India"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Right Livelihood Award - Indian award for peace, disarmament and development is not correctly matched."
  },
  {
   "id": "awards-honours-00191",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Shanti Swarup Bhatnagar Prize - Indian award in science and technology",
    "Saraswati Samman - Coaching excellence in Indian sports",
    "Infosys Prize - Indian award for research",
    "Pulitzer Prize - American award for journalism and letters"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Saraswati Samman - Coaching excellence in Indian sports is not correctly matched."
  },
  {
   "id": "awards-honours-00192",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Dhyan Chand Award - Indian literary award",
    "Grammy Award - American award for music",
    "Vir Chakra - Third highest military decoration of India",
    "Right Livelihood Award - Alternative Nobel Prize"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Dhyan Chand Award - Indian literary award is not correctly matched."
  },
  {
   "id": "awards-honours-00193",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Vir Chakra - Third highest military decoration of India",
    "Kalinga Prize - Third highest civilian award of India",
    "Shanti Swarup Bhatnagar Prize - Indian award in science and technology",
    "Dhyan Chand Award - Lifetime achievement in Indian sports"
   ],
   "a": 1,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Kalinga Prize - Third highest civilian award of India is not correctly matched."
  },
  {
   "id": "awards-honours-00194",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "National Film Award - Awards for Indian cinema",
    "Grammy Award - American award for music",
    "Kalinga Prize - UNESCO award for popularisation of science",
    "Padma Shri - Indian award for social work and peace"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Padma Shri - Indian award for social work and peace is not correctly matched."
  },
  {
   "id": "awards-honours-00195",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Grammy Award - American award for music",
    "Sangeet Natak Akademi Award - Performing arts award of India",
    "Padma Shri - Fourth highest civilian award of India",
    "Padma Bhushan - Award for progress in spiritual matters"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Padma Bhushan - Award for progress in spiritual matters is not correctly matched."
  },
  {
   "id": "awards-honours-00196",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Templeton Prize - Award for progress in spiritual matters",
    "National Bravery Award - Award for brave children in India",
    "Shanti Swarup Bhatnagar Prize - Indian award in science and technology",
    "National Film Award - American award for music"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair National Film Award - American award for music is not correctly matched."
  },
  {
   "id": "awards-honours-00197",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "National Film Award - Awards for Indian cinema",
    "National Bravery Award - Award for brave children in India",
    "Bharat Ratna - Highest civilian award of India",
    "Academy Award (Oscar) - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Academy Award (Oscar) - International award for Physics, Chemistry, Medicine, Literature, Peace and Economics is not correctly matched."
  },
  {
   "id": "awards-honours-00198",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Arjuna Award - Asian award for public service",
    "Vyas Samman - Indian literary award",
    "Padma Bhushan - Third highest civilian award of India",
    "Padma Shri - Fourth highest civilian award of India"
   ],
   "a": 0,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Arjuna Award - Asian award for public service is not correctly matched."
  },
  {
   "id": "awards-honours-00199",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Templeton Prize - Award for progress in spiritual matters",
    "Right Livelihood Award - Alternative Nobel Prize",
    "Param Vir Chakra - Highest military decoration of India",
    "Sahitya Akademi Award - Indian award for research"
   ],
   "a": 3,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Sahitya Akademi Award - Indian award for research is not correctly matched."
  },
  {
   "id": "awards-honours-00200",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Gandhi Peace Prize - Indian award for social work and peace",
    "Dada Saheb Phalke Award - Highest award in Indian cinema",
    "Ashoka Chakra - Highest civilian award of India",
    "Major Dhyan Chand Khel Ratna Award - Highest sporting honour of India"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair Ashoka Chakra - Highest civilian award of India is not correctly matched."
  },
  {
   "id": "awards-honours-00201",
   "q": "Which of the following pairs of award and field is NOT correctly matched?",
   "o": [
    "Infosys Prize - Indian award for research",
    "Shanti Swarup Bhatnagar Prize - Indian award in science and technology",
    "National Bravery Award - American award for films",
    "Sahitya Akademi Award - Literary award for Indian languages"
   ],
   "a": 2,
   "t": "Awards and Honours",
   "l": 3,
   "s": "generated",
   "e": "The pair National Bravery Award - American award for films is not correctly matched."
  }
 ]
};
  if (typeof module !== "undefined" && module.exports) module.exports = data;
  if (typeof window !== "undefined") {
    window.QBANK_CATEGORIES = window.QBANK_CATEGORIES || {};
    window.QBANK_CATEGORIES[data.slug] = data;
  }
})();
