"use strict";
/* Generated by tools/build-qbank.js — do not edit by hand. */
(function () {
  var data = {
 "slug": "physics",
 "name": "Physics",
 "icon": "magnet",
 "group": "Science",
 "exams": [
  "ssc-cgl",
  "railways"
 ],
 "blurb": "Motion, energy, light, electricity and units.",
 "count": 260,
 "questions": [
  {
   "id": "physics-00001",
   "q": "What is the SI unit of force?",
   "o": [
    "Joule",
    "Newton",
    "Watt",
    "Pascal"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Force is measured in newtons."
  },
  {
   "id": "physics-00002",
   "q": "The speed of light in vacuum is approximately:",
   "o": [
    "3 x 10^6 m/s",
    "3 x 10^8 m/s",
    "3 x 10^10 m/s",
    "3 x 10^5 m/s"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Light travels at about 3 x 10^8 metres per second in vacuum."
  },
  {
   "id": "physics-00003",
   "q": "Which law states that every action has an equal and opposite reaction?",
   "o": [
    "Newton's first law",
    "Newton's second law",
    "Newton's third law",
    "Law of gravitation"
   ],
   "a": 2,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Newton's third law of motion states this principle."
  },
  {
   "id": "physics-00004",
   "q": "The SI unit of power is:",
   "o": [
    "Newton",
    "Watt",
    "Joule",
    "Ampere"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Power is measured in watts."
  },
  {
   "id": "physics-00005",
   "q": "Which instrument is used to measure electric current?",
   "o": [
    "Voltmeter",
    "Ammeter",
    "Barometer",
    "Thermometer"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "An ammeter measures current in amperes."
  },
  {
   "id": "physics-00006",
   "q": "What is the unit of electrical resistance?",
   "o": [
    "Ohm",
    "Volt",
    "Ampere",
    "Coulomb"
   ],
   "a": 0,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Resistance is measured in ohms."
  },
  {
   "id": "physics-00007",
   "q": "Which mirror is used as a rear-view mirror in vehicles?",
   "o": [
    "Concave mirror",
    "Convex mirror",
    "Plane mirror",
    "Cylindrical mirror"
   ],
   "a": 1,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "Convex mirrors give a wider field of view."
  },
  {
   "id": "physics-00008",
   "q": "The phenomenon of splitting white light into its components is called:",
   "o": [
    "Reflection",
    "Refraction",
    "Dispersion",
    "Diffraction"
   ],
   "a": 2,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "Dispersion separates white light into its constituent colours."
  },
  {
   "id": "physics-00009",
   "q": "Which lens is used to correct short-sightedness?",
   "o": [
    "Convex lens",
    "Concave lens",
    "Cylindrical lens",
    "Bifocal lens"
   ],
   "a": 1,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "Myopia is corrected using a concave lens."
  },
  {
   "id": "physics-00010",
   "q": "What is the value of acceleration due to gravity on Earth?",
   "o": [
    "8.9 m/s^2",
    "9.8 m/s^2",
    "10.8 m/s^2",
    "7.8 m/s^2"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "The standard value is about 9.8 metres per second squared."
  },
  {
   "id": "physics-00011",
   "q": "Which is a good conductor of electricity?",
   "o": [
    "Rubber",
    "Copper",
    "Wood",
    "Plastic"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Copper is a metal with free electrons and conducts well."
  },
  {
   "id": "physics-00012",
   "q": "The energy possessed by a body by virtue of its motion is called:",
   "o": [
    "Potential energy",
    "Kinetic energy",
    "Thermal energy",
    "Chemical energy"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Energy of motion is kinetic energy."
  },
  {
   "id": "physics-00013",
   "q": "Which device converts mechanical energy into electrical energy?",
   "o": [
    "Motor",
    "Generator",
    "Transformer",
    "Battery"
   ],
   "a": 1,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "A generator converts mechanical energy into electrical energy."
  },
  {
   "id": "physics-00014",
   "q": "Which principle explains the working of a rocket?",
   "o": [
    "Conservation of energy",
    "Conservation of momentum",
    "Conservation of mass",
    "Pascal's law"
   ],
   "a": 1,
   "t": "Curated",
   "l": 3,
   "s": "curated",
   "e": "Rockets work on the conservation of linear momentum."
  },
  {
   "id": "physics-00015",
   "q": "Sound cannot travel through:",
   "o": [
    "Air",
    "Water",
    "Steel",
    "Vacuum"
   ],
   "a": 3,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Sound needs a medium and cannot travel through a vacuum."
  },
  {
   "id": "physics-00016",
   "q": "Which is the unit of frequency?",
   "o": [
    "Hertz",
    "Decibel",
    "Newton",
    "Joule"
   ],
   "a": 0,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Frequency is measured in hertz."
  },
  {
   "id": "physics-00017",
   "q": "What is the boiling point of water at normal atmospheric pressure?",
   "o": [
    "90 degrees Celsius",
    "100 degrees Celsius",
    "110 degrees Celsius",
    "80 degrees Celsius"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "Water boils at 100 degrees Celsius at sea level."
  },
  {
   "id": "physics-00018",
   "q": "Which law relates the pressure and volume of a gas at constant temperature?",
   "o": [
    "Charles's law",
    "Boyle's law",
    "Dalton's law",
    "Avogadro's law"
   ],
   "a": 1,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "Boyle's law states that pressure varies inversely with volume at constant temperature."
  },
  {
   "id": "physics-00019",
   "q": "The unit of magnetic flux density is:",
   "o": [
    "Weber",
    "Tesla",
    "Henry",
    "Farad"
   ],
   "a": 1,
   "t": "Curated",
   "l": 3,
   "s": "curated",
   "e": "Magnetic flux density is measured in tesla."
  },
  {
   "id": "physics-00020",
   "q": "Which radiation has the shortest wavelength?",
   "o": [
    "Infrared",
    "Visible light",
    "Ultraviolet",
    "Gamma rays"
   ],
   "a": 3,
   "t": "Curated",
   "l": 2,
   "s": "curated",
   "e": "Gamma rays have the shortest wavelength in the electromagnetic spectrum."
  },
  {
   "id": "physics-00021",
   "q": "A body weighs least at the:",
   "o": [
    "Poles",
    "Equator",
    "Mountains",
    "Sea level"
   ],
   "a": 1,
   "t": "Curated",
   "l": 3,
   "s": "curated",
   "e": "Gravity and apparent weight are lowest at the equator due to the Earth's shape and rotation."
  },
  {
   "id": "physics-00022",
   "q": "Which instrument measures atmospheric pressure?",
   "o": [
    "Hygrometer",
    "Barometer",
    "Anemometer",
    "Altimeter"
   ],
   "a": 1,
   "t": "Curated",
   "l": 1,
   "s": "curated",
   "e": "A barometer measures atmospheric pressure."
  },
  {
   "id": "physics-00023",
   "q": "What is the SI unit of Capacitance?",
   "o": [
    "Coulomb",
    "Newton",
    "Mole",
    "Farad"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Capacitance is the Farad."
  },
  {
   "id": "physics-00024",
   "q": "Which instrument is used to measure Time accurately?",
   "o": [
    "Chronometer",
    "Electrocardiogram machine",
    "Speedometer",
    "Anemometer"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Chronometer is used to measure Time accurately."
  },
  {
   "id": "physics-00025",
   "q": "What is the SI unit of Power?",
   "o": [
    "Lumen",
    "Watt",
    "Metre",
    "Ohm"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Power is the Watt."
  },
  {
   "id": "physics-00026",
   "q": "Which instrument is used to measure Earthquakes?",
   "o": [
    "Anemometer",
    "Odometer",
    "Spectrometer",
    "Seismograph"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Seismograph is used to measure Earthquakes."
  },
  {
   "id": "physics-00027",
   "q": "What is the SI unit of Luminous flux?",
   "o": [
    "Coulomb",
    "Lumen",
    "Volt",
    "Joule"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Luminous flux is the Lumen."
  },
  {
   "id": "physics-00028",
   "q": "Which instrument is used to measure Internal body organs?",
   "o": [
    "Fathometer",
    "Spherometer",
    "Periscope",
    "Endoscope"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Endoscope is used to measure Internal body organs."
  },
  {
   "id": "physics-00029",
   "q": "What is the SI unit of Electrical resistance?",
   "o": [
    "Ohm",
    "Kilogram",
    "Lumen",
    "Pascal"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Electrical resistance is the Ohm."
  },
  {
   "id": "physics-00030",
   "q": "Which instrument is used to measure Turbidity of liquid?",
   "o": [
    "Pyrometer",
    "Periscope",
    "Sphygmomanometer",
    "Nephelometer"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Nephelometer is used to measure Turbidity of liquid."
  },
  {
   "id": "physics-00031",
   "q": "What is the SI unit of Inductance?",
   "o": [
    "Farad",
    "Henry",
    "Joule",
    "Joule per Kelvin"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Inductance is the Henry."
  },
  {
   "id": "physics-00032",
   "q": "Which instrument is used to measure Magnified view of tiny objects?",
   "o": [
    "Lactometer",
    "Galvanometer",
    "Nephelometer",
    "Microscope"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Microscope is used to measure Magnified view of tiny objects."
  },
  {
   "id": "physics-00033",
   "q": "What is the SI unit of Temperature?",
   "o": [
    "Watt",
    "Kelvin",
    "Joule per Kelvin",
    "Ampere"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Temperature is the Kelvin."
  },
  {
   "id": "physics-00034",
   "q": "Which instrument is used to measure Radiant energy?",
   "o": [
    "Microscope",
    "Manometer",
    "Hygroscope",
    "Radiometer"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Radiometer is used to measure Radiant energy."
  },
  {
   "id": "physics-00035",
   "q": "What is the SI unit of Pressure?",
   "o": [
    "Becquerel",
    "Pascal",
    "Henry",
    "Ampere"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Pressure is the Pascal."
  },
  {
   "id": "physics-00036",
   "q": "Which instrument is used to measure Atmospheric pressure?",
   "o": [
    "Stethoscope",
    "Audiometer",
    "Transducer",
    "Barometer"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Barometer is used to measure Atmospheric pressure."
  },
  {
   "id": "physics-00037",
   "q": "What is the SI unit of Catalytic activity?",
   "o": [
    "Becquerel",
    "Newton",
    "Candela",
    "Katal"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Catalytic activity is the Katal."
  },
  {
   "id": "physics-00038",
   "q": "Which instrument is used to measure High temperature?",
   "o": [
    "Geiger counter",
    "Pyrometer",
    "Endoscope",
    "Fathometer"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Pyrometer is used to measure High temperature."
  },
  {
   "id": "physics-00039",
   "q": "What is the SI unit of Energy?",
   "o": [
    "Joule",
    "Becquerel",
    "Steradian",
    "Ohm"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Energy is the Joule."
  },
  {
   "id": "physics-00040",
   "q": "Which instrument is used to measure Multiple physiological responses?",
   "o": [
    "Polygraph",
    "Stethoscope",
    "Lactometer",
    "Voltmeter"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Polygraph is used to measure Multiple physiological responses."
  },
  {
   "id": "physics-00041",
   "q": "What is the SI unit of Length?",
   "o": [
    "Metre",
    "Watt",
    "Kilogram",
    "Becquerel"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Length is the Metre."
  },
  {
   "id": "physics-00042",
   "q": "Which instrument is used to measure Wind speed?",
   "o": [
    "Endoscope",
    "Anemometer",
    "Audiometer",
    "Telescope"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Anemometer is used to measure Wind speed."
  },
  {
   "id": "physics-00043",
   "q": "What is the SI unit of Radioactivity?",
   "o": [
    "Newton",
    "Henry",
    "Becquerel",
    "Volt"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Radioactivity is the Becquerel."
  },
  {
   "id": "physics-00044",
   "q": "Which instrument is used to measure Small electric currents?",
   "o": [
    "Seismograph",
    "Calorimeter",
    "Telescope",
    "Galvanometer"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Galvanometer is used to measure Small electric currents."
  },
  {
   "id": "physics-00045",
   "q": "What is the SI unit of Time?",
   "o": [
    "Joule per Kelvin",
    "Ampere",
    "Tesla",
    "Second"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Time is the Second."
  },
  {
   "id": "physics-00046",
   "q": "Which instrument is used to measure Purity of milk?",
   "o": [
    "Spherometer",
    "Ammeter",
    "Polygraph",
    "Lactometer"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Lactometer is used to measure Purity of milk."
  },
  {
   "id": "physics-00047",
   "q": "What is the SI unit of Electric charge?",
   "o": [
    "Coulomb",
    "Katal",
    "Mole",
    "Ampere"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Electric charge is the Coulomb."
  },
  {
   "id": "physics-00048",
   "q": "Which instrument is used to measure Objects above obstacles?",
   "o": [
    "Cardiograph",
    "Hygrometer",
    "Periscope",
    "Radiometer"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Periscope is used to measure Objects above obstacles."
  },
  {
   "id": "physics-00049",
   "q": "What is the SI unit of Amount of substance?",
   "o": [
    "Newton",
    "Mole",
    "Kilogram",
    "Steradian"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Amount of substance is the Mole."
  },
  {
   "id": "physics-00050",
   "q": "Which instrument is used to measure Heart activity?",
   "o": [
    "Hygroscope",
    "Viscometer",
    "Cardiograph",
    "Periscope"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Cardiograph is used to measure Heart activity."
  },
  {
   "id": "physics-00051",
   "q": "What is the SI unit of Plane angle?",
   "o": [
    "Henry",
    "Joule",
    "Hertz",
    "Radian"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Plane angle is the Radian."
  },
  {
   "id": "physics-00052",
   "q": "Which instrument is used to measure Distant objects?",
   "o": [
    "Telescope",
    "Radiometer",
    "Microscope",
    "Periscope"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Telescope is used to measure Distant objects."
  },
  {
   "id": "physics-00053",
   "q": "What is the SI unit of Electric current?",
   "o": [
    "Ampere",
    "Lux",
    "Joule per Kelvin",
    "Lumen"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Electric current is the Ampere."
  },
  {
   "id": "physics-00054",
   "q": "Which instrument is used to measure Blood pressure?",
   "o": [
    "Sphygmomanometer",
    "Barometer",
    "Potometer",
    "Spectrometer"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Sphygmomanometer is used to measure Blood pressure."
  },
  {
   "id": "physics-00055",
   "q": "What is the SI unit of Luminous intensity?",
   "o": [
    "Radian",
    "Kelvin",
    "Candela",
    "Gray"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Luminous intensity is the Candela."
  },
  {
   "id": "physics-00056",
   "q": "Which instrument is used to measure Speed of a vehicle?",
   "o": [
    "Calorimeter",
    "Kymograph",
    "Speedometer",
    "Tachometer"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Speedometer is used to measure Speed of a vehicle."
  },
  {
   "id": "physics-00057",
   "q": "What is the SI unit of Wave number?",
   "o": [
    "Ampere",
    "Pascal second",
    "Reciprocal metre",
    "Metre"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Wave number is the Reciprocal metre."
  },
  {
   "id": "physics-00058",
   "q": "Which instrument is used to measure Electric current?",
   "o": [
    "Hygrometer",
    "Ammeter",
    "Kymograph",
    "Barometer"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Ammeter is used to measure Electric current."
  },
  {
   "id": "physics-00059",
   "q": "What is the SI unit of Absorbed dose?",
   "o": [
    "Kilogram",
    "Gray",
    "Ampere",
    "Lumen"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Absorbed dose is the Gray."
  },
  {
   "id": "physics-00060",
   "q": "Which instrument is used to measure Depth of the sea?",
   "o": [
    "Galvanometer",
    "Radiometer",
    "Speedometer",
    "Fathometer"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Fathometer is used to measure Depth of the sea."
  },
  {
   "id": "physics-00061",
   "q": "What is the SI unit of Mass?",
   "o": [
    "Mole",
    "Kilogram",
    "Metre",
    "Coulomb"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Mass is the Kilogram."
  },
  {
   "id": "physics-00062",
   "q": "Which instrument is used to measure Ionising radiation?",
   "o": [
    "Spherometer",
    "Altimeter",
    "Transducer",
    "Geiger counter"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Geiger counter is used to measure Ionising radiation."
  },
  {
   "id": "physics-00063",
   "q": "What is the SI unit of Solid angle?",
   "o": [
    "Reciprocal metre",
    "Hertz",
    "Steradian",
    "Joule"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Solid angle is the Steradian."
  },
  {
   "id": "physics-00064",
   "q": "Which instrument is used to measure Distance travelled?",
   "o": [
    "Odometer",
    "Fathometer",
    "Calorimeter",
    "Spectrometer"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Odometer is used to measure Distance travelled."
  },
  {
   "id": "physics-00065",
   "q": "What is the SI unit of Entropy?",
   "o": [
    "Lumen",
    "Mole",
    "Pascal second",
    "Joule per Kelvin"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Entropy is the Joule per Kelvin."
  },
  {
   "id": "physics-00066",
   "q": "Which instrument is used to measure Humidity?",
   "o": [
    "Potometer",
    "Voltmeter",
    "Hygroscope",
    "Viscometer"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Hygroscope is used to measure Humidity."
  },
  {
   "id": "physics-00067",
   "q": "What is the SI unit of Magnetic flux?",
   "o": [
    "Farad",
    "Kelvin",
    "Lux",
    "Weber"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Magnetic flux is the Weber."
  },
  {
   "id": "physics-00068",
   "q": "Which instrument is used to measure Altitude?",
   "o": [
    "Manometer",
    "Altimeter",
    "Hygroscope",
    "Sphygmomanometer"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Altimeter is used to measure Altitude."
  },
  {
   "id": "physics-00069",
   "q": "What is the SI unit of Illuminance?",
   "o": [
    "Joule",
    "Lux",
    "Lumen",
    "Radian"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Illuminance is the Lux."
  },
  {
   "id": "physics-00070",
   "q": "Which instrument is used to measure Blood pressure variations?",
   "o": [
    "Kymograph",
    "Ammeter",
    "Audiometer",
    "Radiometer"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Kymograph is used to measure Blood pressure variations."
  },
  {
   "id": "physics-00071",
   "q": "What is the SI unit of Electric potential?",
   "o": [
    "Watt",
    "Siemens",
    "Gray",
    "Volt"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Electric potential is the Volt."
  },
  {
   "id": "physics-00072",
   "q": "Which instrument is used to measure Viscosity of liquids?",
   "o": [
    "Potometer",
    "Manometer",
    "Viscometer",
    "Altimeter"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Viscometer is used to measure Viscosity of liquids."
  },
  {
   "id": "physics-00073",
   "q": "What is the SI unit of Magnetic flux density?",
   "o": [
    "Hertz",
    "Ohm",
    "Watt",
    "Tesla"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Magnetic flux density is the Tesla."
  },
  {
   "id": "physics-00074",
   "q": "Which instrument is used to measure Heartbeats?",
   "o": [
    "Spherometer",
    "Stethoscope",
    "Pyrometer",
    "Anemometer"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Stethoscope is used to measure Heartbeats."
  },
  {
   "id": "physics-00075",
   "q": "What is the SI unit of Frequency?",
   "o": [
    "Hertz",
    "Metre",
    "Joule per Kelvin",
    "Mole"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Frequency is the Hertz."
  },
  {
   "id": "physics-00076",
   "q": "Which instrument is used to measure Heat change in reactions?",
   "o": [
    "Lactometer",
    "Calorimeter",
    "Manometer",
    "Nephelometer"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Calorimeter is used to measure Heat change in reactions."
  },
  {
   "id": "physics-00077",
   "q": "What is the SI unit of Force?",
   "o": [
    "Weber",
    "Hertz",
    "Joule",
    "Newton"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Force is the Newton."
  },
  {
   "id": "physics-00078",
   "q": "Which instrument is used to measure Heart electrical activity?",
   "o": [
    "Kymograph",
    "Electrocardiogram machine",
    "Crescograph",
    "Barometer"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Electrocardiogram machine is used to measure Heart electrical activity."
  },
  {
   "id": "physics-00079",
   "q": "What is the SI unit of Viscosity (dynamic)?",
   "o": [
    "Watt",
    "Pascal second",
    "Radian",
    "Gray"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Viscosity (dynamic) is the Pascal second."
  },
  {
   "id": "physics-00080",
   "q": "Which instrument is used to measure One form of energy into another?",
   "o": [
    "Transducer",
    "Cardiograph",
    "Tachometer",
    "Periscope"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Transducer is used to measure One form of energy into another."
  },
  {
   "id": "physics-00081",
   "q": "What is the SI unit of Electrical conductance?",
   "o": [
    "Siemens",
    "Hertz",
    "Kelvin",
    "Joule per Kelvin"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 1,
   "s": "generated",
   "e": "The SI unit of Electrical conductance is the Siemens."
  },
  {
   "id": "physics-00082",
   "q": "Which instrument is used to measure Temperature?",
   "o": [
    "Thermometer",
    "Voltmeter",
    "Periscope",
    "Chronometer"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Thermometer is used to measure Temperature."
  },
  {
   "id": "physics-00083",
   "q": "Which physical quantity is measured in Metre?",
   "o": [
    "Viscosity (dynamic)",
    "Length",
    "Solid angle",
    "Electrical conductance"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Metre is the SI unit of Length."
  },
  {
   "id": "physics-00084",
   "q": "Which instrument is used to measure Curvature of surfaces?",
   "o": [
    "Cardiograph",
    "Geiger counter",
    "Speedometer",
    "Spherometer"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Spherometer is used to measure Curvature of surfaces."
  },
  {
   "id": "physics-00085",
   "q": "Which physical quantity is measured in Henry?",
   "o": [
    "Time",
    "Radioactivity",
    "Inductance",
    "Length"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Henry is the SI unit of Inductance."
  },
  {
   "id": "physics-00086",
   "q": "Which instrument is used to measure Gas pressure?",
   "o": [
    "Pyrometer",
    "Manometer",
    "Viscometer",
    "Odometer"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Manometer is used to measure Gas pressure."
  },
  {
   "id": "physics-00087",
   "q": "Which physical quantity is measured in Joule?",
   "o": [
    "Electric charge",
    "Time",
    "Illuminance",
    "Energy"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Joule is the SI unit of Energy."
  },
  {
   "id": "physics-00088",
   "q": "Which instrument is used to measure Water absorption by plants?",
   "o": [
    "Potometer",
    "Anemometer",
    "Radiometer",
    "Geiger counter"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Potometer is used to measure Water absorption by plants."
  },
  {
   "id": "physics-00089",
   "q": "Which physical quantity is measured in Farad?",
   "o": [
    "Capacitance",
    "Amount of substance",
    "Absorbed dose",
    "Radioactivity"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Farad is the SI unit of Capacitance."
  },
  {
   "id": "physics-00090",
   "q": "Which instrument is used to measure Plant growth?",
   "o": [
    "Radiometer",
    "Crescograph",
    "Ammeter",
    "Endoscope"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Crescograph is used to measure Plant growth."
  },
  {
   "id": "physics-00091",
   "q": "Which physical quantity is measured in Second?",
   "o": [
    "Power",
    "Energy",
    "Luminous flux",
    "Time"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Second is the SI unit of Time."
  },
  {
   "id": "physics-00092",
   "q": "Which instrument is used to measure Rotational speed?",
   "o": [
    "Geiger counter",
    "Potometer",
    "Tachometer",
    "Audiometer"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Tachometer is used to measure Rotational speed."
  },
  {
   "id": "physics-00093",
   "q": "Which physical quantity is measured in Siemens?",
   "o": [
    "Mass",
    "Electrical conductance",
    "Electrical resistance",
    "Length"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Siemens is the SI unit of Electrical conductance."
  },
  {
   "id": "physics-00094",
   "q": "Which instrument is used to measure Hearing sensitivity?",
   "o": [
    "Hygroscope",
    "Audiometer",
    "Altimeter",
    "Spherometer"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Audiometer is used to measure Hearing sensitivity."
  },
  {
   "id": "physics-00095",
   "q": "Which physical quantity is measured in Gray?",
   "o": [
    "Power",
    "Magnetic flux density",
    "Absorbed dose",
    "Plane angle"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Gray is the SI unit of Absorbed dose."
  },
  {
   "id": "physics-00096",
   "q": "Which instrument is used to measure Speed and distance?",
   "o": [
    "Sphygmomanometer",
    "Odometer and Speedometer",
    "Polygraph",
    "Pyrometer"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Odometer and Speedometer is used to measure Speed and distance."
  },
  {
   "id": "physics-00097",
   "q": "Which physical quantity is measured in Kilogram?",
   "o": [
    "Mass",
    "Radioactivity",
    "Absorbed dose",
    "Force"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Kilogram is the SI unit of Mass."
  },
  {
   "id": "physics-00098",
   "q": "Which instrument is used to measure Electric potential difference?",
   "o": [
    "Voltmeter",
    "Cardiograph",
    "Viscometer",
    "Hygroscope"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Voltmeter is used to measure Electric potential difference."
  },
  {
   "id": "physics-00099",
   "q": "Which physical quantity is measured in Steradian?",
   "o": [
    "Electric current",
    "Frequency",
    "Illuminance",
    "Solid angle"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Steradian is the SI unit of Solid angle."
  },
  {
   "id": "physics-00100",
   "q": "Which instrument is used to measure Properties of light?",
   "o": [
    "Telescope",
    "Audiometer",
    "Fathometer",
    "Spectrometer"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Spectrometer is used to measure Properties of light."
  },
  {
   "id": "physics-00101",
   "q": "Which physical quantity is measured in Lux?",
   "o": [
    "Force",
    "Illuminance",
    "Mass",
    "Radioactivity"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Lux is the SI unit of Illuminance."
  },
  {
   "id": "physics-00102",
   "q": "Which instrument is used to measure Humidity?",
   "o": [
    "Altimeter",
    "Telescope",
    "Hygrometer",
    "Barometer"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Hygrometer is used to measure Humidity."
  },
  {
   "id": "physics-00103",
   "q": "Which physical quantity is measured in Joule per Kelvin?",
   "o": [
    "Magnetic flux",
    "Entropy",
    "Radioactivity",
    "Catalytic activity"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Joule per Kelvin is the SI unit of Entropy."
  },
  {
   "id": "physics-00104",
   "q": "Spectrometer is used for which of the following purposes?",
   "o": [
    "Electric potential difference",
    "Distance travelled",
    "Properties of light",
    "Viscosity of liquids"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Spectrometer measures Properties of light."
  },
  {
   "id": "physics-00105",
   "q": "Which physical quantity is measured in Becquerel?",
   "o": [
    "Electric current",
    "Radioactivity",
    "Plane angle",
    "Pressure"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Becquerel is the SI unit of Radioactivity."
  },
  {
   "id": "physics-00106",
   "q": "Microscope is used for which of the following purposes?",
   "o": [
    "Blood pressure variations",
    "Magnified view of tiny objects",
    "Multiple physiological responses",
    "Wind speed"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Microscope measures Magnified view of tiny objects."
  },
  {
   "id": "physics-00107",
   "q": "Which physical quantity is measured in Katal?",
   "o": [
    "Catalytic activity",
    "Frequency",
    "Viscosity (dynamic)",
    "Electric charge"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Katal is the SI unit of Catalytic activity."
  },
  {
   "id": "physics-00108",
   "q": "Odometer and Speedometer is used for which of the following purposes?",
   "o": [
    "Electric current",
    "Altitude",
    "Heart activity",
    "Speed and distance"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Odometer and Speedometer measures Speed and distance."
  },
  {
   "id": "physics-00109",
   "q": "Which physical quantity is measured in Candela?",
   "o": [
    "Electrical resistance",
    "Luminous intensity",
    "Wave number",
    "Mass"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Candela is the SI unit of Luminous intensity."
  },
  {
   "id": "physics-00110",
   "q": "Fathometer is used for which of the following purposes?",
   "o": [
    "Speed of a vehicle",
    "Multiple physiological responses",
    "Water absorption by plants",
    "Depth of the sea"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Fathometer measures Depth of the sea."
  },
  {
   "id": "physics-00111",
   "q": "Which physical quantity is measured in Ohm?",
   "o": [
    "Pressure",
    "Catalytic activity",
    "Magnetic flux",
    "Electrical resistance"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Ohm is the SI unit of Electrical resistance."
  },
  {
   "id": "physics-00112",
   "q": "Endoscope is used for which of the following purposes?",
   "o": [
    "Internal body organs",
    "Atmospheric pressure",
    "High temperature",
    "Earthquakes"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Endoscope measures Internal body organs."
  },
  {
   "id": "physics-00113",
   "q": "Which physical quantity is measured in Ampere?",
   "o": [
    "Viscosity (dynamic)",
    "Inductance",
    "Electric current",
    "Pressure"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Ampere is the SI unit of Electric current."
  },
  {
   "id": "physics-00114",
   "q": "Hygrometer is used for which of the following purposes?",
   "o": [
    "Speed of a vehicle",
    "Electric potential difference",
    "Humidity",
    "Heart electrical activity"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Hygrometer measures Humidity."
  },
  {
   "id": "physics-00115",
   "q": "Which physical quantity is measured in Radian?",
   "o": [
    "Energy",
    "Electric current",
    "Plane angle",
    "Entropy"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Radian is the SI unit of Plane angle."
  },
  {
   "id": "physics-00116",
   "q": "Lactometer is used for which of the following purposes?",
   "o": [
    "Objects above obstacles",
    "Hearing sensitivity",
    "Atmospheric pressure",
    "Purity of milk"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Lactometer measures Purity of milk."
  },
  {
   "id": "physics-00117",
   "q": "Which physical quantity is measured in Volt?",
   "o": [
    "Electric potential",
    "Viscosity (dynamic)",
    "Catalytic activity",
    "Time"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Volt is the SI unit of Electric potential."
  },
  {
   "id": "physics-00118",
   "q": "Anemometer is used for which of the following purposes?",
   "o": [
    "Electric current",
    "Distance travelled",
    "Humidity",
    "Wind speed"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Anemometer measures Wind speed."
  },
  {
   "id": "physics-00119",
   "q": "Which physical quantity is measured in Watt?",
   "o": [
    "Electrical resistance",
    "Power",
    "Luminous flux",
    "Energy"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Watt is the SI unit of Power."
  },
  {
   "id": "physics-00120",
   "q": "Spherometer is used for which of the following purposes?",
   "o": [
    "Curvature of surfaces",
    "Distance travelled",
    "Blood pressure",
    "Electric potential difference"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Spherometer measures Curvature of surfaces."
  },
  {
   "id": "physics-00121",
   "q": "Which physical quantity is measured in Lumen?",
   "o": [
    "Mass",
    "Radioactivity",
    "Force",
    "Luminous flux"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Lumen is the SI unit of Luminous flux."
  },
  {
   "id": "physics-00122",
   "q": "Kymograph is used for which of the following purposes?",
   "o": [
    "Depth of the sea",
    "Atmospheric pressure",
    "Blood pressure variations",
    "Earthquakes"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Kymograph measures Blood pressure variations."
  },
  {
   "id": "physics-00123",
   "q": "Which physical quantity is measured in Reciprocal metre?",
   "o": [
    "Pressure",
    "Temperature",
    "Wave number",
    "Length"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Reciprocal metre is the SI unit of Wave number."
  },
  {
   "id": "physics-00124",
   "q": "Speedometer is used for which of the following purposes?",
   "o": [
    "Humidity",
    "Speed of a vehicle",
    "Heat change in reactions",
    "Wind speed"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Speedometer measures Speed of a vehicle."
  },
  {
   "id": "physics-00125",
   "q": "Which physical quantity is measured in Pascal?",
   "o": [
    "Luminous intensity",
    "Length",
    "Pressure",
    "Mass"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Pascal is the SI unit of Pressure."
  },
  {
   "id": "physics-00126",
   "q": "Audiometer is used for which of the following purposes?",
   "o": [
    "Hearing sensitivity",
    "Heart electrical activity",
    "Electric current",
    "Magnified view of tiny objects"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Audiometer measures Hearing sensitivity."
  },
  {
   "id": "physics-00127",
   "q": "Which physical quantity is measured in Pascal second?",
   "o": [
    "Inductance",
    "Energy",
    "Viscosity (dynamic)",
    "Electric charge"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Pascal second is the SI unit of Viscosity (dynamic)."
  },
  {
   "id": "physics-00128",
   "q": "Barometer is used for which of the following purposes?",
   "o": [
    "Turbidity of liquid",
    "Electric current",
    "Atmospheric pressure",
    "Humidity"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Barometer measures Atmospheric pressure."
  },
  {
   "id": "physics-00129",
   "q": "Which physical quantity is measured in Hertz?",
   "o": [
    "Electric charge",
    "Frequency",
    "Radioactivity",
    "Viscosity (dynamic)"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Hertz is the SI unit of Frequency."
  },
  {
   "id": "physics-00130",
   "q": "Radiometer is used for which of the following purposes?",
   "o": [
    "Depth of the sea",
    "Rotational speed",
    "Electric potential difference",
    "Radiant energy"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Radiometer measures Radiant energy."
  },
  {
   "id": "physics-00131",
   "q": "Which physical quantity is measured in Kelvin?",
   "o": [
    "Luminous intensity",
    "Energy",
    "Luminous flux",
    "Temperature"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Kelvin is the SI unit of Temperature."
  },
  {
   "id": "physics-00132",
   "q": "Viscometer is used for which of the following purposes?",
   "o": [
    "Radiant energy",
    "Distant objects",
    "Atmospheric pressure",
    "Viscosity of liquids"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Viscometer measures Viscosity of liquids."
  },
  {
   "id": "physics-00133",
   "q": "Which physical quantity is measured in Tesla?",
   "o": [
    "Magnetic flux density",
    "Illuminance",
    "Temperature",
    "Length"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Tesla is the SI unit of Magnetic flux density."
  },
  {
   "id": "physics-00134",
   "q": "Ammeter is used for which of the following purposes?",
   "o": [
    "Wind speed",
    "Speed and distance",
    "Radiant energy",
    "Electric current"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Ammeter measures Electric current."
  },
  {
   "id": "physics-00135",
   "q": "Which physical quantity is measured in Weber?",
   "o": [
    "Mass",
    "Inductance",
    "Electric charge",
    "Magnetic flux"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Weber is the SI unit of Magnetic flux."
  },
  {
   "id": "physics-00136",
   "q": "Galvanometer is used for which of the following purposes?",
   "o": [
    "One form of energy into another",
    "Ionising radiation",
    "Hearing sensitivity",
    "Small electric currents"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Galvanometer measures Small electric currents."
  },
  {
   "id": "physics-00137",
   "q": "Which physical quantity is measured in Coulomb?",
   "o": [
    "Electric charge",
    "Mass",
    "Illuminance",
    "Energy"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Coulomb is the SI unit of Electric charge."
  },
  {
   "id": "physics-00138",
   "q": "Voltmeter is used for which of the following purposes?",
   "o": [
    "Internal body organs",
    "Heat change in reactions",
    "Electric potential difference",
    "Magnified view of tiny objects"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Voltmeter measures Electric potential difference."
  },
  {
   "id": "physics-00139",
   "q": "Which physical quantity is measured in Newton?",
   "o": [
    "Wave number",
    "Time",
    "Force",
    "Solid angle"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Newton is the SI unit of Force."
  },
  {
   "id": "physics-00140",
   "q": "Electrocardiogram machine is used for which of the following purposes?",
   "o": [
    "Multiple physiological responses",
    "Heart electrical activity",
    "Humidity",
    "Distance travelled"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Electrocardiogram machine measures Heart electrical activity."
  },
  {
   "id": "physics-00141",
   "q": "Which physical quantity is measured in Mole?",
   "o": [
    "Entropy",
    "Amount of substance",
    "Solid angle",
    "Electric potential"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 2,
   "s": "generated",
   "e": "Mole is the SI unit of Amount of substance."
  },
  {
   "id": "physics-00142",
   "q": "Cardiograph is used for which of the following purposes?",
   "o": [
    "Properties of light",
    "Distant objects",
    "Heart activity",
    "Blood pressure"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Cardiograph measures Heart activity."
  },
  {
   "id": "physics-00143",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Electrical resistance - Lumen",
    "Electrical resistance - Coulomb",
    "Electrical resistance - Farad",
    "Electrical resistance - Ohm"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Electrical resistance - Ohm is correctly matched."
  },
  {
   "id": "physics-00144",
   "q": "Thermometer is used for which of the following purposes?",
   "o": [
    "Earthquakes",
    "Heartbeats",
    "Temperature",
    "Humidity"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Thermometer measures Temperature."
  },
  {
   "id": "physics-00145",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Electrical resistance - Coulomb",
    "Electrical resistance - Lux",
    "Electrical resistance - Ohm",
    "Electrical resistance - Second"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Electrical resistance - Ohm is correctly matched."
  },
  {
   "id": "physics-00146",
   "q": "Calorimeter is used for which of the following purposes?",
   "o": [
    "Heart electrical activity",
    "Heat change in reactions",
    "Time accurately",
    "Blood pressure"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Calorimeter measures Heat change in reactions."
  },
  {
   "id": "physics-00147",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Luminous intensity - Newton",
    "Luminous intensity - Candela",
    "Luminous intensity - Katal",
    "Luminous intensity - Lux"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Luminous intensity - Candela is correctly matched."
  },
  {
   "id": "physics-00148",
   "q": "Odometer is used for which of the following purposes?",
   "o": [
    "Distance travelled",
    "Curvature of surfaces",
    "Internal body organs",
    "Multiple physiological responses"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Odometer measures Distance travelled."
  },
  {
   "id": "physics-00149",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Luminous intensity - Tesla",
    "Luminous intensity - Candela",
    "Luminous intensity - Ohm",
    "Luminous intensity - Gray"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Luminous intensity - Candela is correctly matched."
  },
  {
   "id": "physics-00150",
   "q": "Hygroscope is used for which of the following purposes?",
   "o": [
    "Speed of a vehicle",
    "Time accurately",
    "Gas pressure",
    "Humidity"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Hygroscope measures Humidity."
  },
  {
   "id": "physics-00151",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Electric charge - Candela",
    "Electric charge - Hertz",
    "Electric charge - Coulomb",
    "Electric charge - Kelvin"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Electric charge - Coulomb is correctly matched."
  },
  {
   "id": "physics-00152",
   "q": "Crescograph is used for which of the following purposes?",
   "o": [
    "Blood pressure variations",
    "Multiple physiological responses",
    "Electric potential difference",
    "Plant growth"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Crescograph measures Plant growth."
  },
  {
   "id": "physics-00153",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Electric charge - Coulomb",
    "Electric charge - Kilogram",
    "Electric charge - Pascal second",
    "Electric charge - Metre"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Electric charge - Coulomb is correctly matched."
  },
  {
   "id": "physics-00154",
   "q": "Transducer is used for which of the following purposes?",
   "o": [
    "One form of energy into another",
    "Small electric currents",
    "Electric potential difference",
    "Heart electrical activity"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Transducer measures One form of energy into another."
  },
  {
   "id": "physics-00155",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Illuminance - Ampere",
    "Illuminance - Lux",
    "Illuminance - Farad",
    "Illuminance - Henry"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Illuminance - Lux is correctly matched."
  },
  {
   "id": "physics-00156",
   "q": "Tachometer is used for which of the following purposes?",
   "o": [
    "Rotational speed",
    "Purity of milk",
    "Blood pressure",
    "Humidity"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Tachometer measures Rotational speed."
  },
  {
   "id": "physics-00157",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Illuminance - Katal",
    "Illuminance - Joule",
    "Illuminance - Reciprocal metre",
    "Illuminance - Lux"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Illuminance - Lux is correctly matched."
  },
  {
   "id": "physics-00158",
   "q": "Stethoscope is used for which of the following purposes?",
   "o": [
    "Heartbeats",
    "Gas pressure",
    "Humidity",
    "Heart activity"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Stethoscope measures Heartbeats."
  },
  {
   "id": "physics-00159",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Amount of substance - Hertz",
    "Amount of substance - Mole",
    "Amount of substance - Ampere",
    "Amount of substance - Kelvin"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Amount of substance - Mole is correctly matched."
  },
  {
   "id": "physics-00160",
   "q": "Seismograph is used for which of the following purposes?",
   "o": [
    "Radiant energy",
    "Electric potential difference",
    "Viscosity of liquids",
    "Earthquakes"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Seismograph measures Earthquakes."
  },
  {
   "id": "physics-00161",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Amount of substance - Mole",
    "Amount of substance - Metre",
    "Amount of substance - Farad",
    "Amount of substance - Candela"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Amount of substance - Mole is correctly matched."
  },
  {
   "id": "physics-00162",
   "q": "Telescope is used for which of the following purposes?",
   "o": [
    "Blood pressure variations",
    "Distant objects",
    "Purity of milk",
    "Multiple physiological responses"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Telescope measures Distant objects."
  },
  {
   "id": "physics-00163",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Plane angle - Radian",
    "Plane angle - Second",
    "Plane angle - Farad",
    "Plane angle - Gray"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Plane angle - Radian is correctly matched."
  },
  {
   "id": "physics-00164",
   "q": "Geiger counter is used for which of the following purposes?",
   "o": [
    "Ionising radiation",
    "Earthquakes",
    "Heart electrical activity",
    "Time accurately"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Geiger counter measures Ionising radiation."
  },
  {
   "id": "physics-00165",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Plane angle - Steradian",
    "Plane angle - Hertz",
    "Plane angle - Ampere",
    "Plane angle - Radian"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Plane angle - Radian is correctly matched."
  },
  {
   "id": "physics-00166",
   "q": "Nephelometer is used for which of the following purposes?",
   "o": [
    "Earthquakes",
    "Small electric currents",
    "Turbidity of liquid",
    "Humidity"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Nephelometer measures Turbidity of liquid."
  },
  {
   "id": "physics-00167",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Inductance - Kilogram",
    "Inductance - Hertz",
    "Inductance - Henry",
    "Inductance - Watt"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Inductance - Henry is correctly matched."
  },
  {
   "id": "physics-00168",
   "q": "Chronometer is used for which of the following purposes?",
   "o": [
    "Heartbeats",
    "Hearing sensitivity",
    "Blood pressure variations",
    "Time accurately"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Chronometer measures Time accurately."
  },
  {
   "id": "physics-00169",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Inductance - Coulomb",
    "Inductance - Lumen",
    "Inductance - Hertz",
    "Inductance - Henry"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Inductance - Henry is correctly matched."
  },
  {
   "id": "physics-00170",
   "q": "Pyrometer is used for which of the following purposes?",
   "o": [
    "Heartbeats",
    "Humidity",
    "Objects above obstacles",
    "High temperature"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Pyrometer measures High temperature."
  },
  {
   "id": "physics-00171",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Frequency - Hertz",
    "Frequency - Becquerel",
    "Frequency - Lux",
    "Frequency - Kelvin"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Frequency - Hertz is correctly matched."
  },
  {
   "id": "physics-00172",
   "q": "Sphygmomanometer is used for which of the following purposes?",
   "o": [
    "Blood pressure",
    "Plant growth",
    "Humidity",
    "Distant objects"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Sphygmomanometer measures Blood pressure."
  },
  {
   "id": "physics-00173",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Frequency - Metre",
    "Frequency - Ampere",
    "Frequency - Hertz",
    "Frequency - Kelvin"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Frequency - Hertz is correctly matched."
  },
  {
   "id": "physics-00174",
   "q": "Periscope is used for which of the following purposes?",
   "o": [
    "Objects above obstacles",
    "Speed and distance",
    "Depth of the sea",
    "Temperature"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Periscope measures Objects above obstacles."
  },
  {
   "id": "physics-00175",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Mass - Pascal second",
    "Mass - Siemens",
    "Mass - Second",
    "Mass - Kilogram"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Mass - Kilogram is correctly matched."
  },
  {
   "id": "physics-00176",
   "q": "Altimeter is used for which of the following purposes?",
   "o": [
    "Plant growth",
    "Objects above obstacles",
    "Altitude",
    "Viscosity of liquids"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Altimeter measures Altitude."
  },
  {
   "id": "physics-00177",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Mass - Kilogram",
    "Mass - Katal",
    "Mass - Metre",
    "Mass - Steradian"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Mass - Kilogram is correctly matched."
  },
  {
   "id": "physics-00178",
   "q": "Potometer is used for which of the following purposes?",
   "o": [
    "Rotational speed",
    "Properties of light",
    "Water absorption by plants",
    "Hearing sensitivity"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Potometer measures Water absorption by plants."
  },
  {
   "id": "physics-00179",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Capacitance - Coulomb",
    "Capacitance - Farad",
    "Capacitance - Joule per Kelvin",
    "Capacitance - Mole"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Capacitance - Farad is correctly matched."
  },
  {
   "id": "physics-00180",
   "q": "Manometer is used for which of the following purposes?",
   "o": [
    "Magnified view of tiny objects",
    "Gas pressure",
    "Atmospheric pressure",
    "Properties of light"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Manometer measures Gas pressure."
  },
  {
   "id": "physics-00181",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Capacitance - Coulomb",
    "Capacitance - Second",
    "Capacitance - Pascal second",
    "Capacitance - Farad"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Capacitance - Farad is correctly matched."
  },
  {
   "id": "physics-00182",
   "q": "Polygraph is used for which of the following purposes?",
   "o": [
    "Small electric currents",
    "Humidity",
    "Multiple physiological responses",
    "Atmospheric pressure"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 2,
   "s": "generated",
   "e": "Polygraph measures Multiple physiological responses."
  },
  {
   "id": "physics-00183",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Force - Second",
    "Force - Weber",
    "Force - Newton",
    "Force - Ohm"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Force - Newton is correctly matched."
  },
  {
   "id": "physics-00184",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Viscometer - Radiant energy",
    "Viscometer - Distant objects",
    "Viscometer - Gas pressure",
    "Viscometer - Viscosity of liquids"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Viscometer - Viscosity of liquids is correctly matched."
  },
  {
   "id": "physics-00185",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Force - Newton",
    "Force - Kelvin",
    "Force - Ohm",
    "Force - Candela"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Force - Newton is correctly matched."
  },
  {
   "id": "physics-00186",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Viscometer - Viscosity of liquids",
    "Viscometer - Curvature of surfaces",
    "Viscometer - Radiant energy",
    "Viscometer - Time accurately"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Viscometer - Viscosity of liquids is correctly matched."
  },
  {
   "id": "physics-00187",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Electric current - Weber",
    "Electric current - Ohm",
    "Electric current - Ampere",
    "Electric current - Newton"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Electric current - Ampere is correctly matched."
  },
  {
   "id": "physics-00188",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Manometer - Gas pressure",
    "Manometer - Radiant energy",
    "Manometer - Rotational speed",
    "Manometer - Humidity"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Manometer - Gas pressure is correctly matched."
  },
  {
   "id": "physics-00189",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Electric current - Second",
    "Electric current - Pascal",
    "Electric current - Ampere",
    "Electric current - Candela"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Electric current - Ampere is correctly matched."
  },
  {
   "id": "physics-00190",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Manometer - Objects above obstacles",
    "Manometer - Curvature of surfaces",
    "Manometer - Gas pressure",
    "Manometer - Water absorption by plants"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Manometer - Gas pressure is correctly matched."
  },
  {
   "id": "physics-00191",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Luminous flux - Farad",
    "Luminous flux - Ampere",
    "Luminous flux - Lumen",
    "Luminous flux - Candela"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Luminous flux - Lumen is correctly matched."
  },
  {
   "id": "physics-00192",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Nephelometer - Heart activity",
    "Nephelometer - Objects above obstacles",
    "Nephelometer - Turbidity of liquid",
    "Nephelometer - Water absorption by plants"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Nephelometer - Turbidity of liquid is correctly matched."
  },
  {
   "id": "physics-00193",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Luminous flux - Lumen",
    "Luminous flux - Ampere",
    "Luminous flux - Candela",
    "Luminous flux - Siemens"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Luminous flux - Lumen is correctly matched."
  },
  {
   "id": "physics-00194",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Nephelometer - Plant growth",
    "Nephelometer - Humidity",
    "Nephelometer - Turbidity of liquid",
    "Nephelometer - One form of energy into another"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Nephelometer - Turbidity of liquid is correctly matched."
  },
  {
   "id": "physics-00195",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Length - Katal",
    "Length - Henry",
    "Length - Joule",
    "Length - Metre"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Length - Metre is correctly matched."
  },
  {
   "id": "physics-00196",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Sphygmomanometer - Blood pressure",
    "Sphygmomanometer - Blood pressure variations",
    "Sphygmomanometer - Water absorption by plants",
    "Sphygmomanometer - Heart electrical activity"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Sphygmomanometer - Blood pressure is correctly matched."
  },
  {
   "id": "physics-00197",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Length - Becquerel",
    "Length - Hertz",
    "Length - Metre",
    "Length - Lux"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Length - Metre is correctly matched."
  },
  {
   "id": "physics-00198",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Sphygmomanometer - Wind speed",
    "Sphygmomanometer - Blood pressure",
    "Sphygmomanometer - Plant growth",
    "Sphygmomanometer - Objects above obstacles"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Sphygmomanometer - Blood pressure is correctly matched."
  },
  {
   "id": "physics-00199",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Energy - Steradian",
    "Energy - Joule",
    "Energy - Weber",
    "Energy - Kelvin"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Energy - Joule is correctly matched."
  },
  {
   "id": "physics-00200",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Hygroscope - Internal body organs",
    "Hygroscope - Earthquakes",
    "Hygroscope - Humidity",
    "Hygroscope - Heart electrical activity"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Hygroscope - Humidity is correctly matched."
  },
  {
   "id": "physics-00201",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Energy - Tesla",
    "Energy - Candela",
    "Energy - Joule",
    "Energy - Weber"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Energy - Joule is correctly matched."
  },
  {
   "id": "physics-00202",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Hygroscope - Earthquakes",
    "Hygroscope - Humidity",
    "Hygroscope - High temperature",
    "Hygroscope - Temperature"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Hygroscope - Humidity is correctly matched."
  },
  {
   "id": "physics-00203",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Catalytic activity - Mole",
    "Catalytic activity - Lux",
    "Catalytic activity - Katal",
    "Catalytic activity - Ampere"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Catalytic activity - Katal is correctly matched."
  },
  {
   "id": "physics-00204",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Galvanometer - Small electric currents",
    "Galvanometer - Wind speed",
    "Galvanometer - Speed and distance",
    "Galvanometer - Speed of a vehicle"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Galvanometer - Small electric currents is correctly matched."
  },
  {
   "id": "physics-00205",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Catalytic activity - Steradian",
    "Catalytic activity - Pascal second",
    "Catalytic activity - Katal",
    "Catalytic activity - Watt"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Catalytic activity - Katal is correctly matched."
  },
  {
   "id": "physics-00206",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Galvanometer - Small electric currents",
    "Galvanometer - Radiant energy",
    "Galvanometer - Humidity",
    "Galvanometer - Water absorption by plants"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Galvanometer - Small electric currents is correctly matched."
  },
  {
   "id": "physics-00207",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Entropy - Volt",
    "Entropy - Mole",
    "Entropy - Newton",
    "Entropy - Joule per Kelvin"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Entropy - Joule per Kelvin is correctly matched."
  },
  {
   "id": "physics-00208",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Telescope - Rotational speed",
    "Telescope - Depth of the sea",
    "Telescope - Blood pressure variations",
    "Telescope - Distant objects"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Telescope - Distant objects is correctly matched."
  },
  {
   "id": "physics-00209",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Entropy - Lux",
    "Entropy - Joule per Kelvin",
    "Entropy - Second",
    "Entropy - Joule"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Entropy - Joule per Kelvin is correctly matched."
  },
  {
   "id": "physics-00210",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Telescope - Distant objects",
    "Telescope - Humidity",
    "Telescope - Objects above obstacles",
    "Telescope - Plant growth"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Telescope - Distant objects is correctly matched."
  },
  {
   "id": "physics-00211",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Absorbed dose - Gray",
    "Absorbed dose - Candela",
    "Absorbed dose - Becquerel",
    "Absorbed dose - Henry"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Absorbed dose - Gray is correctly matched."
  },
  {
   "id": "physics-00212",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Radiometer - Electric current",
    "Radiometer - Earthquakes",
    "Radiometer - Temperature",
    "Radiometer - Radiant energy"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Radiometer - Radiant energy is correctly matched."
  },
  {
   "id": "physics-00213",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Absorbed dose - Weber",
    "Absorbed dose - Tesla",
    "Absorbed dose - Gray",
    "Absorbed dose - Candela"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Absorbed dose - Gray is correctly matched."
  },
  {
   "id": "physics-00214",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Radiometer - Temperature",
    "Radiometer - Radiant energy",
    "Radiometer - Wind speed",
    "Radiometer - Heart electrical activity"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Radiometer - Radiant energy is correctly matched."
  },
  {
   "id": "physics-00215",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Time - Joule",
    "Time - Second",
    "Time - Ohm",
    "Time - Farad"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Time - Second is correctly matched."
  },
  {
   "id": "physics-00216",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Spectrometer - Blood pressure",
    "Spectrometer - Properties of light",
    "Spectrometer - Viscosity of liquids",
    "Spectrometer - Water absorption by plants"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Spectrometer - Properties of light is correctly matched."
  },
  {
   "id": "physics-00217",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Time - Becquerel",
    "Time - Ohm",
    "Time - Mole",
    "Time - Second"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Time - Second is correctly matched."
  },
  {
   "id": "physics-00218",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Spectrometer - Properties of light",
    "Spectrometer - Ionising radiation",
    "Spectrometer - Altitude",
    "Spectrometer - Turbidity of liquid"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Spectrometer - Properties of light is correctly matched."
  },
  {
   "id": "physics-00219",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Radioactivity - Kelvin",
    "Radioactivity - Kilogram",
    "Radioactivity - Metre",
    "Radioactivity - Becquerel"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Radioactivity - Becquerel is correctly matched."
  },
  {
   "id": "physics-00220",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Lactometer - One form of energy into another",
    "Lactometer - Gas pressure",
    "Lactometer - Heart activity",
    "Lactometer - Purity of milk"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Lactometer - Purity of milk is correctly matched."
  },
  {
   "id": "physics-00221",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Radioactivity - Becquerel",
    "Radioactivity - Mole",
    "Radioactivity - Volt",
    "Radioactivity - Katal"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Radioactivity - Becquerel is correctly matched."
  },
  {
   "id": "physics-00222",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Lactometer - Heartbeats",
    "Lactometer - Purity of milk",
    "Lactometer - Electric potential difference",
    "Lactometer - Properties of light"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Lactometer - Purity of milk is correctly matched."
  },
  {
   "id": "physics-00223",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Solid angle - Joule",
    "Solid angle - Steradian",
    "Solid angle - Second",
    "Solid angle - Reciprocal metre"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Solid angle - Steradian is correctly matched."
  },
  {
   "id": "physics-00224",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Pyrometer - Purity of milk",
    "Pyrometer - Blood pressure variations",
    "Pyrometer - High temperature",
    "Pyrometer - Heartbeats"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Pyrometer - High temperature is correctly matched."
  },
  {
   "id": "physics-00225",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Solid angle - Gray",
    "Solid angle - Radian",
    "Solid angle - Steradian",
    "Solid angle - Metre"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Solid angle - Steradian is correctly matched."
  },
  {
   "id": "physics-00226",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Pyrometer - Rotational speed",
    "Pyrometer - Humidity",
    "Pyrometer - High temperature",
    "Pyrometer - Plant growth"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Pyrometer - High temperature is correctly matched."
  },
  {
   "id": "physics-00227",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Electrical conductance - Siemens",
    "Electrical conductance - Metre",
    "Electrical conductance - Watt",
    "Electrical conductance - Becquerel"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Electrical conductance - Siemens is correctly matched."
  },
  {
   "id": "physics-00228",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Geiger counter - Temperature",
    "Geiger counter - Ionising radiation",
    "Geiger counter - Earthquakes",
    "Geiger counter - Gas pressure"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Geiger counter - Ionising radiation is correctly matched."
  },
  {
   "id": "physics-00229",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Electrical conductance - Siemens",
    "Electrical conductance - Kelvin",
    "Electrical conductance - Katal",
    "Electrical conductance - Becquerel"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Electrical conductance - Siemens is correctly matched."
  },
  {
   "id": "physics-00230",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Geiger counter - Viscosity of liquids",
    "Geiger counter - Humidity",
    "Geiger counter - Distance travelled",
    "Geiger counter - Ionising radiation"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Geiger counter - Ionising radiation is correctly matched."
  },
  {
   "id": "physics-00231",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Pressure - Pascal second",
    "Pressure - Hertz",
    "Pressure - Kelvin",
    "Pressure - Pascal"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Pressure - Pascal is correctly matched."
  },
  {
   "id": "physics-00232",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Potometer - Water absorption by plants",
    "Potometer - Plant growth",
    "Potometer - Internal body organs",
    "Potometer - Electric current"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Potometer - Water absorption by plants is correctly matched."
  },
  {
   "id": "physics-00233",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Pressure - Lumen",
    "Pressure - Katal",
    "Pressure - Pascal",
    "Pressure - Kelvin"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Pressure - Pascal is correctly matched."
  },
  {
   "id": "physics-00234",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Potometer - Water absorption by plants",
    "Potometer - Electric potential difference",
    "Potometer - Heartbeats",
    "Potometer - Distance travelled"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Potometer - Water absorption by plants is correctly matched."
  },
  {
   "id": "physics-00235",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Viscosity (dynamic) - Pascal second",
    "Viscosity (dynamic) - Ampere",
    "Viscosity (dynamic) - Joule per Kelvin",
    "Viscosity (dynamic) - Tesla"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Viscosity (dynamic) - Pascal second is correctly matched."
  },
  {
   "id": "physics-00236",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Calorimeter - Temperature",
    "Calorimeter - Heat change in reactions",
    "Calorimeter - Humidity",
    "Calorimeter - Distant objects"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Calorimeter - Heat change in reactions is correctly matched."
  },
  {
   "id": "physics-00237",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Viscosity (dynamic) - Pascal second",
    "Viscosity (dynamic) - Watt",
    "Viscosity (dynamic) - Ohm",
    "Viscosity (dynamic) - Kilogram"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Viscosity (dynamic) - Pascal second is correctly matched."
  },
  {
   "id": "physics-00238",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Calorimeter - One form of energy into another",
    "Calorimeter - Time accurately",
    "Calorimeter - Heat change in reactions",
    "Calorimeter - Wind speed"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Calorimeter - Heat change in reactions is correctly matched."
  },
  {
   "id": "physics-00239",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Wave number - Radian",
    "Wave number - Kelvin",
    "Wave number - Mole",
    "Wave number - Reciprocal metre"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Wave number - Reciprocal metre is correctly matched."
  },
  {
   "id": "physics-00240",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Barometer - Atmospheric pressure",
    "Barometer - Altitude",
    "Barometer - Ionising radiation",
    "Barometer - Curvature of surfaces"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Barometer - Atmospheric pressure is correctly matched."
  },
  {
   "id": "physics-00241",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Wave number - Coulomb",
    "Wave number - Becquerel",
    "Wave number - Reciprocal metre",
    "Wave number - Mole"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Wave number - Reciprocal metre is correctly matched."
  },
  {
   "id": "physics-00242",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Barometer - Hearing sensitivity",
    "Barometer - One form of energy into another",
    "Barometer - Rotational speed",
    "Barometer - Atmospheric pressure"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Barometer - Atmospheric pressure is correctly matched."
  },
  {
   "id": "physics-00243",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Magnetic flux - Siemens",
    "Magnetic flux - Farad",
    "Magnetic flux - Weber",
    "Magnetic flux - Volt"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Magnetic flux - Weber is correctly matched."
  },
  {
   "id": "physics-00244",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Chronometer - Speed of a vehicle",
    "Chronometer - Time accurately",
    "Chronometer - Depth of the sea",
    "Chronometer - Hearing sensitivity"
   ],
   "a": 1,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Chronometer - Time accurately is correctly matched."
  },
  {
   "id": "physics-00245",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Magnetic flux - Weber",
    "Magnetic flux - Candela",
    "Magnetic flux - Mole",
    "Magnetic flux - Reciprocal metre"
   ],
   "a": 0,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Magnetic flux - Weber is correctly matched."
  },
  {
   "id": "physics-00246",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Chronometer - Time accurately",
    "Chronometer - Speed of a vehicle",
    "Chronometer - High temperature",
    "Chronometer - Plant growth"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Chronometer - Time accurately is correctly matched."
  },
  {
   "id": "physics-00247",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Power - Kelvin",
    "Power - Radian",
    "Power - Newton",
    "Power - Watt"
   ],
   "a": 3,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Power - Watt is correctly matched."
  },
  {
   "id": "physics-00248",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Hygrometer - Humidity",
    "Hygrometer - Earthquakes",
    "Hygrometer - Time accurately",
    "Hygrometer - Multiple physiological responses"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Hygrometer - Humidity is correctly matched."
  },
  {
   "id": "physics-00249",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Power - Weber",
    "Power - Watt",
    "Power - Lux",
    "Power - Second"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Power - Watt is correctly matched."
  },
  {
   "id": "physics-00250",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Hygrometer - High temperature",
    "Hygrometer - Purity of milk",
    "Hygrometer - Humidity",
    "Hygrometer - Curvature of surfaces"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Hygrometer - Humidity is correctly matched."
  },
  {
   "id": "physics-00251",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Electric potential - Lumen",
    "Electric potential - Kilogram",
    "Electric potential - Volt",
    "Electric potential - Lux"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Electric potential - Volt is correctly matched."
  },
  {
   "id": "physics-00252",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Kymograph - Wind speed",
    "Kymograph - Plant growth",
    "Kymograph - Blood pressure variations",
    "Kymograph - Objects above obstacles"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Kymograph - Blood pressure variations is correctly matched."
  },
  {
   "id": "physics-00253",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Electric potential - Radian",
    "Electric potential - Volt",
    "Electric potential - Metre",
    "Electric potential - Reciprocal metre"
   ],
   "a": 1,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Electric potential - Volt is correctly matched."
  },
  {
   "id": "physics-00254",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Kymograph - Altitude",
    "Kymograph - Electric current",
    "Kymograph - Blood pressure variations",
    "Kymograph - Plant growth"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Kymograph - Blood pressure variations is correctly matched."
  },
  {
   "id": "physics-00255",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Temperature - Lux",
    "Temperature - Kilogram",
    "Temperature - Kelvin",
    "Temperature - Reciprocal metre"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Temperature - Kelvin is correctly matched."
  },
  {
   "id": "physics-00256",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Electrocardiogram machine - Properties of light",
    "Electrocardiogram machine - Wind speed",
    "Electrocardiogram machine - Heart electrical activity",
    "Electrocardiogram machine - Humidity"
   ],
   "a": 2,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Electrocardiogram machine - Heart electrical activity is correctly matched."
  },
  {
   "id": "physics-00257",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Temperature - Ampere",
    "Temperature - Metre",
    "Temperature - Kelvin",
    "Temperature - Candela"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Temperature - Kelvin is correctly matched."
  },
  {
   "id": "physics-00258",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Electrocardiogram machine - Wind speed",
    "Electrocardiogram machine - Temperature",
    "Electrocardiogram machine - Blood pressure",
    "Electrocardiogram machine - Heart electrical activity"
   ],
   "a": 3,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Electrocardiogram machine - Heart electrical activity is correctly matched."
  },
  {
   "id": "physics-00259",
   "q": "Which of the following pairs of quantity and SI unit is correctly matched?",
   "o": [
    "Magnetic flux density - Lumen",
    "Magnetic flux density - Siemens",
    "Magnetic flux density - Tesla",
    "Magnetic flux density - Henry"
   ],
   "a": 2,
   "t": "SI Units",
   "l": 3,
   "s": "generated",
   "e": "Only Magnetic flux density - Tesla is correctly matched."
  },
  {
   "id": "physics-00260",
   "q": "Which of the following pairs of instrument and use is correctly matched?",
   "o": [
    "Audiometer - Hearing sensitivity",
    "Audiometer - One form of energy into another",
    "Audiometer - Speed of a vehicle",
    "Audiometer - Wind speed"
   ],
   "a": 0,
   "t": "Scientific Instruments",
   "l": 3,
   "s": "generated",
   "e": "Only Audiometer - Hearing sensitivity is correctly matched."
  }
 ]
};
  if (typeof module !== "undefined" && module.exports) module.exports = data;
  if (typeof window !== "undefined") {
    window.QBANK_CATEGORIES = window.QBANK_CATEGORIES || {};
    window.QBANK_CATEGORIES[data.slug] = data;
  }
})();
