"use strict";
/* Generated by tools/build-qbank.js — do not edit by hand. */
(function () {
  var data = {
 "slug": "sports",
 "name": "Sports",
 "icon": "trophy",
 "group": "General Knowledge",
 "exams": [
  "ssc-cgl",
  "ssc-chsl",
  "railways"
 ],
 "blurb": "Trophies, terms, players and tournaments.",
 "count": 260,
 "questions": [
  {
   "id": "sports-00001",
   "question": "How many players are there in a cricket team on the field?",
   "options": [
    "10",
    "11",
    "12",
    "9"
   ],
   "answer": 1,
   "explanation": "A cricket team fields 11 players.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00002",
   "question": "How many players are there in a football team on the field?",
   "options": [
    "9",
    "10",
    "11",
    "12"
   ],
   "answer": 2,
   "explanation": "A football team has 11 players on the field.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00003",
   "question": "How many players are there in a kabaddi team on the court?",
   "options": [
    "5",
    "6",
    "7",
    "8"
   ],
   "answer": 2,
   "explanation": "Each kabaddi team has 7 players on the court.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00004",
   "question": "How many players are there in a volleyball team?",
   "options": [
    "5",
    "6",
    "7",
    "8"
   ],
   "answer": 1,
   "explanation": "A volleyball team has 6 players on the court.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00005",
   "question": "How many players are there in a basketball team on the court?",
   "options": [
    "5",
    "6",
    "7",
    "4"
   ],
   "answer": 0,
   "explanation": "A basketball team has 5 players on the court.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00006",
   "question": "Which country won the first Cricket World Cup in 1975?",
   "options": [
    "Australia",
    "West Indies",
    "England",
    "India"
   ],
   "answer": 1,
   "explanation": "West Indies won the first Cricket World Cup in 1975.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00007",
   "question": "Which country has won the most FIFA World Cups?",
   "options": [
    "Germany",
    "Italy",
    "Brazil",
    "Argentina"
   ],
   "answer": 2,
   "explanation": "Brazil has won the FIFA World Cup five times.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00008",
   "question": "The Ashes series is played between:",
   "options": [
    "India and Australia",
    "England and Australia",
    "England and South Africa",
    "New Zealand and Australia"
   ],
   "answer": 1,
   "explanation": "The Ashes is contested between England and Australia.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00009",
   "question": "In which sport is the Davis Cup awarded?",
   "options": [
    "Badminton",
    "Tennis",
    "Hockey",
    "Table tennis"
   ],
   "answer": 1,
   "explanation": "The Davis Cup is a men's international tennis team competition.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00010",
   "question": "The Ryder Cup is associated with which sport?",
   "options": [
    "Golf",
    "Polo",
    "Cricket",
    "Hockey"
   ],
   "answer": 0,
   "explanation": "The Ryder Cup is a golf competition between teams from the USA and Europe.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00011",
   "question": "Which sport is associated with the Thomas Cup?",
   "options": [
    "Badminton",
    "Tennis",
    "Squash",
    "Boxing"
   ],
   "answer": 0,
   "explanation": "The Thomas Cup is the men's world badminton team championship.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00012",
   "question": "The Ranji Trophy is associated with which sport?",
   "options": [
    "Football",
    "Cricket",
    "Hockey",
    "Kabaddi"
   ],
   "answer": 1,
   "explanation": "The Ranji Trophy is a domestic cricket championship in India.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00013",
   "question": "Santosh Trophy is associated with which sport?",
   "options": [
    "Football",
    "Cricket",
    "Hockey",
    "Volleyball"
   ],
   "answer": 0,
   "explanation": "The Santosh Trophy is a football competition in India.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00014",
   "question": "How many rings are there in the Olympic symbol?",
   "options": [
    "4",
    "5",
    "6",
    "7"
   ],
   "answer": 1,
   "explanation": "The Olympic symbol has five interlocking rings.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00015",
   "question": "In which country were the first modern Olympic Games held?",
   "options": [
    "France",
    "Greece",
    "Italy",
    "England"
   ],
   "answer": 1,
   "explanation": "The first modern Olympics were held in Athens, Greece, in 1896.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00016",
   "question": "Which Indian won the first individual Olympic gold medal?",
   "options": [
    "Abhinav Bindra",
    "Sushil Kumar",
    "Vijender Singh",
    "Neeraj Chopra"
   ],
   "answer": 0,
   "explanation": "Abhinav Bindra won gold in shooting at the 2008 Beijing Olympics.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00017",
   "question": "Which Indian athlete won gold in the javelin throw at the Tokyo Olympics?",
   "options": [
    "Neeraj Chopra",
    "Bajrang Punia",
    "Ravi Dahiya",
    "Mirabai Chanu"
   ],
   "answer": 0,
   "explanation": "Neeraj Chopra won India's first athletics Olympic gold in 2021.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00018",
   "question": "Who is known as the Flying Sikh?",
   "options": [
    "Milkha Singh",
    "P. T. Usha",
    "Dhyan Chand",
    "Kapil Dev"
   ],
   "answer": 0,
   "explanation": "Milkha Singh was nicknamed the Flying Sikh.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00019",
   "question": "Who is known as the Wizard of Hockey?",
   "options": [
    "Dhyan Chand",
    "Roop Singh",
    "Balbir Singh",
    "Ajit Pal Singh"
   ],
   "answer": 0,
   "explanation": "Major Dhyan Chand is called the Wizard of Hockey.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00020",
   "question": "In which sport is the term 'googly' used?",
   "options": [
    "Hockey",
    "Cricket",
    "Football",
    "Tennis"
   ],
   "answer": 1,
   "explanation": "A googly is a deceptive delivery bowled in cricket.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00021",
   "question": "In which sport is the term 'love' used for a score of zero?",
   "options": [
    "Badminton",
    "Tennis",
    "Squash",
    "Polo"
   ],
   "answer": 1,
   "explanation": "In tennis, zero is called love.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00022",
   "question": "Which country hosted the 2020 Summer Olympics (held in 2021)?",
   "options": [
    "China",
    "Japan",
    "Brazil",
    "France"
   ],
   "answer": 1,
   "explanation": "The Tokyo Olympics were held in Japan in 2021.",
   "topic": "Curated",
   "level": 1,
   "source": "curated"
  },
  {
   "id": "sports-00023",
   "question": "Which Indian sportsperson is called the Queen of Indian Boxing?",
   "options": [
    "Mary Kom",
    "Sakshi Malik",
    "P. T. Usha",
    "Sania Mirza"
   ],
   "answer": 0,
   "explanation": "Mary Kom is a multiple world champion boxer from Manipur.",
   "topic": "Curated",
   "level": 2,
   "source": "curated"
  },
  {
   "id": "sports-00024",
   "question": "How many players are there in a Cricket team?",
   "options": [
    "2",
    "15",
    "4",
    "11"
   ],
   "answer": 3,
   "explanation": "A Cricket team has 11 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00025",
   "question": "FIH Hockey World Cup is associated with which sport?",
   "options": [
    "Football",
    "Hockey",
    "Multi-sport",
    "Cricket"
   ],
   "answer": 1,
   "explanation": "FIH Hockey World Cup is associated with Hockey.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00026",
   "question": "How many players are there in a Polo team?",
   "options": [
    "4",
    "6",
    "8",
    "7"
   ],
   "answer": 0,
   "explanation": "A Polo team has 4 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00027",
   "question": "Davis Cup is associated with which sport?",
   "options": [
    "Badminton",
    "Cricket",
    "Football",
    "Tennis"
   ],
   "answer": 3,
   "explanation": "Davis Cup is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00028",
   "question": "How many players are there in a Table tennis (singles) team?",
   "options": [
    "7",
    "15",
    "2",
    "1"
   ],
   "answer": 3,
   "explanation": "A Table tennis (singles) team has 1 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00029",
   "question": "Deodhar Trophy is associated with which sport?",
   "options": [
    "Football",
    "Table Tennis",
    "Cricket",
    "Tennis"
   ],
   "answer": 2,
   "explanation": "Deodhar Trophy is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00030",
   "question": "How many players are there in a Ice hockey team?",
   "options": [
    "7",
    "2",
    "6",
    "5"
   ],
   "answer": 2,
   "explanation": "A Ice hockey team has 6 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00031",
   "question": "Santosh Trophy is associated with which sport?",
   "options": [
    "Badminton",
    "Football",
    "Cricket",
    "Tennis"
   ],
   "answer": 1,
   "explanation": "Santosh Trophy is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00032",
   "question": "How many players are there in a Rugby union team?",
   "options": [
    "15",
    "7",
    "5",
    "6"
   ],
   "answer": 0,
   "explanation": "A Rugby union team has 15 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00033",
   "question": "World Cup (Cricket) is associated with which sport?",
   "options": [
    "Tennis",
    "Football",
    "Hockey",
    "Cricket"
   ],
   "answer": 3,
   "explanation": "World Cup (Cricket) is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00034",
   "question": "How many players are there in a Kho Kho team?",
   "options": [
    "2",
    "8",
    "9",
    "6"
   ],
   "answer": 2,
   "explanation": "A Kho Kho team has 9 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00035",
   "question": "Champions Trophy (Cricket) is associated with which sport?",
   "options": [
    "Badminton",
    "Multi-sport",
    "Cricket",
    "Football"
   ],
   "answer": 2,
   "explanation": "Champions Trophy (Cricket) is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00036",
   "question": "How many players are there in a Throwball team?",
   "options": [
    "5",
    "6",
    "7",
    "11"
   ],
   "answer": 2,
   "explanation": "A Throwball team has 7 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00037",
   "question": "Irani Cup is associated with which sport?",
   "options": [
    "Football",
    "Multi-sport",
    "Cricket",
    "Tennis"
   ],
   "answer": 2,
   "explanation": "Irani Cup is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00038",
   "question": "How many players are there in a Badminton (doubles) team?",
   "options": [
    "9",
    "2",
    "6",
    "7"
   ],
   "answer": 1,
   "explanation": "A Badminton (doubles) team has 2 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00039",
   "question": "Syed Mushtaq Ali Trophy is associated with which sport?",
   "options": [
    "Hockey",
    "Tennis",
    "Badminton",
    "Cricket"
   ],
   "answer": 3,
   "explanation": "Syed Mushtaq Ali Trophy is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00040",
   "question": "How many players are there in a Hockey team?",
   "options": [
    "6",
    "15",
    "11",
    "7"
   ],
   "answer": 2,
   "explanation": "A Hockey team has 11 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00041",
   "question": "The Ashes is associated with which sport?",
   "options": [
    "Football",
    "Badminton",
    "Cricket",
    "Hockey"
   ],
   "answer": 2,
   "explanation": "The Ashes is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00042",
   "question": "How many players are there in a Volleyball team?",
   "options": [
    "11",
    "7",
    "6",
    "8"
   ],
   "answer": 2,
   "explanation": "A Volleyball team has 6 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00043",
   "question": "Asia Cup is associated with which sport?",
   "options": [
    "Cricket",
    "Badminton",
    "Tennis",
    "Hockey"
   ],
   "answer": 0,
   "explanation": "Asia Cup is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00044",
   "question": "How many players are there in a Water polo team?",
   "options": [
    "7",
    "11",
    "9",
    "1"
   ],
   "answer": 0,
   "explanation": "A Water polo team has 7 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00045",
   "question": "Subroto Cup is associated with which sport?",
   "options": [
    "Badminton",
    "Multi-sport",
    "Football",
    "Tennis"
   ],
   "answer": 2,
   "explanation": "Subroto Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00046",
   "question": "How many players are there in a Baseball team?",
   "options": [
    "7",
    "9",
    "11",
    "6"
   ],
   "answer": 1,
   "explanation": "A Baseball team has 9 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00047",
   "question": "Copa America is associated with which sport?",
   "options": [
    "Football",
    "Hockey",
    "Cricket",
    "Badminton"
   ],
   "answer": 0,
   "explanation": "Copa America is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00048",
   "question": "How many players are there in a Football team?",
   "options": [
    "11",
    "7",
    "2",
    "4"
   ],
   "answer": 0,
   "explanation": "A Football team has 11 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00049",
   "question": "Ranji Trophy is associated with which sport?",
   "options": [
    "Tennis",
    "Football",
    "Cricket",
    "Table Tennis"
   ],
   "answer": 2,
   "explanation": "Ranji Trophy is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00050",
   "question": "How many players are there in a Basketball team?",
   "options": [
    "11",
    "6",
    "5",
    "7"
   ],
   "answer": 2,
   "explanation": "A Basketball team has 5 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00051",
   "question": "Rovers Cup is associated with which sport?",
   "options": [
    "Football",
    "Cricket",
    "Multi-sport",
    "Badminton"
   ],
   "answer": 0,
   "explanation": "Rovers Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00052",
   "question": "How many players are there in a Korfball team?",
   "options": [
    "11",
    "7",
    "8",
    "2"
   ],
   "answer": 2,
   "explanation": "A Korfball team has 8 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00053",
   "question": "Corbillon Cup is associated with which sport?",
   "options": [
    "Table Tennis",
    "Cricket",
    "Tennis",
    "Football"
   ],
   "answer": 0,
   "explanation": "Corbillon Cup is associated with Table Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00054",
   "question": "How many players are there in a Rugby sevens team?",
   "options": [
    "4",
    "2",
    "7",
    "5"
   ],
   "answer": 2,
   "explanation": "A Rugby sevens team has 7 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00055",
   "question": "Duleep Trophy is associated with which sport?",
   "options": [
    "Football",
    "Cricket",
    "Golf",
    "Multi-sport"
   ],
   "answer": 1,
   "explanation": "Duleep Trophy is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00056",
   "question": "How many players are there in a Netball team?",
   "options": [
    "9",
    "11",
    "7",
    "15"
   ],
   "answer": 2,
   "explanation": "A Netball team has 7 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00057",
   "question": "Australian Open is associated with which sport?",
   "options": [
    "Cricket",
    "Table Tennis",
    "Tennis",
    "Football"
   ],
   "answer": 2,
   "explanation": "Australian Open is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00058",
   "question": "How many players are there in a Kabaddi team?",
   "options": [
    "11",
    "9",
    "7",
    "8"
   ],
   "answer": 2,
   "explanation": "A Kabaddi team has 7 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00059",
   "question": "Nehru Cup is associated with which sport?",
   "options": [
    "Badminton",
    "Hockey",
    "Tennis",
    "Football"
   ],
   "answer": 3,
   "explanation": "Nehru Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00060",
   "question": "How many players are there in a Handball team?",
   "options": [
    "4",
    "9",
    "7",
    "1"
   ],
   "answer": 2,
   "explanation": "A Handball team has 7 players.",
   "topic": "Sports Teams",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00061",
   "question": "French Open is associated with which sport?",
   "options": [
    "Hockey",
    "Tennis",
    "Cricket",
    "Football"
   ],
   "answer": 1,
   "explanation": "French Open is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00062",
   "question": "Which sport uses teams of 7 players?",
   "options": [
    "Table tennis (singles)",
    "Netball",
    "Rugby union",
    "Baseball"
   ],
   "answer": 1,
   "explanation": "Teams of 7 players play Netball.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00063",
   "question": "Sudirman Cup is associated with which sport?",
   "options": [
    "Badminton",
    "Cricket",
    "Table Tennis",
    "Tennis"
   ],
   "answer": 0,
   "explanation": "Sudirman Cup is associated with Badminton.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00064",
   "question": "Which sport uses teams of 11 players?",
   "options": [
    "Kho Kho",
    "Basketball",
    "Baseball",
    "Football"
   ],
   "answer": 3,
   "explanation": "Teams of 11 players play Football.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00065",
   "question": "Bordoloi Trophy is associated with which sport?",
   "options": [
    "Football",
    "Hockey",
    "Badminton",
    "Cricket"
   ],
   "answer": 0,
   "explanation": "Bordoloi Trophy is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00066",
   "question": "Which sport uses teams of 2 players?",
   "options": [
    "Baseball",
    "Badminton (doubles)",
    "Volleyball",
    "Hockey"
   ],
   "answer": 1,
   "explanation": "Teams of 2 players play Badminton (doubles).",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00067",
   "question": "Ryder Cup is associated with which sport?",
   "options": [
    "Tennis",
    "Golf",
    "Cricket",
    "Badminton"
   ],
   "answer": 1,
   "explanation": "Ryder Cup is associated with Golf.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00068",
   "question": "Which sport uses teams of 6 players?",
   "options": [
    "Badminton (doubles)",
    "Volleyball",
    "Basketball",
    "Hockey"
   ],
   "answer": 1,
   "explanation": "Teams of 6 players play Volleyball.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00069",
   "question": "Wimbledon is associated with which sport?",
   "options": [
    "Cricket",
    "Football",
    "Tennis",
    "Table Tennis"
   ],
   "answer": 2,
   "explanation": "Wimbledon is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00070",
   "question": "Which sport uses teams of 5 players?",
   "options": [
    "Ice hockey",
    "Water polo",
    "Football",
    "Basketball"
   ],
   "answer": 3,
   "explanation": "Teams of 5 players play Basketball.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00071",
   "question": "Vijay Hazare Trophy is associated with which sport?",
   "options": [
    "Table Tennis",
    "Golf",
    "Tennis",
    "Cricket"
   ],
   "answer": 3,
   "explanation": "Vijay Hazare Trophy is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00072",
   "question": "Which sport uses teams of 11 players?",
   "options": [
    "Rugby union",
    "Rugby sevens",
    "Kho Kho",
    "Cricket"
   ],
   "answer": 3,
   "explanation": "Teams of 11 players play Cricket.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00073",
   "question": "All England Open is associated with which sport?",
   "options": [
    "Tennis",
    "Cricket",
    "Badminton",
    "Golf"
   ],
   "answer": 2,
   "explanation": "All England Open is associated with Badminton.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00074",
   "question": "Which sport uses teams of 7 players?",
   "options": [
    "Netball",
    "Rugby sevens",
    "Hockey",
    "Volleyball"
   ],
   "answer": 1,
   "explanation": "Teams of 7 players play Rugby sevens.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00075",
   "question": "Beighton Cup is associated with which sport?",
   "options": [
    "Table Tennis",
    "Hockey",
    "Football",
    "Cricket"
   ],
   "answer": 1,
   "explanation": "Beighton Cup is associated with Hockey.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00076",
   "question": "Which sport uses teams of 7 players?",
   "options": [
    "Netball",
    "Hockey",
    "Kho Kho",
    "Kabaddi"
   ],
   "answer": 3,
   "explanation": "Teams of 7 players play Kabaddi.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00077",
   "question": "Uber Cup is associated with which sport?",
   "options": [
    "Tennis",
    "Badminton",
    "Hockey",
    "Cricket"
   ],
   "answer": 1,
   "explanation": "Uber Cup is associated with Badminton.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00078",
   "question": "Which sport uses teams of 9 players?",
   "options": [
    "Kabaddi",
    "Cricket",
    "Badminton (doubles)",
    "Kho Kho"
   ],
   "answer": 3,
   "explanation": "Teams of 9 players play Kho Kho.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00079",
   "question": "Durand Cup is associated with which sport?",
   "options": [
    "Football",
    "Tennis",
    "Golf",
    "Cricket"
   ],
   "answer": 0,
   "explanation": "Durand Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00080",
   "question": "Which sport uses teams of 1 players?",
   "options": [
    "Volleyball",
    "Rugby union",
    "Table tennis (singles)",
    "Badminton (doubles)"
   ],
   "answer": 2,
   "explanation": "Teams of 1 players play Table tennis (singles).",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00081",
   "question": "UEFA Champions League is associated with which sport?",
   "options": [
    "Cricket",
    "Tennis",
    "Badminton",
    "Football"
   ],
   "answer": 3,
   "explanation": "UEFA Champions League is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00082",
   "question": "Which sport uses teams of 7 players?",
   "options": [
    "Handball",
    "Football",
    "Basketball",
    "Kabaddi"
   ],
   "answer": 0,
   "explanation": "Teams of 7 players play Handball.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00083",
   "question": "Thomas Cup is associated with which sport?",
   "options": [
    "Cricket",
    "Football",
    "Hockey",
    "Badminton"
   ],
   "answer": 3,
   "explanation": "Thomas Cup is associated with Badminton.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00084",
   "question": "Which sport uses teams of 9 players?",
   "options": [
    "Cricket",
    "Baseball",
    "Kho Kho",
    "Handball"
   ],
   "answer": 1,
   "explanation": "Teams of 9 players play Baseball.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00085",
   "question": "Azlan Shah Trophy is associated with which sport?",
   "options": [
    "Football",
    "Tennis",
    "Hockey",
    "Golf"
   ],
   "answer": 2,
   "explanation": "Azlan Shah Trophy is associated with Hockey.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00086",
   "question": "Which sport uses teams of 8 players?",
   "options": [
    "Korfball",
    "Netball",
    "Badminton (doubles)",
    "Kho Kho"
   ],
   "answer": 0,
   "explanation": "Teams of 8 players play Korfball.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00087",
   "question": "Swaythling Cup is associated with which sport?",
   "options": [
    "Table Tennis",
    "Football",
    "Hockey",
    "Tennis"
   ],
   "answer": 0,
   "explanation": "Swaythling Cup is associated with Table Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00088",
   "question": "Which sport uses teams of 4 players?",
   "options": [
    "Netball",
    "Polo",
    "Rugby sevens",
    "Hockey"
   ],
   "answer": 1,
   "explanation": "Teams of 4 players play Polo.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00089",
   "question": "Aga Khan Cup is associated with which sport?",
   "options": [
    "Golf",
    "Football",
    "Hockey",
    "Table Tennis"
   ],
   "answer": 2,
   "explanation": "Aga Khan Cup is associated with Hockey.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00090",
   "question": "Which sport uses teams of 15 players?",
   "options": [
    "Baseball",
    "Throwball",
    "Rugby union",
    "Badminton (doubles)"
   ],
   "answer": 2,
   "explanation": "Teams of 15 players play Rugby union.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00091",
   "question": "FIFA World Cup is associated with which sport?",
   "options": [
    "Hockey",
    "Football",
    "Cricket",
    "Tennis"
   ],
   "answer": 1,
   "explanation": "FIFA World Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00092",
   "question": "Which sport uses teams of 6 players?",
   "options": [
    "Badminton (doubles)",
    "Handball",
    "Ice hockey",
    "Table tennis (singles)"
   ],
   "answer": 2,
   "explanation": "Teams of 6 players play Ice hockey.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00093",
   "question": "Grand Slam (Tennis) is associated with which sport?",
   "options": [
    "Badminton",
    "Football",
    "Tennis",
    "Cricket"
   ],
   "answer": 2,
   "explanation": "Grand Slam (Tennis) is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00094",
   "question": "Which sport uses teams of 7 players?",
   "options": [
    "Badminton (doubles)",
    "Rugby union",
    "Water polo",
    "Netball"
   ],
   "answer": 2,
   "explanation": "Teams of 7 players play Water polo.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00095",
   "question": "Sultan Azlan Shah Cup is associated with which sport?",
   "options": [
    "Football",
    "Hockey",
    "Badminton",
    "Tennis"
   ],
   "answer": 1,
   "explanation": "Sultan Azlan Shah Cup is associated with Hockey.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00096",
   "question": "Which sport uses teams of 11 players?",
   "options": [
    "Badminton (doubles)",
    "Throwball",
    "Table tennis (singles)",
    "Hockey"
   ],
   "answer": 3,
   "explanation": "Teams of 11 players play Hockey.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00097",
   "question": "US Open is associated with which sport?",
   "options": [
    "Tennis",
    "Table Tennis",
    "Cricket",
    "Football"
   ],
   "answer": 0,
   "explanation": "US Open is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00098",
   "question": "Which sport uses teams of 7 players?",
   "options": [
    "Handball",
    "Throwball",
    "Rugby union",
    "Table tennis (singles)"
   ],
   "answer": 1,
   "explanation": "Teams of 7 players play Throwball.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00099",
   "question": "Indian Premier League is associated with which sport?",
   "options": [
    "Cricket",
    "Football",
    "Badminton",
    "Hockey"
   ],
   "answer": 0,
   "explanation": "Indian Premier League is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00100",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Water polo - 1",
    "Water polo - 7",
    "Water polo - 11",
    "Water polo - 5"
   ],
   "answer": 1,
   "explanation": "Only Water polo - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00101",
   "question": "Merdeka Cup is associated with which sport?",
   "options": [
    "Table Tennis",
    "Football",
    "Badminton",
    "Tennis"
   ],
   "answer": 1,
   "explanation": "Merdeka Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00102",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Water polo - 2",
    "Water polo - 9",
    "Water polo - 11",
    "Water polo - 7"
   ],
   "answer": 3,
   "explanation": "Only Water polo - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00103",
   "question": "Khelo India Games is associated with which sport?",
   "options": [
    "Football",
    "Table Tennis",
    "Hockey",
    "Multi-sport"
   ],
   "answer": 3,
   "explanation": "Khelo India Games is associated with Multi-sport.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00104",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Badminton (doubles) - 5",
    "Badminton (doubles) - 2",
    "Badminton (doubles) - 9",
    "Badminton (doubles) - 11"
   ],
   "answer": 1,
   "explanation": "Only Badminton (doubles) - 2 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00105",
   "question": "World Test Championship is associated with which sport?",
   "options": [
    "Cricket",
    "Football",
    "Badminton",
    "Tennis"
   ],
   "answer": 0,
   "explanation": "World Test Championship is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00106",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Badminton (doubles) - 8",
    "Badminton (doubles) - 2",
    "Badminton (doubles) - 9",
    "Badminton (doubles) - 7"
   ],
   "answer": 1,
   "explanation": "Only Badminton (doubles) - 2 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00107",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Syed Mushtaq Ali Trophy",
    "Bordoloi Trophy",
    "Grand Slam (Tennis)",
    "Swaythling Cup"
   ],
   "answer": 0,
   "explanation": "Syed Mushtaq Ali Trophy is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00108",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Basketball - 6",
    "Basketball - 5",
    "Basketball - 9",
    "Basketball - 7"
   ],
   "answer": 1,
   "explanation": "Only Basketball - 5 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00109",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Durand Cup",
    "All England Open",
    "Rovers Cup",
    "World Cup (Cricket)"
   ],
   "answer": 3,
   "explanation": "World Cup (Cricket) is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00110",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Basketball - 15",
    "Basketball - 7",
    "Basketball - 5",
    "Basketball - 9"
   ],
   "answer": 2,
   "explanation": "Only Basketball - 5 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00111",
   "question": "Which trophy or cup is associated with Table Tennis?",
   "options": [
    "Corbillon Cup",
    "Khelo India Games",
    "Sudirman Cup",
    "Azlan Shah Trophy"
   ],
   "answer": 0,
   "explanation": "Corbillon Cup is associated with Table Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00112",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Volleyball - 2",
    "Volleyball - 4",
    "Volleyball - 7",
    "Volleyball - 6"
   ],
   "answer": 3,
   "explanation": "Only Volleyball - 6 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00113",
   "question": "Which trophy or cup is associated with Tennis?",
   "options": [
    "US Open",
    "World Cup (Cricket)",
    "Aga Khan Cup",
    "Swaythling Cup"
   ],
   "answer": 0,
   "explanation": "US Open is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00114",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Volleyball - 9",
    "Volleyball - 6",
    "Volleyball - 7",
    "Volleyball - 15"
   ],
   "answer": 1,
   "explanation": "Only Volleyball - 6 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00115",
   "question": "Which trophy or cup is associated with Football?",
   "options": [
    "Grand Slam (Tennis)",
    "Subroto Cup",
    "World Test Championship",
    "Azlan Shah Trophy"
   ],
   "answer": 1,
   "explanation": "Subroto Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00116",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Hockey - 7",
    "Hockey - 8",
    "Hockey - 11",
    "Hockey - 4"
   ],
   "answer": 2,
   "explanation": "Only Hockey - 11 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00117",
   "question": "Which trophy or cup is associated with Hockey?",
   "options": [
    "Sudirman Cup",
    "Beighton Cup",
    "Syed Mushtaq Ali Trophy",
    "Australian Open"
   ],
   "answer": 1,
   "explanation": "Beighton Cup is associated with Hockey.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00118",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Hockey - 7",
    "Hockey - 4",
    "Hockey - 11",
    "Hockey - 5"
   ],
   "answer": 2,
   "explanation": "Only Hockey - 11 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00119",
   "question": "Which trophy or cup is associated with Football?",
   "options": [
    "Nehru Cup",
    "Syed Mushtaq Ali Trophy",
    "Vijay Hazare Trophy",
    "World Cup (Cricket)"
   ],
   "answer": 0,
   "explanation": "Nehru Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00120",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Polo - 7",
    "Polo - 8",
    "Polo - 4",
    "Polo - 5"
   ],
   "answer": 2,
   "explanation": "Only Polo - 4 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00121",
   "question": "Which trophy or cup is associated with Hockey?",
   "options": [
    "Champions Trophy (Cricket)",
    "Azlan Shah Trophy",
    "FIH Hockey World Cup",
    "Khelo India Games"
   ],
   "answer": 2,
   "explanation": "FIH Hockey World Cup is associated with Hockey.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00122",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Polo - 4",
    "Polo - 7",
    "Polo - 6",
    "Polo - 5"
   ],
   "answer": 0,
   "explanation": "Only Polo - 4 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00123",
   "question": "Which trophy or cup is associated with Tennis?",
   "options": [
    "Grand Slam (Tennis)",
    "Subroto Cup",
    "UEFA Champions League",
    "Swaythling Cup"
   ],
   "answer": 0,
   "explanation": "Grand Slam (Tennis) is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00124",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Rugby sevens - 11",
    "Rugby sevens - 9",
    "Rugby sevens - 7",
    "Rugby sevens - 8"
   ],
   "answer": 2,
   "explanation": "Only Rugby sevens - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00125",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Davis Cup",
    "Vijay Hazare Trophy",
    "Swaythling Cup",
    "US Open"
   ],
   "answer": 1,
   "explanation": "Vijay Hazare Trophy is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00126",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Rugby sevens - 7",
    "Rugby sevens - 15",
    "Rugby sevens - 1",
    "Rugby sevens - 11"
   ],
   "answer": 0,
   "explanation": "Only Rugby sevens - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00127",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "World Test Championship",
    "Duleep Trophy",
    "The Ashes",
    "Azlan Shah Trophy"
   ],
   "answer": 0,
   "explanation": "World Test Championship is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00128",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Cricket - 9",
    "Cricket - 11",
    "Cricket - 15",
    "Cricket - 2"
   ],
   "answer": 1,
   "explanation": "Only Cricket - 11 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00129",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Indian Premier League",
    "Swaythling Cup",
    "Wimbledon",
    "World Test Championship"
   ],
   "answer": 0,
   "explanation": "Indian Premier League is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00130",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Cricket - 11",
    "Cricket - 2",
    "Cricket - 6",
    "Cricket - 8"
   ],
   "answer": 0,
   "explanation": "Only Cricket - 11 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00131",
   "question": "Which trophy or cup is associated with Table Tennis?",
   "options": [
    "Khelo India Games",
    "Sultan Azlan Shah Cup",
    "Beighton Cup",
    "Swaythling Cup"
   ],
   "answer": 3,
   "explanation": "Swaythling Cup is associated with Table Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00132",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Kho Kho - 9",
    "Kho Kho - 7",
    "Kho Kho - 6",
    "Kho Kho - 15"
   ],
   "answer": 0,
   "explanation": "Only Kho Kho - 9 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00133",
   "question": "Which trophy or cup is associated with Badminton?",
   "options": [
    "French Open",
    "All England Open",
    "Aga Khan Cup",
    "Thomas Cup"
   ],
   "answer": 1,
   "explanation": "All England Open is associated with Badminton.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00134",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Kho Kho - 6",
    "Kho Kho - 8",
    "Kho Kho - 11",
    "Kho Kho - 9"
   ],
   "answer": 3,
   "explanation": "Only Kho Kho - 9 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00135",
   "question": "Which trophy or cup is associated with Football?",
   "options": [
    "World Cup (Cricket)",
    "Duleep Trophy",
    "UEFA Champions League",
    "Uber Cup"
   ],
   "answer": 2,
   "explanation": "UEFA Champions League is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00136",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Netball - 4",
    "Netball - 11",
    "Netball - 6",
    "Netball - 7"
   ],
   "answer": 3,
   "explanation": "Only Netball - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00137",
   "question": "Which trophy or cup is associated with Tennis?",
   "options": [
    "Khelo India Games",
    "Wimbledon",
    "Merdeka Cup",
    "FIFA World Cup"
   ],
   "answer": 1,
   "explanation": "Wimbledon is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00138",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Netball - 7",
    "Netball - 1",
    "Netball - 8",
    "Netball - 5"
   ],
   "answer": 0,
   "explanation": "Only Netball - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00139",
   "question": "Which trophy or cup is associated with Tennis?",
   "options": [
    "Duleep Trophy",
    "Irani Cup",
    "Sultan Azlan Shah Cup",
    "French Open"
   ],
   "answer": 3,
   "explanation": "French Open is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00140",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Baseball - 1",
    "Baseball - 7",
    "Baseball - 2",
    "Baseball - 9"
   ],
   "answer": 3,
   "explanation": "Only Baseball - 9 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00141",
   "question": "Which trophy or cup is associated with Football?",
   "options": [
    "Sultan Azlan Shah Cup",
    "Bordoloi Trophy",
    "Merdeka Cup",
    "Vijay Hazare Trophy"
   ],
   "answer": 2,
   "explanation": "Merdeka Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00142",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Baseball - 7",
    "Baseball - 9",
    "Baseball - 4",
    "Baseball - 11"
   ],
   "answer": 1,
   "explanation": "Only Baseball - 9 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00143",
   "question": "Which trophy or cup is associated with Football?",
   "options": [
    "US Open",
    "Santosh Trophy",
    "Aga Khan Cup",
    "Grand Slam (Tennis)"
   ],
   "answer": 1,
   "explanation": "Santosh Trophy is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00144",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Throwball - 7",
    "Throwball - 11",
    "Throwball - 6",
    "Throwball - 5"
   ],
   "answer": 0,
   "explanation": "Only Throwball - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00145",
   "question": "Which trophy or cup is associated with Golf?",
   "options": [
    "Ryder Cup",
    "Nehru Cup",
    "Corbillon Cup",
    "Irani Cup"
   ],
   "answer": 0,
   "explanation": "Ryder Cup is associated with Golf.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00146",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Throwball - 7",
    "Throwball - 5",
    "Throwball - 9",
    "Throwball - 1"
   ],
   "answer": 0,
   "explanation": "Only Throwball - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00147",
   "question": "Which trophy or cup is associated with Hockey?",
   "options": [
    "Grand Slam (Tennis)",
    "Aga Khan Cup",
    "Durand Cup",
    "World Cup (Cricket)"
   ],
   "answer": 1,
   "explanation": "Aga Khan Cup is associated with Hockey.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00148",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Handball - 5",
    "Handball - 11",
    "Handball - 9",
    "Handball - 7"
   ],
   "answer": 3,
   "explanation": "Only Handball - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00149",
   "question": "Which trophy or cup is associated with Tennis?",
   "options": [
    "Davis Cup",
    "Sultan Azlan Shah Cup",
    "Ranji Trophy",
    "Syed Mushtaq Ali Trophy"
   ],
   "answer": 0,
   "explanation": "Davis Cup is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00150",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Handball - 7",
    "Handball - 4",
    "Handball - 15",
    "Handball - 2"
   ],
   "answer": 0,
   "explanation": "Only Handball - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00151",
   "question": "Which trophy or cup is associated with Football?",
   "options": [
    "US Open",
    "Beighton Cup",
    "Syed Mushtaq Ali Trophy",
    "Copa America"
   ],
   "answer": 3,
   "explanation": "Copa America is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00152",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Table tennis (singles) - 1",
    "Table tennis (singles) - 9",
    "Table tennis (singles) - 7",
    "Table tennis (singles) - 2"
   ],
   "answer": 0,
   "explanation": "Only Table tennis (singles) - 1 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00153",
   "question": "Which trophy or cup is associated with Badminton?",
   "options": [
    "Sudirman Cup",
    "Indian Premier League",
    "Grand Slam (Tennis)",
    "French Open"
   ],
   "answer": 0,
   "explanation": "Sudirman Cup is associated with Badminton.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00154",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Table tennis (singles) - 6",
    "Table tennis (singles) - 5",
    "Table tennis (singles) - 11",
    "Table tennis (singles) - 1"
   ],
   "answer": 3,
   "explanation": "Only Table tennis (singles) - 1 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00155",
   "question": "Which trophy or cup is associated with Football?",
   "options": [
    "The Ashes",
    "Bordoloi Trophy",
    "Rovers Cup",
    "Indian Premier League"
   ],
   "answer": 1,
   "explanation": "Bordoloi Trophy is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00156",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Korfball - 7",
    "Korfball - 5",
    "Korfball - 11",
    "Korfball - 8"
   ],
   "answer": 3,
   "explanation": "Only Korfball - 8 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00157",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Rovers Cup",
    "Davis Cup",
    "Asia Cup",
    "Sultan Azlan Shah Cup"
   ],
   "answer": 2,
   "explanation": "Asia Cup is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00158",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Korfball - 2",
    "Korfball - 8",
    "Korfball - 7",
    "Korfball - 11"
   ],
   "answer": 1,
   "explanation": "Only Korfball - 8 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00159",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Ryder Cup",
    "Champions Trophy (Cricket)",
    "Grand Slam (Tennis)",
    "Uber Cup"
   ],
   "answer": 1,
   "explanation": "Champions Trophy (Cricket) is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00160",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Kabaddi - 7",
    "Kabaddi - 8",
    "Kabaddi - 6",
    "Kabaddi - 5"
   ],
   "answer": 0,
   "explanation": "Only Kabaddi - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00161",
   "question": "Which trophy or cup is associated with Football?",
   "options": [
    "Rovers Cup",
    "Subroto Cup",
    "Aga Khan Cup",
    "Corbillon Cup"
   ],
   "answer": 0,
   "explanation": "Rovers Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00162",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Kabaddi - 11",
    "Kabaddi - 7",
    "Kabaddi - 4",
    "Kabaddi - 9"
   ],
   "answer": 1,
   "explanation": "Only Kabaddi - 7 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00163",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Duleep Trophy",
    "Merdeka Cup",
    "Grand Slam (Tennis)",
    "FIFA World Cup"
   ],
   "answer": 0,
   "explanation": "Duleep Trophy is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00164",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Football - 15",
    "Football - 5",
    "Football - 1",
    "Football - 11"
   ],
   "answer": 3,
   "explanation": "Only Football - 11 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00165",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Deodhar Trophy",
    "Vijay Hazare Trophy",
    "Aga Khan Cup",
    "Corbillon Cup"
   ],
   "answer": 0,
   "explanation": "Deodhar Trophy is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00166",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Football - 2",
    "Football - 6",
    "Football - 11",
    "Football - 9"
   ],
   "answer": 2,
   "explanation": "Only Football - 11 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00167",
   "question": "Which trophy or cup is associated with Multi-sport?",
   "options": [
    "Beighton Cup",
    "Santosh Trophy",
    "Khelo India Games",
    "Champions Trophy (Cricket)"
   ],
   "answer": 2,
   "explanation": "Khelo India Games is associated with Multi-sport.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00168",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Ice hockey - 2",
    "Ice hockey - 5",
    "Ice hockey - 6",
    "Ice hockey - 7"
   ],
   "answer": 2,
   "explanation": "Only Ice hockey - 6 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00169",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Champions Trophy (Cricket)",
    "The Ashes",
    "Merdeka Cup",
    "All England Open"
   ],
   "answer": 1,
   "explanation": "The Ashes is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00170",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Ice hockey - 2",
    "Ice hockey - 7",
    "Ice hockey - 11",
    "Ice hockey - 6"
   ],
   "answer": 3,
   "explanation": "Only Ice hockey - 6 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00171",
   "question": "Which trophy or cup is associated with Hockey?",
   "options": [
    "Sultan Azlan Shah Cup",
    "Grand Slam (Tennis)",
    "Swaythling Cup",
    "Deodhar Trophy"
   ],
   "answer": 0,
   "explanation": "Sultan Azlan Shah Cup is associated with Hockey.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00172",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Rugby union - 11",
    "Rugby union - 15",
    "Rugby union - 7",
    "Rugby union - 1"
   ],
   "answer": 1,
   "explanation": "Only Rugby union - 15 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00173",
   "question": "Which trophy or cup is associated with Football?",
   "options": [
    "Champions Trophy (Cricket)",
    "Ranji Trophy",
    "Durand Cup",
    "Uber Cup"
   ],
   "answer": 2,
   "explanation": "Durand Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00174",
   "question": "Which of the following pairs of sport and number of players is correctly matched?",
   "options": [
    "Rugby union - 7",
    "Rugby union - 15",
    "Rugby union - 9",
    "Rugby union - 1"
   ],
   "answer": 1,
   "explanation": "Only Rugby union - 15 is correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00175",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Ranji Trophy",
    "US Open",
    "Irani Cup",
    "UEFA Champions League"
   ],
   "answer": 2,
   "explanation": "Irani Cup is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00176",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Rugby sevens - 7",
    "Water polo - 7",
    "Basketball - 6",
    "Baseball - 9"
   ],
   "answer": 2,
   "explanation": "The pair Basketball - 6 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00177",
   "question": "Which trophy or cup is associated with Badminton?",
   "options": [
    "Thomas Cup",
    "Merdeka Cup",
    "Irani Cup",
    "Beighton Cup"
   ],
   "answer": 0,
   "explanation": "Thomas Cup is associated with Badminton.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00178",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Volleyball - 6",
    "Rugby union - 15",
    "Rugby sevens - 7",
    "Kabaddi - 11"
   ],
   "answer": 3,
   "explanation": "The pair Kabaddi - 11 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00179",
   "question": "Which trophy or cup is associated with Badminton?",
   "options": [
    "Uber Cup",
    "World Cup (Cricket)",
    "Champions Trophy (Cricket)",
    "All England Open"
   ],
   "answer": 0,
   "explanation": "Uber Cup is associated with Badminton.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00180",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Kabaddi - 7",
    "Polo - 7",
    "Rugby union - 15",
    "Water polo - 7"
   ],
   "answer": 1,
   "explanation": "The pair Polo - 7 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00181",
   "question": "Which trophy or cup is associated with Hockey?",
   "options": [
    "Azlan Shah Trophy",
    "Durand Cup",
    "Uber Cup",
    "UEFA Champions League"
   ],
   "answer": 0,
   "explanation": "Azlan Shah Trophy is associated with Hockey.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00182",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Football - 11",
    "Handball - 7",
    "Rugby sevens - 6",
    "Polo - 4"
   ],
   "answer": 2,
   "explanation": "The pair Rugby sevens - 6 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00183",
   "question": "Which trophy or cup is associated with Cricket?",
   "options": [
    "Santosh Trophy",
    "Champions Trophy (Cricket)",
    "Subroto Cup",
    "Ranji Trophy"
   ],
   "answer": 3,
   "explanation": "Ranji Trophy is associated with Cricket.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00184",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Kho Kho - 9",
    "Rugby union - 15",
    "Volleyball - 7",
    "Polo - 4"
   ],
   "answer": 2,
   "explanation": "The pair Volleyball - 7 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00185",
   "question": "Which trophy or cup is associated with Football?",
   "options": [
    "Beighton Cup",
    "Davis Cup",
    "FIFA World Cup",
    "Grand Slam (Tennis)"
   ],
   "answer": 2,
   "explanation": "FIFA World Cup is associated with Football.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00186",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Baseball - 9",
    "Rugby sevens - 7",
    "Football - 9",
    "Table tennis (singles) - 1"
   ],
   "answer": 2,
   "explanation": "The pair Football - 9 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00187",
   "question": "Which trophy or cup is associated with Tennis?",
   "options": [
    "Irani Cup",
    "US Open",
    "Corbillon Cup",
    "Australian Open"
   ],
   "answer": 3,
   "explanation": "Australian Open is associated with Tennis.",
   "topic": "Trophies and Cups",
   "level": 2,
   "source": "generated"
  },
  {
   "id": "sports-00188",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Netball - 7",
    "Polo - 4",
    "Cricket - 7",
    "Kabaddi - 7"
   ],
   "answer": 2,
   "explanation": "The pair Cricket - 7 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00189",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Davis Cup - Tennis",
    "Davis Cup - Hockey",
    "Davis Cup - Cricket",
    "Davis Cup - Badminton"
   ],
   "answer": 0,
   "explanation": "Only Davis Cup - Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00190",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Rugby sevens - 7",
    "Kabaddi - 7",
    "Throwball - 1",
    "Kho Kho - 9"
   ],
   "answer": 2,
   "explanation": "The pair Throwball - 1 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00191",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Davis Cup - Cricket",
    "Davis Cup - Tennis",
    "Davis Cup - Golf",
    "Davis Cup - Hockey"
   ],
   "answer": 1,
   "explanation": "Only Davis Cup - Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00192",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Rugby union - 15",
    "Football - 11",
    "Kabaddi - 7",
    "Baseball - 8"
   ],
   "answer": 3,
   "explanation": "The pair Baseball - 8 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00193",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Subroto Cup - Cricket",
    "Subroto Cup - Football",
    "Subroto Cup - Hockey",
    "Subroto Cup - Tennis"
   ],
   "answer": 1,
   "explanation": "Only Subroto Cup - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00194",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Rugby union - 15",
    "Ice hockey - 15",
    "Netball - 7",
    "Kabaddi - 7"
   ],
   "answer": 1,
   "explanation": "The pair Ice hockey - 15 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00195",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Hockey - 11",
    "Korfball - 8",
    "Kabaddi - 7",
    "Badminton (doubles) - 9"
   ],
   "answer": 3,
   "explanation": "The pair Badminton (doubles) - 9 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00196",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Sultan Azlan Shah Cup - Multi-sport",
    "Sultan Azlan Shah Cup - Hockey",
    "Sultan Azlan Shah Cup - Cricket",
    "Sultan Azlan Shah Cup - Badminton"
   ],
   "answer": 1,
   "explanation": "Only Sultan Azlan Shah Cup - Hockey is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00197",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Water polo - 11",
    "Rugby sevens - 7",
    "Kabaddi - 7",
    "Volleyball - 6"
   ],
   "answer": 0,
   "explanation": "The pair Water polo - 11 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00198",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Sultan Azlan Shah Cup - Hockey",
    "Sultan Azlan Shah Cup - Football",
    "Sultan Azlan Shah Cup - Cricket",
    "Sultan Azlan Shah Cup - Table Tennis"
   ],
   "answer": 0,
   "explanation": "Only Sultan Azlan Shah Cup - Hockey is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00199",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Cricket - 11",
    "Netball - 6",
    "Throwball - 7",
    "Ice hockey - 6"
   ],
   "answer": 1,
   "explanation": "The pair Netball - 6 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00200",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Champions Trophy (Cricket) - Cricket",
    "Champions Trophy (Cricket) - Badminton",
    "Champions Trophy (Cricket) - Football",
    "Champions Trophy (Cricket) - Tennis"
   ],
   "answer": 0,
   "explanation": "Only Champions Trophy (Cricket) - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00201",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Hockey - 7",
    "Rugby sevens - 7",
    "Netball - 7",
    "Ice hockey - 6"
   ],
   "answer": 0,
   "explanation": "The pair Hockey - 7 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00202",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Champions Trophy (Cricket) - Football",
    "Champions Trophy (Cricket) - Cricket",
    "Champions Trophy (Cricket) - Badminton",
    "Champions Trophy (Cricket) - Hockey"
   ],
   "answer": 1,
   "explanation": "Only Champions Trophy (Cricket) - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00203",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Table tennis (singles) - 7",
    "Cricket - 11",
    "Basketball - 5",
    "Handball - 7"
   ],
   "answer": 0,
   "explanation": "The pair Table tennis (singles) - 7 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00204",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Duleep Trophy - Badminton",
    "Duleep Trophy - Football",
    "Duleep Trophy - Cricket",
    "Duleep Trophy - Tennis"
   ],
   "answer": 2,
   "explanation": "Only Duleep Trophy - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00205",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Kho Kho - 9",
    "Basketball - 5",
    "Korfball - 11",
    "Table tennis (singles) - 1"
   ],
   "answer": 2,
   "explanation": "The pair Korfball - 11 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00206",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Duleep Trophy - Football",
    "Duleep Trophy - Cricket",
    "Duleep Trophy - Tennis",
    "Duleep Trophy - Hockey"
   ],
   "answer": 1,
   "explanation": "Only Duleep Trophy - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00207",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Cricket - 11",
    "Rugby sevens - 7",
    "Throwball - 7",
    "Kho Kho - 11"
   ],
   "answer": 3,
   "explanation": "The pair Kho Kho - 11 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00208",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Asia Cup - Cricket",
    "Asia Cup - Tennis",
    "Asia Cup - Badminton",
    "Asia Cup - Football"
   ],
   "answer": 0,
   "explanation": "Only Asia Cup - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00209",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Ice hockey - 6",
    "Rugby union - 11",
    "Basketball - 5",
    "Handball - 7"
   ],
   "answer": 1,
   "explanation": "The pair Rugby union - 11 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00210",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Asia Cup - Tennis",
    "Asia Cup - Cricket",
    "Asia Cup - Football",
    "Asia Cup - Hockey"
   ],
   "answer": 1,
   "explanation": "Only Asia Cup - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00211",
   "question": "Which of the following pairs of sport and number of players is NOT correctly matched?",
   "options": [
    "Handball - 15",
    "Water polo - 7",
    "Basketball - 5",
    "Volleyball - 6"
   ],
   "answer": 0,
   "explanation": "The pair Handball - 15 is not correctly matched.",
   "topic": "Sports Teams",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00212",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Ryder Cup - Cricket",
    "Ryder Cup - Golf",
    "Ryder Cup - Football",
    "Ryder Cup - Badminton"
   ],
   "answer": 1,
   "explanation": "Only Ryder Cup - Golf is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00213",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Ryder Cup - Golf",
    "Ryder Cup - Badminton",
    "Ryder Cup - Football",
    "Ryder Cup - Tennis"
   ],
   "answer": 0,
   "explanation": "Only Ryder Cup - Golf is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00214",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Wimbledon - Tennis",
    "Wimbledon - Cricket",
    "Wimbledon - Badminton",
    "Wimbledon - Football"
   ],
   "answer": 0,
   "explanation": "Only Wimbledon - Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00215",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Wimbledon - Tennis",
    "Wimbledon - Badminton",
    "Wimbledon - Multi-sport",
    "Wimbledon - Cricket"
   ],
   "answer": 0,
   "explanation": "Only Wimbledon - Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00216",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "All England Open - Badminton",
    "All England Open - Cricket",
    "All England Open - Hockey",
    "All England Open - Multi-sport"
   ],
   "answer": 0,
   "explanation": "Only All England Open - Badminton is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00217",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "All England Open - Cricket",
    "All England Open - Tennis",
    "All England Open - Badminton",
    "All England Open - Football"
   ],
   "answer": 2,
   "explanation": "Only All England Open - Badminton is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00218",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Khelo India Games - Tennis",
    "Khelo India Games - Football",
    "Khelo India Games - Multi-sport",
    "Khelo India Games - Table Tennis"
   ],
   "answer": 2,
   "explanation": "Only Khelo India Games - Multi-sport is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00219",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Khelo India Games - Football",
    "Khelo India Games - Cricket",
    "Khelo India Games - Multi-sport",
    "Khelo India Games - Table Tennis"
   ],
   "answer": 2,
   "explanation": "Only Khelo India Games - Multi-sport is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00220",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Uber Cup - Football",
    "Uber Cup - Table Tennis",
    "Uber Cup - Tennis",
    "Uber Cup - Badminton"
   ],
   "answer": 3,
   "explanation": "Only Uber Cup - Badminton is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00221",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Uber Cup - Badminton",
    "Uber Cup - Football",
    "Uber Cup - Cricket",
    "Uber Cup - Hockey"
   ],
   "answer": 0,
   "explanation": "Only Uber Cup - Badminton is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00222",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Thomas Cup - Badminton",
    "Thomas Cup - Football",
    "Thomas Cup - Cricket",
    "Thomas Cup - Table Tennis"
   ],
   "answer": 0,
   "explanation": "Only Thomas Cup - Badminton is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00223",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Thomas Cup - Badminton",
    "Thomas Cup - Football",
    "Thomas Cup - Hockey",
    "Thomas Cup - Tennis"
   ],
   "answer": 0,
   "explanation": "Only Thomas Cup - Badminton is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00224",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Bordoloi Trophy - Multi-sport",
    "Bordoloi Trophy - Football",
    "Bordoloi Trophy - Hockey",
    "Bordoloi Trophy - Badminton"
   ],
   "answer": 1,
   "explanation": "Only Bordoloi Trophy - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00225",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Bordoloi Trophy - Football",
    "Bordoloi Trophy - Table Tennis",
    "Bordoloi Trophy - Hockey",
    "Bordoloi Trophy - Multi-sport"
   ],
   "answer": 0,
   "explanation": "Only Bordoloi Trophy - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00226",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "French Open - Cricket",
    "French Open - Football",
    "French Open - Tennis",
    "French Open - Badminton"
   ],
   "answer": 2,
   "explanation": "Only French Open - Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00227",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Corbillon Cup - Cricket",
    "Corbillon Cup - Tennis",
    "Corbillon Cup - Table Tennis",
    "Corbillon Cup - Hockey"
   ],
   "answer": 2,
   "explanation": "Only Corbillon Cup - Table Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00228",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Corbillon Cup - Table Tennis",
    "Corbillon Cup - Cricket",
    "Corbillon Cup - Golf",
    "Corbillon Cup - Hockey"
   ],
   "answer": 0,
   "explanation": "Only Corbillon Cup - Table Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00229",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Durand Cup - Tennis",
    "Durand Cup - Cricket",
    "Durand Cup - Football",
    "Durand Cup - Badminton"
   ],
   "answer": 2,
   "explanation": "Only Durand Cup - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00230",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Durand Cup - Hockey",
    "Durand Cup - Badminton",
    "Durand Cup - Football",
    "Durand Cup - Cricket"
   ],
   "answer": 2,
   "explanation": "Only Durand Cup - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00231",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Copa America - Football",
    "Copa America - Hockey",
    "Copa America - Tennis",
    "Copa America - Cricket"
   ],
   "answer": 0,
   "explanation": "Only Copa America - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00232",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Copa America - Cricket",
    "Copa America - Hockey",
    "Copa America - Golf",
    "Copa America - Football"
   ],
   "answer": 3,
   "explanation": "Only Copa America - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00233",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "The Ashes - Tennis",
    "The Ashes - Cricket",
    "The Ashes - Hockey",
    "The Ashes - Football"
   ],
   "answer": 1,
   "explanation": "Only The Ashes - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00234",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "The Ashes - Cricket",
    "The Ashes - Football",
    "The Ashes - Badminton",
    "The Ashes - Tennis"
   ],
   "answer": 0,
   "explanation": "Only The Ashes - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00235",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Swaythling Cup - Tennis",
    "Swaythling Cup - Table Tennis",
    "Swaythling Cup - Hockey",
    "Swaythling Cup - Cricket"
   ],
   "answer": 1,
   "explanation": "Only Swaythling Cup - Table Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00236",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Swaythling Cup - Cricket",
    "Swaythling Cup - Table Tennis",
    "Swaythling Cup - Tennis",
    "Swaythling Cup - Football"
   ],
   "answer": 1,
   "explanation": "Only Swaythling Cup - Table Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00237",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Grand Slam (Tennis) - Football",
    "Grand Slam (Tennis) - Hockey",
    "Grand Slam (Tennis) - Cricket",
    "Grand Slam (Tennis) - Tennis"
   ],
   "answer": 3,
   "explanation": "Only Grand Slam (Tennis) - Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00238",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Grand Slam (Tennis) - Football",
    "Grand Slam (Tennis) - Cricket",
    "Grand Slam (Tennis) - Tennis",
    "Grand Slam (Tennis) - Multi-sport"
   ],
   "answer": 2,
   "explanation": "Only Grand Slam (Tennis) - Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00239",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Beighton Cup - Hockey",
    "Beighton Cup - Football",
    "Beighton Cup - Badminton",
    "Beighton Cup - Cricket"
   ],
   "answer": 0,
   "explanation": "Only Beighton Cup - Hockey is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00240",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Santosh Trophy - Table Tennis",
    "Santosh Trophy - Hockey",
    "Santosh Trophy - Tennis",
    "Santosh Trophy - Football"
   ],
   "answer": 3,
   "explanation": "Only Santosh Trophy - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00241",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Santosh Trophy - Cricket",
    "Santosh Trophy - Tennis",
    "Santosh Trophy - Golf",
    "Santosh Trophy - Football"
   ],
   "answer": 3,
   "explanation": "Only Santosh Trophy - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00242",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Azlan Shah Trophy - Tennis",
    "Azlan Shah Trophy - Hockey",
    "Azlan Shah Trophy - Cricket",
    "Azlan Shah Trophy - Football"
   ],
   "answer": 1,
   "explanation": "Only Azlan Shah Trophy - Hockey is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00243",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Azlan Shah Trophy - Badminton",
    "Azlan Shah Trophy - Football",
    "Azlan Shah Trophy - Multi-sport",
    "Azlan Shah Trophy - Hockey"
   ],
   "answer": 3,
   "explanation": "Only Azlan Shah Trophy - Hockey is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00244",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Sudirman Cup - Tennis",
    "Sudirman Cup - Badminton",
    "Sudirman Cup - Hockey",
    "Sudirman Cup - Cricket"
   ],
   "answer": 1,
   "explanation": "Only Sudirman Cup - Badminton is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00245",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Sudirman Cup - Hockey",
    "Sudirman Cup - Badminton",
    "Sudirman Cup - Table Tennis",
    "Sudirman Cup - Football"
   ],
   "answer": 1,
   "explanation": "Only Sudirman Cup - Badminton is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00246",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Merdeka Cup - Hockey",
    "Merdeka Cup - Multi-sport",
    "Merdeka Cup - Tennis",
    "Merdeka Cup - Football"
   ],
   "answer": 3,
   "explanation": "Only Merdeka Cup - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00247",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Merdeka Cup - Football",
    "Merdeka Cup - Hockey",
    "Merdeka Cup - Table Tennis",
    "Merdeka Cup - Tennis"
   ],
   "answer": 0,
   "explanation": "Only Merdeka Cup - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00248",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "World Cup (Cricket) - Football",
    "World Cup (Cricket) - Tennis",
    "World Cup (Cricket) - Badminton",
    "World Cup (Cricket) - Cricket"
   ],
   "answer": 3,
   "explanation": "Only World Cup (Cricket) - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00249",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "World Cup (Cricket) - Hockey",
    "World Cup (Cricket) - Tennis",
    "World Cup (Cricket) - Multi-sport",
    "World Cup (Cricket) - Cricket"
   ],
   "answer": 3,
   "explanation": "Only World Cup (Cricket) - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00250",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "FIH Hockey World Cup - Hockey",
    "FIH Hockey World Cup - Football",
    "FIH Hockey World Cup - Badminton",
    "FIH Hockey World Cup - Table Tennis"
   ],
   "answer": 0,
   "explanation": "Only FIH Hockey World Cup - Hockey is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00251",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "FIH Hockey World Cup - Hockey",
    "FIH Hockey World Cup - Football",
    "FIH Hockey World Cup - Tennis",
    "FIH Hockey World Cup - Cricket"
   ],
   "answer": 0,
   "explanation": "Only FIH Hockey World Cup - Hockey is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00252",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "UEFA Champions League - Football",
    "UEFA Champions League - Table Tennis",
    "UEFA Champions League - Cricket",
    "UEFA Champions League - Tennis"
   ],
   "answer": 0,
   "explanation": "Only UEFA Champions League - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00253",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "UEFA Champions League - Cricket",
    "UEFA Champions League - Football",
    "UEFA Champions League - Table Tennis",
    "UEFA Champions League - Badminton"
   ],
   "answer": 1,
   "explanation": "Only UEFA Champions League - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00254",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "FIFA World Cup - Hockey",
    "FIFA World Cup - Football",
    "FIFA World Cup - Cricket",
    "FIFA World Cup - Tennis"
   ],
   "answer": 1,
   "explanation": "Only FIFA World Cup - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00255",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "FIFA World Cup - Tennis",
    "FIFA World Cup - Hockey",
    "FIFA World Cup - Football",
    "FIFA World Cup - Badminton"
   ],
   "answer": 2,
   "explanation": "Only FIFA World Cup - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00256",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "US Open - Football",
    "US Open - Cricket",
    "US Open - Tennis",
    "US Open - Badminton"
   ],
   "answer": 2,
   "explanation": "Only US Open - Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00257",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "US Open - Tennis",
    "US Open - Table Tennis",
    "US Open - Football",
    "US Open - Cricket"
   ],
   "answer": 0,
   "explanation": "Only US Open - Tennis is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00258",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Irani Cup - Badminton",
    "Irani Cup - Cricket",
    "Irani Cup - Football",
    "Irani Cup - Tennis"
   ],
   "answer": 1,
   "explanation": "Only Irani Cup - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00259",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Irani Cup - Football",
    "Irani Cup - Cricket",
    "Irani Cup - Golf",
    "Irani Cup - Badminton"
   ],
   "answer": 1,
   "explanation": "Only Irani Cup - Cricket is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  },
  {
   "id": "sports-00260",
   "question": "Which of the following pairs of trophy and sport is correctly matched?",
   "options": [
    "Rovers Cup - Golf",
    "Rovers Cup - Football",
    "Rovers Cup - Table Tennis",
    "Rovers Cup - Cricket"
   ],
   "answer": 1,
   "explanation": "Only Rovers Cup - Football is correctly matched.",
   "topic": "Trophies and Cups",
   "level": 3,
   "source": "generated"
  }
 ]
};
  if (typeof module !== "undefined" && module.exports) module.exports = data;
  if (typeof window !== "undefined") {
    window.QBANK_CATEGORIES = window.QBANK_CATEGORIES || {};
    window.QBANK_CATEGORIES[data.slug] = data;
  }
})();
