"use strict";
/** Curated MCQs: Awards and Honours */
module.exports = [
  { question: "Which is the highest civilian award of India?", options: ["Padma Vibhushan", "Bharat Ratna", "Padma Bhushan", "Padma Shri"], answer: 1, level: 1, explanation: "The Bharat Ratna is the highest civilian award of India." },
  { question: "Who was the first recipient of the Bharat Ratna?", options: ["Jawaharlal Nehru", "C. Rajagopalachari", "S. Radhakrishnan", "C. V. Raman"], answer: 1, level: 3, explanation: "C. Rajagopalachari was among the first recipients in 1954." },
  { question: "Which is the highest gallantry award of India?", options: ["Ashoka Chakra", "Param Vir Chakra", "Maha Vir Chakra", "Vir Chakra"], answer: 1, level: 1, explanation: "The Param Vir Chakra is the highest wartime gallantry award." },
  { question: "Who was the first woman to receive the Bharat Ratna?", options: ["Indira Gandhi", "Mother Teresa", "Sarojini Naidu", "Aruna Asaf Ali"], answer: 0, level: 3, explanation: "Indira Gandhi received the Bharat Ratna in 1971." },
  { question: "The Jnanpith Award is given for excellence in:", options: ["Cinema", "Literature", "Science", "Sports"], answer: 1, level: 2, explanation: "The Jnanpith Award honours writers in Indian languages." },
  { question: "The Dada Saheb Phalke Award is associated with:", options: ["Music", "Cinema", "Painting", "Theatre"], answer: 1, level: 2, explanation: "It is the highest award in Indian cinema." },
  { question: "Which award is the highest sporting honour of India?", options: ["Arjuna Award", "Dronacharya Award", "Major Dhyan Chand Khel Ratna", "Dhyan Chand Award"], answer: 2, level: 2, explanation: "The Khel Ratna is India's highest sporting honour." },
  { question: "The Dronacharya Award is given to:", options: ["Players", "Coaches", "Umpires", "Sports journalists"], answer: 1, level: 2, explanation: "The Dronacharya Award recognises outstanding coaches." },
  { question: "In which year was the Nobel Prize first awarded?", options: ["1895", "1901", "1913", "1920"], answer: 1, level: 2, explanation: "The first Nobel Prizes were awarded in 1901." },
  { question: "Who was the first Indian to win a Nobel Prize?", options: ["C. V. Raman", "Rabindranath Tagore", "Mother Teresa", "Amartya Sen"], answer: 1, level: 1, explanation: "Rabindranath Tagore won the Nobel Prize in Literature in 1913." },
  { question: "C. V. Raman won the Nobel Prize in which field?", options: ["Physics", "Chemistry", "Medicine", "Literature"], answer: 0, level: 2, explanation: "C. V. Raman won the Nobel Prize in Physics in 1930." },
  { question: "Amartya Sen won the Nobel Prize in which field?", options: ["Economics", "Physics", "Peace", "Literature"], answer: 0, level: 2, explanation: "Amartya Sen won the Nobel Memorial Prize in Economic Sciences in 1998." },
  { question: "The Ramon Magsaysay Award is often called the:", options: ["Asian Nobel Prize", "European Nobel Prize", "Indian Nobel Prize", "World Peace Prize"], answer: 0, level: 2, explanation: "It is popularly known as Asia's Nobel Prize." },
  { question: "Which award is given for bravery by children in India?", options: ["National Bravery Award", "Ashoka Chakra", "Kirti Chakra", "Shaurya Chakra"], answer: 0, level: 2, explanation: "The National Bravery Award honours brave children." },
  { question: "The Pulitzer Prize is associated with:", options: ["Journalism", "Medicine", "Physics", "Music only"], answer: 0, level: 2, explanation: "The Pulitzer Prize mainly recognises journalism and letters." },
  { question: "Which award is given to Indian scientists for research in science and technology?", options: ["Shanti Swarup Bhatnagar Prize", "Dada Saheb Phalke Award", "Jnanpith Award", "Vyas Samman"], answer: 0, level: 2, explanation: "The Shanti Swarup Bhatnagar Prize is a prestigious Indian science award." },
  { question: "The Gandhi Peace Prize is awarded by the Government of India for:", options: ["Social and economic development", "Cinema", "Sports", "Literature"], answer: 0, level: 3, explanation: "It recognises contributions to social, economic and political transformation." },
  { question: "Which is the highest award for valour in peacetime in India?", options: ["Param Vir Chakra", "Ashoka Chakra", "Maha Vir Chakra", "Sena Medal"], answer: 1, level: 2, explanation: "The Ashoka Chakra is awarded for peacetime gallantry." },
  { question: "The Oscar award is associated with which field?", options: ["Cinema", "Music", "Literature", "Science"], answer: 0, level: 1, explanation: "The Academy Awards, known as Oscars, honour cinema." },
  { question: "Which award is given for lifetime achievement in Indian sports?", options: ["Dhyan Chand Award", "Arjuna Award", "Khel Ratna", "Dronacharya Award"], answer: 0, level: 2, explanation: "The Dhyan Chand Award honours lifetime contribution to sports." },
  { question: "Who was the first Indian woman to win the Miss World title?", options: ["Aishwarya Rai", "Reita Faria", "Sushmita Sen", "Priyanka Chopra"], answer: 1, level: 3, explanation: "Reita Faria won the Miss World title in 1966." }
];
