"use strict";
/** Curated MCQs: Current Affairs (stable, verifiable developments) */
module.exports = [
  { question: "Which country hosted the G20 Summit in 2023?", options: ["Indonesia", "India", "Brazil", "Japan"], answer: 1, level: 1, explanation: "India hosted the 2023 G20 Summit in New Delhi." },
  { question: "Which Indian mission made a soft landing near the Moon's south pole in 2023?", options: ["Chandrayaan-2", "Chandrayaan-3", "Mangalyaan", "Gaganyaan"], answer: 1, level: 1, explanation: "Chandrayaan-3 landed near the lunar south pole in August 2023." },
  { question: "Aditya-L1 is India's first mission to study what?", options: ["The Moon", "The Sun", "Mars", "Asteroids"], answer: 1, level: 2, explanation: "Aditya-L1 is India's first solar observatory mission, placed at Lagrange point L1." },
  { question: "NISAR is a joint Earth observation mission between ISRO and which agency?", options: ["ESA", "NASA", "JAXA", "Roscosmos"], answer: 1, level: 2, explanation: "NISAR is a joint mission of ISRO and NASA." },
  { question: "Which scheme provides free cooking gas connections to poor women?", options: ["PM Ujjwala Yojana", "PM Awas Yojana", "PM Kisan", "Ayushman Bharat"], answer: 0, level: 1, explanation: "Pradhan Mantri Ujjwala Yojana provides LPG connections." },
  { question: "Ayushman Bharat provides health cover of how much per family per year?", options: ["1 lakh rupees", "2 lakh rupees", "5 lakh rupees", "10 lakh rupees"], answer: 2, level: 2, explanation: "The scheme offers 5 lakh rupees of health cover per family per year." },
  { question: "What does UPI stand for in digital payments?", options: ["Unified Payments Interface", "Universal Payment Instrument", "United Payment Index", "Unified Purchase Interface"], answer: 0, level: 1, explanation: "UPI stands for Unified Payments Interface." },
  { question: "India's G20 presidency theme in 2023 was:", options: ["One Earth, One Family, One Future", "Recover Together", "Shaping an Interconnected World", "Building Consensus"], answer: 0, level: 2, explanation: "The theme was Vasudhaiva Kutumbakam, One Earth, One Family, One Future." },
  { question: "Which organisation publishes the Human Development Index?", options: ["World Bank", "UNDP", "IMF", "WHO"], answer: 1, level: 2, explanation: "The UNDP publishes the Human Development Index." },
  { question: "Gaganyaan is India's programme for what?", options: ["Moon landing", "Human spaceflight", "Solar study", "Deep sea exploration"], answer: 1, level: 2, explanation: "Gaganyaan is India's human spaceflight programme." },
  { question: "Which digital payment push of India is built on Aadhaar and is known for direct benefit transfer?", options: ["Aadhaar Enabled Payment System", "Bharat BillPay", "NEFT", "IMPS"], answer: 0, level: 3, explanation: "Aadhaar Enabled Payment System enables banking through Aadhaar authentication." },
  { question: "The Quad grouping consists of India, Japan, Australia and which country?", options: ["China", "United States", "Russia", "France"], answer: 1, level: 2, explanation: "The Quad is India, Japan, Australia and the United States." },
  { question: "Which Indian city hosted the 2023 Cricket World Cup final?", options: ["Mumbai", "Ahmedabad", "Kolkata", "Chennai"], answer: 1, level: 2, explanation: "The final was played at the Narendra Modi Stadium in Ahmedabad." },
  { question: "Which country joined BRICS in 2024 along with others in the first expansion round?", options: ["Egypt", "Pakistan", "Sri Lanka", "Mexico"], answer: 0, level: 3, explanation: "Egypt, Ethiopia, Iran, Saudi Arabia and the UAE joined BRICS from January 2024." },
  { question: "What is India's ranking ambition under the 'Semicon India' programme?", options: ["Be a global semiconductor hub", "Ban chip imports", "Export only raw silicon", "Build only test facilities"], answer: 0, level: 3, explanation: "Semicon India aims to build a domestic semiconductor manufacturing ecosystem." },
  { question: "Which mission aims to provide piped drinking water to every rural household?", options: ["Jal Jeevan Mission", "Swachh Bharat", "Namami Gange", "Jal Shakti Abhiyan"], answer: 0, level: 1, explanation: "Jal Jeevan Mission targets functional household tap connections in rural areas." },
  { question: "The 'Make in India' initiative was launched in which year?", options: ["2012", "2014", "2016", "2018"], answer: 1, level: 1, explanation: "Make in India was launched in September 2014." },
  { question: "Which Indian state launched the world's largest solar park at Bhadla?", options: ["Gujarat", "Rajasthan", "Karnataka", "Madhya Pradesh"], answer: 1, level: 2, explanation: "Bhadla Solar Park is in Rajasthan." },
  { question: "What does the 'Digital India' programme primarily aim to do?", options: ["Provide digital infrastructure and services to citizens", "Reduce internet speed", "Ban cash", "Privatise telecom"], answer: 0, level: 2, explanation: "Digital India aims to deliver government services electronically and build digital infrastructure." },
  { question: "India's first indigenous aircraft carrier commissioned in 2022 is named:", options: ["INS Vikramaditya", "INS Vikrant", "INS Viraat", "INS Kolkata"], answer: 1, level: 2, explanation: "INS Vikrant, built at Kochi, was commissioned in September 2022." }
];
