"use strict";
/** Curated MCQs: Economics and Banking */
module.exports = [
  { question: "Who is known as the father of economics?", options: ["Adam Smith", "Karl Marx", "John Keynes", "David Ricardo"], answer: 0, level: 1, explanation: "Adam Smith wrote The Wealth of Nations in 1776." },
  { question: "In which year was the Reserve Bank of India established?", options: ["1925", "1935", "1947", "1949"], answer: 1, level: 2, explanation: "The RBI was established in 1935." },
  { question: "Which rate does the RBI charge while lending to commercial banks?", options: ["Repo rate", "Reverse repo rate", "Bank rate", "Prime rate"], answer: 0, level: 2, explanation: "The repo rate is the RBI's lending rate against securities." },
  { question: "Which committee recommended the Goods and Services Tax in India?", options: ["Kelkar Committee", "Narasimham Committee", "Rangarajan Committee", "Tendulkar Committee"], answer: 0, level: 3, explanation: "The Kelkar Committee recommended GST in India." },
  { question: "In which year was GST introduced in India?", options: ["2015", "2016", "2017", "2018"], answer: 2, level: 1, explanation: "GST was rolled out on 1 July 2017." },
  { question: "Which article of the Constitution provides for the GST Council?", options: ["Article 279A", "Article 280", "Article 112", "Article 148"], answer: 0, level: 3, explanation: "Article 279A provides for the GST Council." },
  { question: "Which body regulates the securities market in India?", options: ["SEBI", "RBI", "IRDAI", "PFRDA"], answer: 0, level: 1, explanation: "SEBI regulates the securities market." },
  { question: "Which is the apex bank for agricultural credit in India?", options: ["NABARD", "SIDBI", "EXIM Bank", "RBI"], answer: 0, level: 2, explanation: "NABARD is the apex institution for agricultural and rural credit." },
  { question: "Which institution prints currency notes in India?", options: ["Reserve Bank of India", "Government of India", "State Bank of India", "Ministry of Finance"], answer: 0, level: 1, explanation: "The RBI issues banknotes, while the government issues coins." },
  { question: "In which year were the first major banks nationalised in India?", options: ["1949", "1955", "1969", "1980"], answer: 2, level: 2, explanation: "Fourteen banks were nationalised in 1969." },
  { question: "Which plan was the first Five Year Plan of India?", options: ["1951-56", "1947-52", "1955-60", "1961-66"], answer: 0, level: 2, explanation: "The first Five Year Plan covered 1951-56 with a focus on agriculture." },
  { question: "Which body replaced the Planning Commission of India?", options: ["NITI Aayog", "Finance Commission", "NITI Board", "Economic Advisory Council"], answer: 0, level: 1, explanation: "NITI Aayog replaced the Planning Commission in 2015." },
  { question: "Which of these is a direct tax?", options: ["Income tax", "GST", "Customs duty", "Excise duty"], answer: 0, level: 1, explanation: "Income tax is a direct tax on income." },
  { question: "Which of these is an indirect tax?", options: ["GST", "Income tax", "Corporate tax", "Wealth tax"], answer: 0, level: 1, explanation: "GST is levied on goods and services and is an indirect tax." },
  { question: "What does fiscal deficit mean?", options: ["Excess of government expenditure over revenue", "Excess of imports over exports", "Excess of savings over investment", "Excess of revenue over expenditure"], answer: 0, level: 2, explanation: "Fiscal deficit is the gap between total expenditure and total receipts excluding borrowings." },
  { question: "In which year did India adopt liberalisation reforms?", options: ["1991", "1985", "1999", "2000"], answer: 0, level: 1, explanation: "India adopted LPG reforms in 1991." },
  { question: "Who is known as the architect of India's 1991 economic reforms?", options: ["Manmohan Singh", "P. Chidambaram", "Montek Singh Ahluwalia", "I. G. Patel"], answer: 0, level: 2, explanation: "Dr. Manmohan Singh was Finance Minister and led the reforms." },
  { question: "Which sector contributes the largest share to India's GDP?", options: ["Services", "Agriculture", "Manufacturing", "Mining"], answer: 0, level: 2, explanation: "The services sector contributes the largest share of GDP." },
  { question: "Which organisation publishes the Human Development Index?", options: ["UNDP", "World Bank", "IMF", "WTO"], answer: 0, level: 2, explanation: "The UNDP publishes the HDI." },
  { question: "Which index is used to measure retail inflation in India?", options: ["Consumer Price Index", "Wholesale Price Index", "Index of Industrial Production", "GDP deflator"], answer: 0, level: 2, explanation: "Retail inflation is tracked through the CPI." },
  { question: "Which is the oldest stock exchange in Asia?", options: ["Bombay Stock Exchange", "National Stock Exchange", "Calcutta Stock Exchange", "Tokyo Stock Exchange"], answer: 0, level: 2, explanation: "The BSE was established in 1875 and is the oldest in Asia." },
  { question: "What is the full form of MSP in agriculture?", options: ["Minimum Support Price", "Market Selling Price", "Maximum Support Price", "Minimum Selling Price"], answer: 0, level: 1, explanation: "MSP is the price at which the government buys crops from farmers." },
  { question: "Which body recommends the minimum support prices in India?", options: ["CACP", "NABARD", "FCI", "ICAR"], answer: 0, level: 3, explanation: "The Commission for Agricultural Costs and Prices recommends MSP." }
];
