"use strict";
/** Curated MCQs: Environmental Studies & Ecology */
module.exports = [
  { question: "Which day is celebrated as World Environment Day?", options: ["5 June", "5 July", "22 April", "16 September"], answer: 0, level: 1, explanation: "World Environment Day is observed on 5 June every year." },
  { question: "Which convention deals with the protection of the ozone layer?", options: ["Kyoto Protocol", "Montreal Protocol", "Ramsar Convention", "Basel Convention"], answer: 1, level: 2, explanation: "The Montreal Protocol of 1987 phases out ozone-depleting substances." },
  { question: "Which gas is mainly responsible for the depletion of the ozone layer?", options: ["Carbon dioxide", "Chlorofluorocarbon", "Methane", "Nitrous oxide"], answer: 1, level: 2, explanation: "Chlorofluorocarbons release chlorine that destroys ozone molecules." },
  { question: "The Kyoto Protocol aims to reduce the emission of:", options: ["Greenhouse gases", "Ozone", "Nitrogen", "Water vapour"], answer: 0, level: 2, explanation: "The Kyoto Protocol sets targets for reducing greenhouse gas emissions." },
  { question: "Which is the largest source of renewable energy in India?", options: ["Solar", "Wind", "Hydropower", "Biomass"], answer: 2, level: 3, explanation: "Hydropower has the largest installed renewable capacity in India." },
  { question: "What is the primary cause of global warming?", options: ["Ozone depletion", "Greenhouse gas emissions", "Acid rain", "Deforestation of deserts"], answer: 1, level: 1, explanation: "Greenhouse gases trap heat and cause global warming." },
  { question: "Which organisation publishes the Red List of threatened species?", options: ["UNEP", "IUCN", "WWF", "WHO"], answer: 1, level: 2, explanation: "IUCN publishes the Red List of Threatened Species." },
  { question: "Project Tiger was launched in which year?", options: ["1972", "1973", "1980", "1991"], answer: 1, level: 2, explanation: "Project Tiger was launched in 1973 to conserve tiger habitats." },
  { question: "Which is the largest tiger reserve in India by area?", options: ["Nagarjunsagar-Srisailam", "Jim Corbett", "Kanha", "Sundarbans"], answer: 0, level: 3, explanation: "Nagarjunsagar-Srisailam in Andhra Pradesh is the largest tiger reserve." },
  { question: "The term 'biodiversity' refers to:", options: ["Number of forests", "Variety of living organisms", "Amount of rainfall", "Level of pollution"], answer: 1, level: 1, explanation: "Biodiversity means the variety of life in a particular habitat or the planet." },
  { question: "Which is the chief greenhouse gas emitted by vehicles?", options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"], answer: 0, level: 1, explanation: "Burning fuel releases carbon dioxide, the main greenhouse gas." },
  { question: "Which pollution is caused by excessive sound in the environment?", options: ["Air pollution", "Noise pollution", "Water pollution", "Soil pollution"], answer: 1, level: 1, explanation: "Unwanted high-intensity sound causes noise pollution." },
  { question: "Which is the most hazardous air pollutant for humans?", options: ["Carbon monoxide", "Nitrogen", "Oxygen", "Argon"], answer: 0, level: 2, explanation: "Carbon monoxide binds with haemoglobin and reduces oxygen transport." },
  { question: "The Chipko movement was associated with:", options: ["Water conservation", "Forest conservation", "Wildlife protection", "Soil conservation"], answer: 1, level: 2, explanation: "The Chipko movement protected trees from being felled in Uttarakhand." },
  { question: "Which is India's first national park?", options: ["Kanha", "Jim Corbett", "Gir", "Bandipur"], answer: 1, level: 2, explanation: "Jim Corbett National Park, established in 1936, is India's first national park." },
  { question: "Which is the largest mangrove forest in the world?", options: ["Sundarbans", "Pichavaram", "Bhitarkanika", "Godavari delta"], answer: 0, level: 1, explanation: "The Sundarbans is the world's largest mangrove forest." },
  { question: "World Wildlife Day is observed on:", options: ["3 March", "21 March", "22 April", "5 June"], answer: 0, level: 2, explanation: "World Wildlife Day is observed on 3 March." },
  { question: "Which international agreement aims to limit global temperature rise?", options: ["Paris Agreement", "Kyoto Protocol", "Montreal Protocol", "Basel Convention"], answer: 0, level: 2, explanation: "The Paris Agreement of 2015 aims to keep warming well below 2 degrees Celsius." },
  { question: "Which of these is a biodegradable waste?", options: ["Plastic bag", "Vegetable peel", "Glass bottle", "Aluminium can"], answer: 1, level: 1, explanation: "Vegetable peels are organic and decompose naturally." },
  { question: "The Ganga Action Plan was launched to:", options: ["Increase irrigation", "Reduce pollution in the Ganga", "Promote fishing", "Build dams"], answer: 1, level: 2, explanation: "The Ganga Action Plan aimed at reducing pollution in the river." },
  { question: "Which renewable source uses the heat of the Earth's interior?", options: ["Solar energy", "Geothermal energy", "Tidal energy", "Wind energy"], answer: 1, level: 2, explanation: "Geothermal energy is derived from heat inside the Earth." },
  { question: "Which greenhouse gas is released in large quantities from paddy fields?", options: ["Methane", "Oxygen", "Helium", "Argon"], answer: 0, level: 3, explanation: "Flooded paddy fields produce methane through anaerobic decomposition." }
];
