"use strict";
/** Curated MCQs: Indian Polity */
module.exports = [
  { question: "The Constitution of India was adopted on which date?", options: ["15 August 1947", "26 November 1949", "26 January 1950", "2 October 1950"], answer: 1, level: 1, explanation: "The Constituent Assembly adopted the Constitution on 26 November 1949, now Constitution Day." },
  { question: "Who was the Chairman of the Drafting Committee of the Constitution?", options: ["Rajendra Prasad", "B. R. Ambedkar", "Jawaharlal Nehru", "Sardar Patel"], answer: 1, level: 1, explanation: "Dr B. R. Ambedkar chaired the Drafting Committee." },
  { question: "Which part of the Constitution contains the Fundamental Rights?", options: ["Part II", "Part III", "Part IV", "Part V"], answer: 1, level: 2, explanation: "Part III (Articles 12 to 35) lists the Fundamental Rights." },
  { question: "Which article is called the heart and soul of the Constitution by Ambedkar?", options: ["Article 14", "Article 19", "Article 32", "Article 44"], answer: 2, level: 3, explanation: "Article 32 gives citizens the right to move the Supreme Court for enforcement of rights." },
  { question: "How many Fundamental Duties are listed in the Constitution at present?", options: ["10", "11", "12", "9"], answer: 1, level: 2, explanation: "Eleven Fundamental Duties are listed in Article 51A after the 86th Amendment." },
  { question: "Who is the constitutional head of the Indian State?", options: ["Prime Minister", "President", "Chief Justice", "Speaker"], answer: 1, level: 1, explanation: "The President is the constitutional head; real executive power rests with the Council of Ministers." },
  { question: "What is the maximum strength of the Lok Sabha as per the Constitution?", options: ["545", "550", "552", "560"], answer: 2, level: 3, explanation: "Article 81 permits up to 552 members, including nominated Anglo-Indian members before 2020." },
  { question: "The Rajya Sabha is a permanent house because it cannot be dissolved. What is its maximum strength?", options: ["238", "245", "250", "252"], answer: 2, level: 3, explanation: "The Rajya Sabha can have up to 250 members." },
  { question: "Who administers the oath of office to the President?", options: ["Prime Minister", "Chief Justice of India", "Vice President", "Speaker"], answer: 1, level: 2, explanation: "The Chief Justice of India administers the oath." },
  { question: "A money bill can be introduced only in which house?", options: ["Rajya Sabha", "Lok Sabha", "Either house", "Joint sitting"], answer: 1, level: 2, explanation: "Money bills originate only in the Lok Sabha, on the President's recommendation." },
  { question: "Which amendment added the words socialist and secular to the Preamble?", options: ["24th", "42nd", "44th", "52nd"], answer: 1, level: 3, explanation: "The 42nd Amendment of 1976 added these words." },
  { question: "The Panchayati Raj system was given constitutional status by which amendment?", options: ["72nd", "73rd", "74th", "76th"], answer: 1, level: 2, explanation: "The 73rd Amendment (1992) gave constitutional status to Panchayati Raj institutions." },
  { question: "Who appoints the Chief Justice of a High Court?", options: ["Governor", "President", "Chief Justice of India", "State legislature"], answer: 1, level: 2, explanation: "The President appoints High Court judges in consultation with the Chief Justice of India and the Governor." },
  { question: "What is the tenure of a member of the Rajya Sabha?", options: ["5 years", "6 years", "4 years", "Life"], answer: 1, level: 1, explanation: "Rajya Sabha members serve six-year terms, with one third retiring every two years." },
  { question: "Which body conducts elections to Parliament and State legislatures in India?", options: ["NITI Aayog", "Election Commission", "UPSC", "Finance Commission"], answer: 1, level: 1, explanation: "The Election Commission of India supervises these elections." },
  { question: "The Governor of a state is appointed by whom?", options: ["Chief Minister", "President", "Prime Minister", "Chief Justice"], answer: 1, level: 1, explanation: "The President appoints the Governor for a term of five years." },
  { question: "Which schedule of the Constitution deals with anti-defection provisions?", options: ["Ninth Schedule", "Tenth Schedule", "Eleventh Schedule", "Twelfth Schedule"], answer: 1, level: 3, explanation: "The Tenth Schedule, added by the 52nd Amendment, covers defection." },
  { question: "In which case did the Supreme Court lay down the basic structure doctrine?", options: ["Golaknath case", "Kesavananda Bharati case", "Shankari Prasad case", "Minerva Mills case"], answer: 1, level: 3, explanation: "The Kesavananda Bharati judgment of 1973 established the basic structure doctrine." },
  { question: "Which article abolishes untouchability?", options: ["Article 15", "Article 16", "Article 17", "Article 18"], answer: 2, level: 2, explanation: "Article 17 abolishes untouchability in any form." },
  { question: "The idea of a Constituent Assembly for India was first proposed by whom?", options: ["M. N. Roy", "Gandhi", "Nehru", "Ambedkar"], answer: 0, level: 3, explanation: "M. N. Roy proposed the idea of a Constituent Assembly in 1934." }
];
