"use strict";
/** Curated MCQs: Reasoning */
module.exports = [
  { question: "Find the next number in the series: 2, 6, 12, 20, 30, ?", options: ["36", "40", "42", "44"], answer: 2, level: 1, explanation: "Differences are 4, 6, 8, 10, so the next difference is 12 and 30 + 12 = 42." },
  { question: "Find the next term: 1, 4, 9, 16, 25, ?", options: ["30", "36", "42", "49"], answer: 1, level: 1, explanation: "These are perfect squares: 1^2, 2^2, 3^2, 4^2, 5^2, so the next is 6^2 = 36." },
  { question: "Find the missing term: 3, 7, 15, 31, ?", options: ["63", "62", "48", "55"], answer: 0, level: 2, explanation: "Each term is double the previous term plus one: 31 x 2 + 1 = 63." },
  { question: "Complete the series: A, C, F, J, ?", options: ["N", "O", "P", "M"], answer: 1, level: 2, explanation: "Gaps increase by one letter: +2, +3, +4, so the next jump is +5, giving O." },
  { question: "If CAT is coded as 3-1-20, how is DOG coded?", options: ["4-15-7", "4-14-7", "3-15-7", "4-15-6"], answer: 0, level: 1, explanation: "Letters are replaced by their positions in the alphabet: D=4, O=15, G=7." },
  { question: "If in a code language MONKEY is written as XDJMNL, how is TIGER written?", options: ["SFDHU", "QDFHS", "SFDHT", "RFDFH"], answer: 1, level: 3, explanation: "Each letter is replaced by the letter two places before it in the alphabet after reversing the word." },
  { question: "Pointing to a photograph, a man said, 'She is the daughter of my grandfather's only son.' How is she related to him?", options: ["Cousin", "Sister", "Aunt", "Niece"], answer: 1, level: 2, explanation: "The grandfather's only son is the man's father, so the girl is his sister." },
  { question: "A is the brother of B. B is the sister of C. C is the father of D. How is A related to D?", options: ["Father", "Uncle", "Brother", "Grandfather"], answer: 1, level: 2, explanation: "A is the brother of D's father C, so A is D's uncle." },
  { question: "Ravi walks 5 km north, then turns right and walks 3 km, then turns right and walks 5 km. How far is he from the starting point?", options: ["3 km", "5 km", "8 km", "13 km"], answer: 0, level: 2, explanation: "The two north-south legs cancel out, leaving a displacement of 3 km east." },
  { question: "A man facing north turns 90 degrees clockwise, then 180 degrees anticlockwise. Which direction is he facing now?", options: ["North", "South", "East", "West"], answer: 3, level: 2, explanation: "North plus 90 degrees clockwise is East; 180 degrees anticlockwise from East is West." },
  { question: "Which one is the odd one out: 3, 5, 11, 14, 17?", options: ["11", "14", "17", "5"], answer: 1, level: 1, explanation: "All the numbers are prime except 14." },
  { question: "Which one does not belong: Circle, Square, Triangle, Cube?", options: ["Circle", "Square", "Triangle", "Cube"], answer: 3, level: 1, explanation: "Cube is a three-dimensional solid while the others are plane figures." },
  { question: "Statements: All roses are flowers. Some flowers fade quickly. Conclusion: Some roses fade quickly.", options: ["Definitely true", "Definitely false", "Cannot be determined", "Partly true"], answer: 2, level: 3, explanation: "The quick-fading flowers need not be roses, so the conclusion does not follow." },
  { question: "Statements: All men are mortal. Socrates is a man. Conclusion: Socrates is mortal.", options: ["Follows logically", "Does not follow", "Cannot be determined", "Contradicts the premise"], answer: 0, level: 1, explanation: "This is a valid syllogism, so the conclusion follows from the premises." },
  { question: "Find the next number: 5, 11, 23, 47, ?", options: ["95", "94", "96", "90"], answer: 0, level: 2, explanation: "Each term is double the previous term plus one: 47 x 2 + 1 = 95." },
  { question: "Which letter comes next: Z, X, V, T, ?", options: ["S", "R", "Q", "P"], answer: 1, level: 1, explanation: "The series skips one letter backwards each time, so after T comes R." },
  { question: "If SOUTH is written as TPVUI, how is EAST written?", options: ["FBTU", "FBUT", "FATU", "EBTU"], answer: 0, level: 2, explanation: "Each letter is replaced by the next letter of the alphabet: E-A-S-T becomes F-B-T-U." },
  { question: "In a row of 40 students, Ravi is 12th from the left. What is his position from the right?", options: ["28th", "29th", "27th", "30th"], answer: 1, level: 2, explanation: "Position from the right = 40 - 12 + 1 = 29." },
  { question: "Five friends sit in a row. A is to the left of B but to the right of C. Who is in the middle if B is at the extreme right and C at the extreme left of the group of three?", options: ["A", "B", "C", "Cannot be determined"], answer: 0, level: 3, explanation: "With C at the left and B at the right, A sits between them." },
  { question: "Which number replaces the question mark: 8, 27, 64, 125, ?", options: ["216", "200", "196", "225"], answer: 0, level: 2, explanation: "These are cubes: 2^3, 3^3, 4^3, 5^3, so the next is 6^3 = 216." },
  { question: "A clock shows 3 o'clock. What is the angle between the hour and minute hands?", options: ["45 degrees", "60 degrees", "90 degrees", "120 degrees"], answer: 2, level: 1, explanation: "Each hour mark is 30 degrees apart, so 3 marks give 90 degrees." },
  { question: "If 'blue' means 'green', 'green' means 'yellow' and 'yellow' means 'red', what is the colour of fresh grass?", options: ["Green", "Yellow", "Blue", "Red"], answer: 1, level: 3, explanation: "Grass is green, and in the code 'green' is called 'yellow'." }
];
